/*
 * Copyright Samsung Electronics Co., LTD.
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */

#pragma once

/*******************************************************************************************
 *
 * File: commondef.h
 *
 * Description: This file will have all definitions which are common to both legacy and json
 *
 *******************************************************************************************/

#include "types.h"
#include "protocolenv.h"

#define RCM_CATEGORY                       (17)

typedef enum
{
    SIT_PAYLOAD_TYPE_LEGACY = 0,
    SIT_PAYLOAD_TYPE_JSON = 1,
}SIT_PAYLOAD_TYPE;

#ifdef USE_JSON_PAYLOAD
static int protocolPayloadType = SIT_PAYLOAD_TYPE_JSON;    // JSON
#else
static int protocolPayloadType = SIT_PAYLOAD_TYPE_LEGACY;    // LEGACY
#endif

inline bool IsPayloadTypeJson() { return ProtocolEnv::getEnv().isJsonSupported(); }

typedef enum
{
    SIT_BASE_ID_CALL = 0x0000,
    SIT_BASE_ID_SMS = 0x0100,
    SIT_BASE_ID_SIM = 0x0200,
    SIT_BASE_ID_SAT = 0x0300,
    SIT_BASE_ID_DEVICEID =  0x0400,
    SIT_BASE_ID_SS = 0x0500,
    SIT_BASE_ID_PDP = 0x0600,
    SIT_BASE_ID_NET = 0x0700,
    SIT_BASE_ID_PWR = 0x0800,
    SIT_BASE_ID_MISC = 0x0900,
    SIT_BASE_ID_SND = 0x0A00,
    SIT_BASE_ID_IMS_MEDIA = 0x0B00,
    SIT_BASE_ID_AGPS = 0x0C00,
    SIT_BASE_ID_AIMS = 0x0D00,
    SIT_BASE_ID_VSIM = 0x0E00,
    SIT_BASE_ID_WFC = 0x0F00,
    SIT_BASE_ID_EMBMS = 0x1000,
    SIT_BASE_ID_OEM = 0x4000,
    SIT_BASE_ID_OEM2 = 0x4100,
    SIT_BASE_ID_OEM3 = 0x4200,
    SIT_BASE_ID_OEM4 = 0x4300,
    SIT_BASE_ID_OEM5 = 0x4400,
}SIT_BASE_ID;

typedef enum
{
    SIT_GET_CURRENT_CALLS = 0x0000,
    SIT_DIAL = 0x0001,
    SIT_GET_LAST_CALL_FAIL_CAUSE = 0x0002,
    SIT_DTMF = 0x0003,
    SIT_ANSWER = 0x0004,
    SIT_DTMF_START = 0x0005,
    SIT_DTMF_STOP = 0x0006,
    SIT_SEND_EXPLICIT_CALL_TRANSFER = 0x0007,
    SIT_HANGUP = 0x0008,
    SIT_IND_CALL_STATE_CHANGED = 0x0009,
    SIT_IND_CALL_RING = 0x000A,
    SIT_SET_SRVCC_CALL_LIST = 0x000B, // TODO: not used as per json document
    SIT_IND_SRVCC_HO = 0x000C,
    SIT_IND_EMERGENCY_CALL_LIST  = 0x000D,
    SIT_CALL_CONFIRM_FEATURE_SET_REQ = 0x000E, // TODO: not used as per json document
    SIT_CALL_CONFIRM = 0x000F,
    SIT_IND_CALL_PRESENT_IND = 0x0010,

    SIT_SET_CDMA_VOICE_PRIVACY_MODE = 0x0011,
    SIT_GET_CDMA_VOICE_PRIVACY_MODE = 0x0012,
    SIT_IND_CDMA_VOICE_PRIVACY_MODE = 0x0013, // TODO: not used as per json document

    SIT_IND_ENTER_EMERGENCY_CB_MODE = 0x0014,

    SIT_CDMA_BURST_DTMF = 0x0015,
    SIT_IND_OTA_PROVISION_STATUS = 0x0016,
    SIT_IND_CDMA_INFO_REC = 0x0017,

    SIT_IND_EMERGENCY_SUPPORT_RAT_MODE = 0x0018,
    SIT_IND_EXIT_EMERGENCY_CB_MODE = 0x0019,
    SIT_EXIT_EMERGENCY_CB_MODE = 0x001A,
    SIT_IND_MT_CSFB = 0x0024,
}SIT_ID_CALL;

typedef enum
{
    SIT_SEND_SMS  = 0x0100,
    SIT_SEND_SMS_EXPECT_MORE = 0x0101,
    SIT_SEND_SMS_ACK = 0x0102,
    SIT_WRITE_SMS_TO_SIM = 0x0103,
    SIT_DELETE_SMS_ON_SIM = 0x0104,
    SIT_GET_BCST_SMS_CFG = 0x0105,
    SIT_SET_BCST_SMS_CFG = 0x0106,
    SIT_ACT_BCST_SMS = 0x0107,
    SIT_GET_SMSC_ADDR = 0x0108,
    SIT_SET_SMSC_ADDR = 0x0109,
    SIT_SEND_SMS_MEM_STATUS = 0x010A,
    SIT_SEND_ACK_INCOMING_SMS = 0x010B,
    SIT_IND_NEW_SMS = 0x010C,
    SIT_IND_NEW_SMS_STATUS_REPORT = 0x010D,
    SIT_IND_NEW_SMS_ON_SIM = 0x010E,
    SIT_IND_SIM_SMS_STORAGE_FULL = 0x010F,
    SIT_IND_NEW_BCST_SMS = 0x0110,

    SIT_CDMA_SEND_SMS = 0x0111,
    SIT_CDMA_SEND_SMS_ACK = 0x0112,
    SIT_CDMA_GET_BCST_SMS_CFG = 0x0113,
    SIT_CDMA_SET_BCST_SMS_CFG = 0x0114,
    SIT_CDMA_ACT_BCST_SMS = 0x0115,
    SIT_CDMA_WRITE_SMS_TO_RUIM = 0x0116,
    SIT_CDMA_DELETE_SMS_ON_RUIM = 0x0117,
    SIT_IND_CDMA_NEW_SMS = 0x0118,
    SIT_IND_CDMA_RUIM_SMS_STORAGE_FULL = 0x0119,
    SIT_IND_CDMA_VOICE_MSG_WAITING_INFO = 0x0120,
    SIT_GET_STORED_SMS_COUNT =  0x0121,
    SIT_CDMA_SEND_SMS_EXPECT_MORE = 0x0122,
}SIT_ID_SMS;

typedef enum
{
    SIT_GET_SIM_STATUS = 0x0200,
    SIT_VERIFY_SIM_PIN = 0x0201,
    SIT_VERIFY_SIM_PUK = 0x0202,
    SIT_VERIFY_SIM_PIN2 = 0x0203,
    SIT_VERIFY_SIM_PUK2 = 0x0204,
    SIT_CHG_SIM_PIN = 0x0205,
    SIT_CHG_SIM_PIN2 = 0x0206,
    SIT_VERIFY_NETWORK_LOCK = 0x0207,
    SIT_SIM_IO = 0x0208,
    SIT_GET_FACILITY_LOCK = 0x0209,
    SIT_SET_FACILITY_LOCK = 0x020A,
    SIT_GET_SIM_AUTH = 0x020B,
    SIT_TRANSMIT_SIM_APDU_BASIC = 0x020C,
    SIT_OPEN_SIM_CHANNEL = 0x020D,
    SIT_CLOSE_SIM_CHANNEL = 0x020E,
    SIT_TRANSMIT_SIM_APDU_CHANNEL    = 0x020F,
    SIT_IND_SIM_STATUS_CHANGED = 0x0210,
    SIT_GET_GBA_CONTEXT = 0x0211,
    SIT_GET_ATR = 0x0212,
//SAP +
    SIT_SAP_CONNECT = 0x0220,
    SIT_SAP_DISCONNECT = 0x0221,
    SIT_IND_SAP_DISCONNECT = 0x0222,
    SIT_SAP_TRANSFER_APDU = 0x0223,
    SIT_SAP_TRANSFER_ATR = 0x0224,
    SIT_SAP_POWER_SIM_OFF = 0x0225,
    SIT_SAP_POWER_SIM_ON = 0x0226,
    SIT_SAP_RESET_SIM = 0x0227,
    SIT_IND_SAP_STATUS = 0x0228,
    SIT_SAP_TRANSFER_CARD_READER_STATUS = 0x0229,
    SIT_SAP_SET_TRANPORT_PROTOCOL = 0x022A,
//SAP -
//SIMPB +
    SIT_READ_PB_ENTRY = 0x0240,
    SIT_UPDATE_PB_ENTRY = 0x0241,
    SIT_GET_PB_STORAGE_INFO = 0x0242,
    SIT_GET_3G_PB_CAPA = 0x0245,
    SIT_IND_SIM_PB_READY = 0x0246,
    SIT_OPEN_SIM_CHANNEL_WITH_P2 = 0x0247,
//SIMPB -
    SIT_SET_UICC_SUBSCRIPTION = 0x0249,
    SIT_IND_UICC_SUBSCRIPTION_STATE_CHANGED = 0x024A,
    //SIT_GET_SIM_AUTH = 0x024B,    // ISIM_AUTH is changed into SIM_AUTH
    SIT_SET_SIM_CARD_POWER = 0x024C,

    // Radio Config
    SIT_GET_SLOT_STATUS = 0x024D,
    SIT_IND_SIM_SLOT_STATUS_CHANGED = 0x024E,
    SIT_IND_SIM_DATA_INFO = 0x024F,
    // TODO: id needs to be fixed when CP prepares this command
    SIT_SET_LOGICAL_TO_PHYSICAL_SLOT_MAPPING = 0x0250,

    // SIM_TRAY status
    SIT_IND_SIM_TRAY_STATUS_CHANGED = 0x0251,
}SIT_ID_SIM;

typedef enum
{
    SIT_SEND_STK_ENVELOPE_CMD = 0x0300,
    SIT_SEND_STK_TERMINAL_RSP = 0x0301,
    SIT_SEND_STK_ENVELOPE_WITH_STATUS= 0x0302,
    SIT_IND_STK_PROACTIVE_COMMAND = 0x0303,
    SIT_IND_SIM_REFRESH = 0x0304,
    SIT_STK_CALL_SETUP = 0x0305,
    SIT_IND_STK_SESSION_END = 0x0306,
    SIT_IND_STK_CC_ALPHA_NOTIFY = 0x0307,  // IPC NOT IN USE as per CP JSON document

    // BIP over WiFi
    SIT_IND_STK_WIFI_STATUS_REQUEST = 0x0309,
    SIT_SEND_STK_WIFI_STATUS_REPORT = 0x030A,
    SIT_SEND_STK_TCP_STATUS_EVENT = 0x030B,
    SIT_IND_STK_OPEN_CHANNEL_REQUEST = 0x030C,
    SIT_SEND_STK_WIFI_OPEN_CHANNEL_RSP = 0x030D,
    SIT_IND_STK_SEND_DATA_TO_WIFI = 0x030E,
    SIT_STK_SEND_WIFI_DATA_RESPONSE = 0x0310,
    SIT_IND_STK_RECEIVE_DATA_FROM_WIFI = 0x0311,
    SIT_STK_SEND_BIP_DATA_TO_SIM = 0x0312,
    SIT_IND_STK_CLOSE_CHANNEL_REQUEST = 0x0313,
    SIT_STK_SEND_CLOSE_CHANNEL_RESPONSE = 0x0314,
}SIT_ID_SAT;

typedef enum
{
    SIT_GET_IMSI =0x0400,
    SIT_GET_IMEI =0x0401,
    SIT_GET_IMEISV =0x0402,
    SIT_GET_DEVICE_ID =0x0403,
    SIT_SET_SGC = 0x0404,
    SIT_GET_SGC = 0x0405,
    SIT_SET_CARRIER_INFO_IMSI_ENCRYPTION =0x0406,
    SIT_IND_CARRIER_INFO_IMSI_ENCRYPTION = 0x0407,
    SIT_SET_CARRIER_CONFIG_MANIFEST = 0x0408,
    SIT_IND_CARRIER_CONFIG_STATUS = 0x0409,
    SIT_IND_CARRIER_CONFIG_SIM_INFO = 0x0410,
}SIT_ID_DEVICEID;

typedef enum
{
    SIT_HANGUP_WAITING_OR_BACKGROUND = 0x0500,
    SIT_HANGUP_FORGROUND_RESUME_BACKGROUND = 0x0501,
    SIT_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE = 0x0502,
    SIT_CONFERENCE = 0x0503,
    SIT_UDUB = 0x0504,
    SIT_SEND_USSD = 0x0505,
    SIT_CANCEL_USSD = 0x0506,
    SIT_GET_CLIR = 0x0507,
    SIT_GET_COLP= 0x0508,
    SIT_GET_CALL_FORWARD_STATUS = 0x0509,
    SIT_SET_CALL_FORWARD = 0x050A,
    SIT_GET_CALL_WAITING = 0x050B,
    SIT_SET_CALL_WAITING = 0x050C,
    SIT_CHG_BARRING_PWD = 0x050D,
    SIT_SEPARATE_CONNECTION = 0x050E,
    SIT_GET_CLIP = 0x050F,
    SIT_IND_ON_USSD = 0x0510,
    SIT_IND_SUPP_SVC_NOTIFICATION = 0x0511,
    SIT_GET_COLR= 0x0512,
    SIT_IND_SS_RETURN_RESULT = 0x0513,
    SIT_SET_CDMA_FLASH_INFO = 0x0514,
    SIT_IND_CDMA_CALL_WAITING = 0x0515,
    SIT_IND_ON_SS = 0x0516,  // NOT IN USE as per JSON doc
}SIT_ID_SS;

typedef enum
{
    SIT_SETUP_DATA_CALL = 0x0600,
    SIT_DEACT_DATA_CALL = 0x0601,
    SIT_GET_DATA_CALL_LIST = 0x0602,
    SIT_SET_INITIAL_ATTACH_APN = 0x0603,
    SIT_IND_DATA_CALL_LIST_CHANGED = 0x0604,
    SIT_SET_FD_INFO = 0x0605,
    SIT_IND_DEDICATED_BEARER_INFO = 0x0621,
    SIT_IND_NAS_TIMER_STATUS = 0x0607,
    SIT_DETACH = 0x0608,
    SIT_IND_DATA_STATE_CHANGE = 0x0609,
    SIT_START_KEEPALIVE = 0x060A,
    SIT_STOP_KEEPALIVE = 0x060B,
    SIT_IND_KEEPALIVE_STATUS = 0x060C,
    SIT_IND_PCO_DATA = 0x060D,
    SIT_START_LCE_INFO = 0x060E,
    SIT_STOP_LCE_INFO = 0x060F,
    SIT_GET_LCE_DATA = 0x0610,
    SIT_IND_LCE_DATA = 0x0611,
    SIT_SET_DATA_PROFILE = 0x0613,
    SIT_SET_IMS_TEST_MODE = 0x0614,
    SIT_GET_PHONE_CAPABILITY = 0x0615,
    SIT_SET_PDN_IP_ADDRESS = 0x0616,
    SIT_IND_IP_ADDR_STATUS = 0x0617,
    SIT_SET_DATA_CALL = 0x0618,
    SIT_IND_PS_DATA_OFF_STATUS = 0x0619,
    SIT_ALLOC_PDU_SESSION = 0x061A,
    SIT_REL_PDU_SESSION = 0x061B,
    SIT_START_HANDOVER = 0x061C,
    SIT_CANCEL_HANDOVER = 0x061D,
    SIT_IND_UNTHROTTLE_APN = 0x061E,
    SIT_GET_SLICING_CONFIG = 0x0622,
    SIT_IND_SLICING_CONFIG = 0x0623,
    SIT_SET_SLICING_CONFIG = 0x0624,
    SIT_SET_MOBILE_DATA_STATE = 0x0625,
}SIT_ID_PDP;

typedef enum
{
    SIT_GET_CS_REG_STATE = 0x0700,
    SIT_GET_PS_REG_STATE = 0x0701,
    SIT_GET_OPERATOR = 0x0702,
    SIT_GET_NTW_MODE = 0x0703,
    SIT_SET_NTW_MODE_AUTO = 0x0704,
    SIT_SET_NTW_MODE_MANUAL = 0x0705,
    SIT_GET_AVAILABLE_NETWORKS = 0x0706,
    SIT_CANCEL_GET_AVAILABLE_NETWORKS = 0x0707,
    SIT_SET_BAND_MODE = 0x0708,
    SIT_GET_BAND_MODE = 0x0709,
    SIT_SET_PREFERRED_NTW_TYPE = 0x070A,
    SIT_GET_PREFERRED_NTW_TYPE = 0x070B,
    SIT_GET_CELL_INFO_LIST = 0x070C,
    SIT_SET_CELL_INFO_LIST_REPORT_RATE = 0x070D,
    SIT_IND_NTW_STATE_CHANGED = 0x070E,
    SIT_IND_CELL_INFO_LIST = 0x070F,
    SIT_SET_PS_SERVICE = 0x0710,
    SIT_GET_PS_SERVICE = 0x0711,
    SIT_SET_EMERGENCY_CALL_STATUS = 0x0712,
    SIT_IND_EMERGENCY_ACT_INFO = 0x0713,
    SIT_SET_UPLMN = 0x0714,
    SIT_GET_UPLMN = 0x0715,
    SIT_SET_DS_NTW_TYPE = 0x0716,
    SIT_IND_NET_CURRENT_LTE_MODE  = 0x0717, // deprecated
    SIT_GET_RADIO_CAPABILITY = 0x0718,
    SIT_SET_RADIO_CAPABILITY = 0x0719,
    SIT_GET_DUPLEX_MODE  = 0x071A,
    SIT_SET_DUPLEX_MODE  = 0x071B,
    SIT_IND_LTE_CA_CHANGED  = 0x071C, // deprecated
    SIT_GET_LTE_CA_INFO = 0x071D, // deprecated
    SIT_GET_GSM_CELL_INFO = 0x071E,
    SIT_SET_MICRO_CELL_SEARCH = 0x071F,
    //SIT_IND_RC_INFO_RECV = 0x720,
    SIT_IND_AC_BARRING_INFO = 0x0720,
    SIT_SET_CDMA_ROAMING_PREFERENCE = 0x0721,
    SIT_GET_CDMA_ROAMING_PREFERENCE = 0x0722,
    SIT_SET_CDMA_HYBRID_MODE = 0x0723,
    SIT_GET_CDMA_HYBRID_MODE = 0x0724,
    SIT_SET_DUAL_NTW_AND_PS_TYPE = 0x072B,
    SIT_IND_TOTAL_OOS = 0x072C,
    SIT_IND_MCC = 0x072D,
    SIT_SET_CARRIER_RESTRICTIONS = 0x072E,
    SIT_GET_CARRIER_RESTRICTIONS = 0x072F,
    SIT_GET_MANUAL_BAND_MODE = 0x0730,
    SIT_SET_MANUAL_BAND_MODE = 0x0731,
    SIT_GET_RF_DESENSE_MODE = 0x0732,
    SIT_SET_RF_DESENSE_MODE = 0x0733,
    SIT_START_SCANNING_NETWORKS = 0x0734,
    SIT_STOP_SCANNING_NETWORKS = 0x0735,
    SIT_IND_SCANNING_NETWORKS = 0x0736,
    SIT_IND_RADIO_CAPABILITY = 0x0737,
    SIT_GET_MANUAL_RAT_MODE = 0x0738,
    SIT_SET_MANUAL_RAT_MODE = 0x0739,
    SIT_GET_FREQUENCY_LOCK = 0x073A,
    SIT_SET_FREQUENCY_LOCK = 0x073B,
    SIT_IND_B2_B1_CONFIG = 0x073C,
    SIT_SET_ENDC_MODE = 0x073D,
    SIT_GET_ENDC_MODE = 0x073E,
    SIT_IND_SCG_BEARER_ALLOCATION = 0x073F, // deprecated
    // Implementation is in PSService
    SIT_SET_PREFERRED_DATA_MODEM = 0x0740,
    // SIT_SET_MODEMS_CONFIG = ?,
    // SIT_GET_MODEMS_CONFIG = ?,
    // SIT_GET_PHONE_CAPABILITY = ?,
    SIT_IND_FREQUENCY_INFO = 0x0741,
    SIT_IND_PHYSICAL_CHANNEL_CONFIG = 0x0742,
    SIT_SET_LOCATION_UPDATE_SETTING = 0x0744,
    SIT_GET_FREQUENCY_INFO = 0x0746,
    SIT_IND_RRC_INFO = 0x0747, // deprecated
    SIT_SET_NR_MODE = 0x0748,
    SIT_GET_NR_MODE = 0x0749,
    SIT_IND_REG_FAILED = 0x074A,
    SIT_IND_BARRING_INFO_CHANGED = 0x074B,
    SIT_SET_SYSTEM_SELECTION_CHANNELS = 0x074C,
    SIT_GET_BARRING_INFOS = 0x074D,
    SIT_GET_SYSTEM_SELECTION_CHANNELS = 0x074E,
    SIT_SET_ALLOW_NETWORK = 0x074F,
    SIT_GET_ALLOW_NETWORK = 0x0750,
    SIT_SET_PLMN_LIST = 0x0751,
    SIT_GET_PLMN_LIST = 0x0752,
    SIT_IND_DSDS_STATUS = 0x0753,
    SIT_SET_TRIGGER_EPSFB = 0x0756,
}SIT_ID_NET;

typedef enum
{
    SIT_SET_RADIO_POWER = 0x0800,
    SIT_GET_RADIO_POWER = 0x0801,
    SIT_IND_RADIO_STATE_CHANGED = 0x0802,
    SIT_IND_RADIO_READY = 0x0803,
    SIT_IND_PHONE_RESET = 0x0804,
    SIT_IND_MODEM_RESTART = 0x0805,  // this command is not used by CP anymore as per JSON doc
    SIT_SET_STACK_STATUS = 0x080F,
    SIT_GET_STACK_STATUS = 0x0810,
}SIT_ID_PWR;

typedef enum
{
    SIT_GET_SIGNAL_STRENGTH = 0x0900,
    SIT_GET_BASEBAND_VERSION = 0x0901,
    SIT_SET_SCREEN_STATE = 0x0902,
    SIT_SET_TTY_MODE = 0x0903,
    SIT_GET_TTY_MODE = 0x0904,
    SIT_IND_NITZ_TIME_RECEIVED = 0x0905,
    SIT_IND_SIGNAL_STRENGTH = 0x0906,
    SIT_SET_CFG_DEFAULT = 0x0907,
    SIT_SET_ENG_MODE = 0x0908,
    SIT_SET_SCREEN_LINE = 0x0909,
    SIT_IND_DISPLAY_ENG = 0x090A,
    SIT_SET_DEBUG_TRACE = 0x090B,
    SIT_GET_ACTIVITY_INFO = 0x090C,
    SIT_SET_OPERATOR_INFO = 0x090D,
    SIT_SET_FEATURE_INFO = 0x090E,
    SIT_GET_CDMA_SUBSCRIPTION = 0x090F,

    SIT_SET_ENG_STRING_INPUT = 0x0910,
    SIT_GET_MSL_CODE = 0x0911,

    SIT_SET_VOICE_OPERATION = 0x091A,
    SIT_GET_VOICE_OPERATION = 0x091B,


    SIT_SET_PIN_CONTROL = 0x0920,
    SIT_IND_PIN_CONTROL = 0x0921,
    SIT_SET_DEVICE_INFO = 0x0922,

    SIT_GET_HW_CONFIG = 0x0926,
    SIT_IND_HW_CONFIG_CHANGED = 0x0927,
    SIT_SET_IND_CMD_FILTER = 0x0928,
    SIT_IND_CDMA_PRL_CHANGED = 0x0929,
    SIT_IND_SAR_CONTROL_STATE = 0x092A,
    SIT_SET_SENSOR_STATUS = 0x092B,

    SIT_SET_RSSI_SCAN = 0x092D,
    SIT_IND_RSSI_SCAN = 0x092E,
    SIT_SET_PREFERRED_CALL_CAPABILITY = 0x092F,
    SIT_GET_PREFERRED_CALL_CAPABILITY = 0x0930,
    SIT_SET_FORWARDING_AT_COMMAND = 0x0931,
    SIT_IND_FORWARDING_AT_COMMAND = 0x0932,
    SIT_SET_INTPS_SERVICE = 0x0933, /* DEPRECATED */

    SIT_SET_VOWIFI_HO_THRESHOLD = 0x0935,
    SIT_GET_RADIO_NODE = 0x0936,
    SIT_SET_RADIO_NODE = 0x0937,
    SIT_GET_VOLTE_PROVISION_UPDATE = 0x0938,
    SIT_SET_VOLTE_PROVISION_UPDATE = 0x0939,
    SIT_SET_SELFLOG = 0x093A,
    SIT_GET_SELFLOG_STATUS = 0x093B,
    SIT_IND_SELFLOG_STATUS = 0x093C,
    SIT_SET_ELEVATOR_SENSOR = 0x093D,

    SIT_SET_MODEM_CONFIG = 0x093F,
    SIT_SET_MODEM_LOG_DUMP = 0x0940,

    SIT_SET_SELFLOG_PROFILE = 0x0942,
    SIT_SET_SIGNAL_STRENGTH_REPORTING_CRITERIA = 0x0943,
    SIT_SET_LINK_CAPACITY_REPORTING_CRITERIA = 0x0944,
    SIT_IND_CURRENT_LINK_CAPACITY_ESTIMATE = 0x0945,

    SIT_SET_AP_SYSTEM_TIME = 0x0949,

    SIT_SET_NR_SILENCE_MODE = 0x094C,
    SIT_SET_DATA_THROTTLING = 0x094D,
    SIT_SET_LAB_TEST_CONFIG = 0x094E,
    SIT_GET_NR_SILENCE_MODE = 0x094F,
    SIT_IND_RF_CONNECTION = 0x0950,

    SIT_GET_VONR_CAPABILITY = 0x0953,
    SIT_SET_VONR_CAPABILITY = 0x0954,
    SIT_GET_NITZ_TIME = 0x0955,
    SIT_SET_DEVICE_SERVICE = 0x0956,
    SIT_GET_DEVICE_SERVICE = 0x0957,
    SIT_SET_BTL_BUFMAX_SIZE = 0x0961,
    SIT_SET_UL_MIMO  = 0x0962,
    SIT_IND_MAC_CE_INFO = 0x0971,
    SIT_QUERY_MAC_CE_INFO = 0x0972,
}SIT_ID_MISC;

/*typedef enum
{
    SIT_IND_SAR_CONTROL_STATE = 0x092A, // shifted to MISC group
    SIT_SET_SENSOR_STATUS = 0x092B, // shifted to MISC group
}SIT_ID_PSENSOR;*/

typedef enum
{
    SIT_SET_MUTE =0x0A00,
    SIT_GET_MUTE = 0x0A01,
    SIT_IND_RINGBACK_TONE = 0x0A02,
    SIT_SET_VOLUME = 0x0A03,
    SIT_GET_VOLUME = 0x0A04,
    SIT_SET_AUDIO_PATH = 0x0A05,
    SIT_GET_AUDIO_PATH = 0x0A06,
    SIT_SET_MULTI_MIC = 0x0A07,
    SIT_GET_MULTI_MIC = 0x0A08,
    SIT_SWITCH_VOICE_CALL_AUDIO = 0x0A09,
    SIT_SET_AUDIO_CLK = 0x0A0A,
    SIT_SET_AUDIO_LOOPBACK = 0x0A0B,
    SIT_IND_WB_AMR_REPORT = 0x0A0C,
    SIT_SET_WB_CAPABILITY = 0x0A0D,
    SIT_GET_WB_CAPABILITY = 0x0A0E,
    SIT_IND_RESEND_IN_CALL_MUTE = 0x0A0F,
}SIT_ID_SND;

// Added to support IMS MEDIA
typedef enum
{
    SIT_IMS_MEDIA_TEST_RCM = 0x0B00,
    SIT_IMS_MEDIA_INIT = 0x0B01,
    SIT_IMS_MEDIA_OPEN_SESSION = 0x0B02,
    SIT_IMS_MEDIA_CLOSE_SESSION = 0x0B03,
    SIT_IMS_MEDIA_MODIFY_SESSION = 0x0B04,
    SIT_IMS_MEDIA_SEND_DTMF = 0x0B05,
    SIT_IMS_MEDIA_START_DTMF = 0x0B06,
    SIT_IMS_MEDIA_STOP_DTMF =0x0B07,
    SIT_IMS_MEDIA_SEND_TEXT = 0x0B09,
    SIT_IMS_MEDIA_SEND_HEADER_EXTENSION = 0x0B0B,
    SIT_IMS_MEDIA_SET_MEDIA_QUALITY_THRESHOLD = 0x0B0D,
    SIT_IND_IMS_MEDIA_TEST_RCM = 0x0B00,
    SIT_IND_IMS_MEDIA_ON_DTMF_RECEIVED = 0x0B08,
    SIT_IND_IMS_MEDIA_ON_TEXT_RECEIVED = 0x0B0A,
    SIT_IND_IMS_MEDIA_ON_HEADER_EXTENSION_RECEIVED = 0x0B0C,
    SIT_IND_IMS_MEDIA_ON_FIRST_MEDIA_RECEIVED = 0x0B0E,
    SIT_IND_IMS_MEDIA_NOTIFY_MEDIA_INACTIVITY = 0x0B0F,
    SIT_IND_IMS_MEDIA_NOTIFY_PACKET_LOSS = 0x0B10,
    SIT_IND_IMS_MEDIA_NOTIFY_JITTER = 0x0B11,
    SIT_IND_IMS_MEDIA_ON_CALL_QUALITY_CHANGED = 0x0B12,
    SIT_IND_IMS_MEDIA_TRIGGER_AMBR_QUERY = 0x0B13,
    SIT_IMS_GET_OPERATION_MODE = 0x0B1C,
    SIT_IMS_SIP_MESSAGE = 0x0B1D,
    SIT_IMS_SET_REGISTRATION_STATUS = 0x0B14,
    SIT_IND_IMS_RRC_CONNECTION_FAILURE = 0x0B17,
    SIT_IND_IMS_DEREGISTERTAION = 0x0B18,
    SIT_IND_MT_CALL_GUARDTMR_STATUS = 0x0B19,
    SIT_IMS_START_TRAFFIC = 0x0B1E,
    SIT_IMS_STOP_TRAFFIC = 0x0B1F,
    SIT_IMS_WIFI_CONFIG_REQ = 0x0B21,

}SIT_ID_IMS;

typedef enum
{
    SIT_SET_GPS_FREQUENCY_AIDING            = 0x0C00,
    SIT_GET_LPP_SUPL_REQ_ECID_INFO          = 0x0C01,
    SIT_GET_RRLP_SUPL_REQ_ECID_INFO         = 0x0C02,
    SIT_IND_GPS_MEASURE_POS_REQ             = 0x0C03,
    SIT_IND_GPS_MEASURE_POSITION_RSP        = 0x0C04,
    SIT_IND_GPS_ASSIST_DATA                 = 0x0C05,
    SIT_IND_RELEASE_GPS                     = 0x0C06,
    SIT_GPS_MO_LOCATION_REQUEST             = 0x0C07,
    SIT_IND_GPS_MT_LOCATION_REQUEST         = 0x0C08,
    SIT_IND_RESET_GPS_ASSIST_DATA           = 0x0C09,
    SIT_GET_LPP_REQ_SERVING_CELL_INFO       = 0x0C0A,
    SIT_IND_LPP_REQUEST_CAPABILITIES        = 0x0C0B,
    SIT_LPP_PROVIDE_CAPABILITIES_IND        = 0x0C0C,
    SIT_IND_LPP_REQUEST_ASSIST_DATA         = 0x0C0D,
    SIT_IND_LPP_PROVIDE_ASSIST_DATA         = 0x0C0E,
    SIT_IND_LPP_REQUEST_LOCATION_INFO       = 0x0C0F,
    SIT_LPP_PROVIDE_LOCATION_INFO_IND       = 0x0C10,
    SIT_LPP_GPS_ERROR_IND                   = 0x0C11,
    SIT_IND_SUPL_LPP_DATA_INFO              = 0x0C12,
    SIT_IND_SUPL_NI_MESSAGE                 = 0x0C13,
    SIT_SET_GPS_SUPL_NI_READY               = 0x0C14,
    SIT_IND_3GPP_SEND_GANSS_ASSIT_DATA      = 0x0C15,
    SIT_IND_GANSS_MEAS_POS_MSG              = 0x0C16,
    SIT_SET_GANSS_MEAS_POS_RSP              = 0x0C17,
    SIT_IND_GANSS_AP_POS_CAP_REQ            = 0x0C18,
    SIT_IND_GANSS_AP_POS_CAP_RSP            = 0x0C19,
    SIT_GET_GSM_EXT_INFO_MSG                = 0x0C1A,
    SIT_GPS_CONTROL_PLANE_ENABLE            = 0x0C1B,
    SIT_GNSS_LPP_PROFILE_SET                = 0x0C1C,
    SIT_SET_GPS_LOCK_MODE                   = 0x0C20,
    SIT_GET_REFERENCE_LOCATION              = 0x0C21,
    SIT_IND_CDMA_GPS_POWER_ON               = 0x0C22,
    SIT_SET_PSEUDO_RANGE_MEASUREMENTS       = 0x0C23,
    SIT_IND_CDMA_SEND_ACQUSITION_ASSIT_DATA = 0x0C24,
    SIT_IND_CDMA_SESSION_CANCELLATION       = 0x0C25,
    SIT_GET_CDMA_PRECISE_TIME_AIDING_INFO   = 0x0C26,
    SIT_GET_GPS_CDMA_FREQ_AIDING            = 0x0C27,
    SIT_IND_GPS_LOCK_MODE                   = 0x0C28,
    SIT_IND_GPS_START_MDT_LOC               = 0x0C29,
    SIT_GPS_RETRIEVE_LOC_INFO               = 0x0C2A,
    SIT_IND_LPP_UPDATE_UE_LOC_INFO          = 0x0C2B,
    SIT_SET_GNSS_BLANKING                   = 0x0C2C,
    SIT_SET_GNSS_BLANKING_TDL               = 0x0C2D,
}SIT_ID_GPS;

//AIMS support start ---------------------
typedef enum
{
    SIT_AIMS_DIAL                               = 0x0D00,
    SIT_IND_AIMS_CALL_RING                      = 0x0D01,
    SIT_AIMS_ANSWER                             = 0x0D02,
    SIT_AIMS_HANGUP                             = 0x0D03,
    SIT_IND_AIMS_CALL_STATUS                    = 0x0D04,
    SIT_IND_AIMS_REGISTRATION                   = 0x0D05,
    SIT_AIMS_DEREGISTRATION                     = 0x0D06,
    SIT_AIMS_HIDDEN_MENU                        = 0x0D07,
    SIT_AIMS_ADD_PDN_INFO                       = 0x0D08,
    SIT_AIMS_CALL_MANAGE                        = 0x0D09,
    SIT_AIMS_SEND_DTMF                          = 0x0D0A,
    SIT_AIMS_SET_FRAME_TIME                     = 0x0D0B,
    SIT_AIMS_GET_FRAME_TIME                     = 0x0D0C,
    SIT_AIMS_CALL_MODIFY                        = 0x0D0D,
    SIT_IND_AIMS_CALL_MODIFY                    = 0x0D0E,
    SIT_AIMS_RESPONSE_CALL_MODIFY               = 0x0D0F,
    SIT_IND_AIMS_EXPIRE_INFO                    = 0x0D10,
    SIT_IND_AIMS_FRAME_TIME                     = 0x0D11,
    SIT_AIMS_CONF_CALL_ADD_REMOVE_USER          = 0x0D12,
    SIT_AIMS_ENHANCED_CONF_CALL                 = 0x0D13,
    SIT_AIMS_GET_CALL_FORWARD_STATUS            = 0x0D14,
    SIT_AIMS_SET_CALL_FORWARD_STATUS            = 0x0D15,
    SIT_AIMS_GET_CALL_WAITING                   = 0x0D16,
    SIT_AIMS_SET_CALL_WAITING                   = 0x0D17,
    SIT_AIMS_GET_CALL_BARRING                   = 0x0D18,
    SIT_AIMS_SET_CALL_BARRING                   = 0x0D19,
    SIT_IND_AIMS_SUPP_SVC_NOTIFICATION          = 0x0D1A,
    SIT_AIMS_SEND_SMS                           = 0x0D1B,
    SIT_AIMS_SEND_EXPECT_MORE                   = 0x0D1C,
    SIT_AIMS_SEND_SMS_ACK                       = 0x0D1D,
    SIT_IND_AIMS_NEW_SMS                        = 0x0D1E,
    SIT_AIMS_SEND_ACK_INCOMING_SMS              = 0x0D1F,
    SIT_IND_AIMS_NEW_SMS_STATUS_REPORT          = 0x0D20,
    SIT_IND_AIMS_ON_USSD                        = 0x0D21,
    SIT_AIMS_CHG_BARRING_PWD                    = 0x0D22,
    SIT_IND_AIMS_CONFERENCE_CALL_EVENT          = 0x0D23,
    SIT_AIMS_SEND_USSD_INFO                     = 0x0D24,
    SIT_AIMS_GET_PRESENTATION_SETTINGS          = 0x0D25,
    SIT_AIMS_SET_PRESENTATION_SETTINGS          = 0x0D26,
    SIT_AIMS_SET_SELF_CAPABILITY                = 0x0D27,
    SIT_AIMS_HO_TO_WIFI_READY_REQ               = 0x0D28,
    SIT_AIMS_HO_TO_WIFI_CANCEL_IND              = 0x0D29,
    SIT_IND_AIMS_PAYLOAD_INFO_IND               = 0x0D2A,
    SIT_AIMS_HO_TO_3GPP_REQ                     = 0x0D2B,
    SIT_IND_AIMS_VOWIFI_HO_CALL_INFO            = 0x0D2C,
    SIT_IND_AIMS_NEW_CDMA_SMS                   = 0x0D2D,
    SIT_AIMS_SEND_ACK_INCOMING_CDMA_SMS         = 0x0D2E,
    SIT_IND_AIMS_RINGBACK_TONE                  = 0x0D2F,
    SIT_AIMS_MEDIA_STATE_IND                    = 0x0D30,
    SIT_IND_AIMS_CALL_MANAGE                    = 0x0D31,
    SIT_IND_AIMS_CONF_CALL_ADD_REMOVE_USER      = 0x0D32,
    SIT_IND_AIMS_ENHANCED_CONF_CALL             = 0x0D33,
    SIT_IND_AIMS_CALL_MODIFY_RSP                = 0x0D34,
    SIT_IND_AIMS_DTMF_EVENT                     = 0x0D35,
    SIT_AIMS_SET_HIDDEN_MENU_ITEM               = 0x0D36,
    SIT_AIMS_GET_HIDDEN_MENU_ITEM               = 0x0D37,
    SIT_AIMS_DEL_PDN_INFO                       = 0x0D38,
    SIT_AIMS_STACK_START_REQ                    = 0x0D39,
    SIT_AIMS_STACK_STOP_REQ                     = 0x0D3A,
    SIT_AIMS_XCAPM_START_REQ                    = 0x0D3B,
    SIT_AIMS_XCAPM_STOP_REQ                     = 0x0D3C,
    SIT_AIMS_RTT_SEND_TEXT                      = 0x0D3D,
    SIT_IND_AIMS_RTT_NEW_TEXT                   = 0x0D3E,
    SIT_IND_AIMS_RTT_FAIL_SENDING_TEXT          = 0x0D3F,
    SIT_AIMS_RCS_MULTI_FRAME                    = 0x0D40,
    SIT_IND_AIMS_RCS_MULTI_FRAME                = 0x0D41,
    SIT_AIMS_RCS_CHAT                           = 0x0D42,
    SIT_IND_AIMS_RCS_CHAT                       = 0x0D43,
    SIT_AIMS_RCS_GROUP_CHAT                     = 0x0D44,
    SIT_IND_AIMS_RCS_GROUP_CHAT                 = 0x0D45,
    SIT_AIMS_RCS_OFFLINE_MODE                   = 0x0D46,
    SIT_IND_AIMS_RCS_OFFLINE_MODE               = 0x0D47,
    SIT_AIMS_RCS_FILE_TRANSFER                  = 0x0D48,
    SIT_IND_AIMS_RCS_FILE_TRANSFER              = 0x0D49,
    SIT_AIMS_RCS_COMMON_MESSAGE                 = 0x0D5A,
    SIT_IND_AIMS_RCS_COMMON_MESSAGE             = 0x0D4B,
    SIT_AIMS_RCS_CONTENT_SHARE                  = 0x0D4C,
    SIT_IND_AIMS_RCS_CONTENT_SHARE              = 0x0D4D,
    SIT_AIMS_RCS_PRESENCE                       = 0x0D4E,
    SIT_IND_AIMS_RCS_PRESENCE                   = 0x0D4F,
    SIT_AIMS_RCS_XCAP_MANAGE                    = 0x0D50,
    SIT_IND_AIMS_RCS_XCAP_MANAGE                = 0x0D51,
    SIT_AIMS_RCS_CONFIG_MANAGE                  = 0x0D52,
    SIT_IND_AIMS_RCS_CONFIG_MANAGE              = 0x0D53,
    SIT_AIMS_RCS_TLS_MANAGE                     = 0x0D54,
    SIT_IND_AIMS_RCS_TLS_MANAGE                 = 0x0D55,
    SIT_AIMS_ENRICHED_CALLING                   = 0x0D56,
    SIT_IND_AIMS_ENRICHED_CALLING               = 0x0D57,
    SIT_AIMS_EXIT_EMERGENCY_CB_MODE             = 0x0D60,
    SIT_IND_AIMS_EXIT_EMERGENCY_CB_MODE         = 0x0D61,
    SIT_AIMS_SET_GEO_LOCATION_INFO              = 0x0D62,
    SIT_IND_AIMS_DIALOG_INFO                    = 0x0D63,
    SIT_AIMS_CDMA_SEND_SMS                      = 0x0D64,
    SIT_IND_AIMS_SIP_MSG_INFO                   = 0x0D65,
    SIT_IND_AIMS_MEDIA_STATUS                   = 0x0D70,
    SIT_AIMS_SET_PDN_EST_STATUS                 = 0x0D71,
    SIT_AIMS_SET_RTP_RX_STATISTICS              = 0x0D72,
    SIT_AIMS_IND_RTP_RX_STATISTICS              = 0x0D73,
    SIT_IND_AIMS_VOICE_RTP_QUALITY              = 0x0D74,
    SIT_IND_AIMS_FEAT_SUPP                      = 0x0D75,
    SIT_IND_AIMS_AT_CMD_FORWARDING              = 0x0D79,
    SIT_REQ_AIMS_AT_CMD_FORWARDING              = 0x0D80,
    SIT_REQ_AIMS_CALL_TRANSFER                  = 0x0D81,
    SIT_IND_AIMS_CALL_TRANSFER_RSP              = 0x0D82,
    SIT_IND_AIMS_CALL_TRANSFER                  = 0x0D85,
    SIT_AIMS_CALL_DEFLECTION_REQ                = 0x0D86,
    SIT_IND_AIMS_MWI_INFO                       = 0x0D87,
    SIT_REQ_AIMS_COMMON_IMS_SVC_INFO            = 0x0D88,
    SIT_IND_AIMS_SIP_CONFIG                     = 0x0D89,
    SIT_AIMS_SEND_UL_SIP_MSG_IND                = 0x0D8A,
    SIT_IND_AIMS_UL_SIP_MSG_RESULT              = 0x0D8B,
    SIT_IND_AIMS_SEND_DL_SIP_MSG                = 0x0D8C,
    SIT_AIMS_DL_SIP_MSG_RESULT_IND              = 0x0D8D,
    SIT_AIMS_REGISTER_IND                       = 0x0D8E,
    SIT_AIMS_COMPOSER_MMTEL                     = 0x0D8F,
    SIT_IND_AIMS_COMPOSER_MMTEL                 = 0x0D90,
    SIT_AIMS_CANCEL_COMPOSER_MMTEL              = 0x0D91,
    SIT_AIMS_SET_RTP_HEADER_EXTENSION_TYPE      = 0x0D92,
    SIT_IND_AIMS_RTP_HEADER_EXTENSION_TYPE      = 0x0D93,
    SIT_AIMS_SEND_RTP_HEADER_EXTENSION          = 0x0D94,
    SIT_IND_AIMS_RTP_HEADER_EXTENSION           = 0x0D95,
    SIT_AIMS_EMERGENCY_VOWIFI_CAPABILITY        = 0x0D96,
    SIT_IND_AIMS_CODEC_INFO                     = 0x0D97,
    SIT_REQ_AIMS_DC_SESS_UPDATE                 = 0x0D98,
    SIT_IND_AIMS_DC_SESS_UPDATE                 = 0x0D99,
    SIT_REQ_AIMS_DC_SESS_MANAGE                 = 0x0D9A,
    SIT_IND_AIMS_DC_SESSION_MANAGE              = 0x0D9B,
    SIT_IND_AIMS_DC_SESS_MODIFY                 = 0x0D9C,
    SIT_AIMS_DC_SESS_MODIFY_IND                 = 0x0D9D,


}SIT_ID_AIMS;
//AIMS support end ---------------------

typedef enum
{
    SIT_VSIM_NOTIFICATION = 0x0E00,
    SIT_IND_VSIM_OPERATION = 0x0E01,
    SIT_VSIM_OPERATION = 0x0E02,
}SIT_ID_VSIM;

typedef enum
{
    SIT_SET_WFC_MEDIA_CONFIGURATION = 0x0F00,
    SIT_IND_WFC_RTP_RTCP_TIMEOUT  = 0x0F01,
    SIT_WFC_DTMF_START   = 0x0F02,
    SIT_IND_WFC_FIRST_RTP   = 0x0F03,
    SIT_IND_WFC_RTCP_RX_SR   = 0x0F04,
    SIT_IND_WFC_RCV_DTMF_NOTI   = 0x0F05,
}SIT_ID_WFC;

typedef enum
{
    SIT_SET_EMBMS_SERVICE = 0x1000,
    SIT_SET_EMBMS_SESSION = 0x1001,
    SIT_IND_EMBMS_COVERAGE = 0x1002,
    SIT_GET_EMBMS_SESSION_LIST = 0x1003,
    SIT_IND_EMBMS_SESSION_LIST = 0x1004,
    SIT_GET_EMBMS_SIGNAL_STRENGTH = 0x1005,
    SIT_IND_EMBMS_SIGNAL_STRENGTH = 0x1006,
    SIT_GET_EMBMS_NETWORK_TIME = 0x1007,
    SIT_IND_EMBMS_NETWORK_TIME = 0x1008,
    SIT_IND_EMBMS_SAI_LIST = 0x1009,
    SIT_IND_EMBMS_GLOBAL_CELL_ID = 0x100A,
}SIT_ID_EMBMS;

typedef enum
{
    SIT_OEM_STORE_ADB_SERIAL_NUMBER_REQ = 0x4011,
    SIT_OEM_READ_ADB_SERIAL_NUMBER_REQ = 0x4012,
}SIT_ID_OEM;

typedef enum
{
    SIT_OEM_GET_SAR_STATE = 0x4100,
    SIT_OEM_SET_SAR_STATE = 0x4101,
    SIT_OEM_IND_RF_CONNECTION = 0x4102,
    SIT_OEM_SET_SVN = 0x4103,
    SIT_OEM_GET_SIM_LOCK_INFO = 0x4104,
    SIT_OEM_SET_CA_BW_FILTER = 0x4105,
    SIT_OEM_IND_CA_BW_FILTER = 0x4106,
}SIT_ID_OEM2;

typedef enum
{
    SIT_OEM_SET_PSEUDO_BS_CON = 0x4200,
    SIT_OEM_GET_PSEUDO_BS_CON = 0x4201,
    SIT_OEM_IND_PSEUDO_BS_INFO = 0x4202,
}SIT_ID_OEM3;

typedef enum
{
    SIT_OEM_GET_MODEM_INFO = 0x4300,
    SIT_OEM_SET_MODEM_INFO = 0x4301,
}SIT_ID_OEM4;

typedef enum
{
    // Improvement auto verify pin
    SIT_OEM_VERIFY_SIM_PIN_ENC = 0x4603,
    SIT_OEM_IND_SIM_PIN_ENC = 0x4604,
} SIT_ID_OEM8;

typedef enum
{
    SIT_OEM_NW_INFO = 0x4400,
    SIT_OEM_IND_NW_INFO = 0x4401,
    SIT_OEM_SET_ACTIVATE_VSIM = 0x4402,
    SIT_OEM_SET_FORBID_LTE_CELL = 0x4403,
    SIT_OEM_SET_CP_SLEEP_BLOCK = 0x4404,
    SIT_OEM_SET_FUNC_SWITCH_REQ = 0x4405,
    SIT_OEM_SET_FORBID_NR_CELL = 0x4406,
    SIT_OEM_SET_PDCP_DISCARD_TIMER = 0x4408,
    SIT_OEM_GET_CQI_INFO = 0x4409,
    SIT_OEM_SET_SAR_SETTING = 0x440A,
    SIT_OEM_SET_GMO_SWITCH = 0x440B,
    SIT_OEM_SET_TCS_FCI_REQ = 0x440C,
    SIT_OEM_GET_TCS_FCI_INFO = 0x440D,
    SIT_OEM_IND_ENDC_CAPABILITY  = 0x440E,
    SIT_OEM_GET_ACTIVITY_INFO  = 0x440F,
    SIT_OEM_IND_BASESTATION_INFO = 0x4410,
    SIT_OEM5_SET_SVN = 0x4412,
    SIT_OEM_SET_FORBIDDEN_FREQUENCY = 0x4413,
    SIT_OEM_SET_FORBIDDEN_LTE_BAND = 0x4414,
    SIT_OEM_SET_FORBIDDEN_LTE_TAC = 0x4415,
    SIT_OEM_SET_SELFLOG_TCP_DUMP_MODE = 0x4416,
    SIT_OEM_IND_DROPPED_MT_CALL_INFO = 0x4417,
    SIT_OEM_SET_BSR_PARA_REQ = 0x4418,
    SIT_OEM_SET_DRDV = 0x4419,
    SIT_OEM_SET_AHEAD_RRE = 0x441B,
    SIT_OEM_SET_ALL_4RX_DIV_SETTING_DEFAULT = 0x441C,
    SIT_OEM_GET_CDMA_CAPABILITY_INFO = 0x441D,
    SIT_OEM_SET_SRS_PWR_LIMIT = 0x441F,
    SIT_OEM_SET_UE_OPERATION_MODE = 0x4420,
    SIT_OEM_GET_UE_OPERATION_MODE = 0x4421,
    SIT_OEM_SET_TRACE_DUMP_CFG = 0x4422,
    SIT_OEM_GET_TRACE_DUMP_CFG = 0x4423,
    SIT_OEM_SET_NRRRM_MIN_REQ_ENABLE = 0x4427,
    SIT_OEM_GET_NRRRM_MIN_REQ_ENABLE = 0x4428,
    SIT_OEM_SET_ENABLE_N28  = 0x442B,
    SIT_OEM_SET_PWR_DETECT_THR_REQ = 0x442C,
    SIT_OEM_GET_BINARY_VERSION_INFO = 0x442D,
    SIT_OEM_SET_NR_DISABLE_BAND = 0x4431,
    SIT_OEM_SET_VCRT = 0x4432,
    SIT_OEM_GET_VCRT = 0x4433,
}SIT_ID_OEM5;

typedef enum
{
    RCM_E_SUCCESS = 0,

    RCM_E_RADIO_NOT_AVAILABLE,
    RCM_E_GENERIC_FAILURE,
    RCM_E_PASSWORD_INCORRECT,
    RCM_E_SIM_PIN2,
    RCM_E_SIM_PUK2,
    RCM_E_REQUEST_NOT_SUPPORTED,
    RCM_E_CANCELLED,
    RCM_E_OP_NOT_ALLOWED_DURING_VOICE_CALL,
    RCM_E_OP_NOT_ALLOWED_BEFORE_REG_TO_NW,
    RCM_E_SMS_SEND_FAIL_RETRY = 10,

    RCM_E_SIM_ABSENT,
    RCM_E_SUBSCRIPTION_NOT_AVAILABLE,
    RCM_E_MODE_NOT_SUPPORTED,
    RCM_E_FDN_CHECK_FAILURE,
    RCM_E_ILLEGAL_SIM_OR_ME,
    RCM_E_MISSING_RESOURCE,
    RCM_E_NO_SUCH_ELEMENT,
    RCM_E_SIM_MEMORY_FULL,
    RCM_E_PB_TOO_LONG_DATA,

    RCM_E_SIM_PIN_REQ = 20,
    RCM_E_SIM_PUK_REQ,
    RCM_E_UNDEFINED_CMD,
    RCM_E_OP_NOT_ALLOWED_DURING_PLMN_SEARCH,
    RCM_E_NOT_ALLOWED_DURING_PLMN_SEARCH,
    RCM_E_SIMULTANEOUS_SMS_AND_CALL_NOT_ALLOWED,
    RCM_E_ACCESS_BARRED,
    RCM_E_BLOCKED_DUE_TO_CALL,
    RCM_E_RF_HARDWARE_ISSUE,
    RCM_E_NO_RF_CALIBRATION_INFO,

    RCM_E_MODEM_ERR = 30,
    RCM_E_NOT_ALLOWED_DURING_CARRIER_CONFIG = 31,
    RCM_E_INVALID_SIM_STATE = 32,

    RCM_E_MAX = 0xFF,
}SIT_ERROR_ID;

enum {
    RCM_TYPE_REQUEST = 0x00,
    RCM_TYPE_RESPONSE = 0x01,
    RCM_TYPE_INDICATION = 0x02,
};

enum {
    SIT_RESULT_FAIL = 0x00,
    SIT_RESULT_SUCCESS = 0x01,
};

/**
 * Power
 */
typedef enum
{
    SIT_PWR_RADIO_STATE_INITIALIZED = 0x00,
    SIT_PWR_RADIO_STATE_STOP_NETWORK = 0x01,
    SIT_PWR_RADIO_STATE_START_NETWORK = 0x02,
    SIT_PWR_RADIO_STATE_POWER_OFF = 0x03,
    SIT_PWR_RADIO_STATE_RESET = 0x04,  // never sent by CP as per JSON doc

    SIT_PWR_RADIO_STATE_MAX
}sit_pwr_radio_state_e_type;

typedef enum
{
    SIT_PWR_RESET_TYPE_PHONE_ONLY = 0x01,
    SIT_PWR_RESET_TYPE_RESET_BOTH = 0x02,
    SIT_PWR_RESET_TYPE_SHUTDOWN = 0x03,   // never sent by CP as per JSON doc

    SIT_PWR_RESET_TYPE_MAX
}sit_pwr_phone_reset_type_e_type;

typedef enum
{
    SIT_PWR_RESET_CAUSE_MAX
}sit_pwr_phone_reset_cause_e_type;

typedef enum
{
    SIT_PWR_RADIO_SIM_STATE_OFF = 0x00,
    SIT_PWR_RADIO_SIM_STATE_UNAVAILABLE = 0x01,
    SIT_PWR_RADIO_SIM_STATE_SIM_NOT_READY = 0x02,
    SIT_PWR_RADIO_SIM_STATE_SIM_LOCK_OR_ABSENT = 0x03,
    SIT_PWR_RADIO_SIM_STATE_SIM_READY = 0x04,
    SIT_PWR_RADIO_SIM_STATE_RUIM_NOT_READY = 0x05,
    SIT_PWR_RADIO_SIM_STATE_RUIM_LOCK_OR_ABSENT = 0x06,
    SIT_PWR_RADIO_SIM_STATE_RUIM_READY = 0x07,
    SIT_PWR_RADIO_SIM_STATE_NV_NOT_READY = 0x08,
    SIT_PWR_RADIO_SIM_STATE_NV_READY = 0x09,
    SIT_PWR_RADIO_SIM_STATE_ON = 0x0a,

    SIT_PWR_RADIO_SIM_STATE_MAX
}sit_pwr_radio_sim_state_e_type;

typedef enum
{
    SIT_PWR_STATCK_DISABLE,
    SIT_PWR_STATCK_ENABLE
}sit_pwr_stack_mode_e_type;

/**
 * Call
 */
typedef enum
{
    SIT_CALL_STATE_ACTIVE = 0x00,
    SIT_CALL_STATE_HOLDING,
    SIT_CALL_STATE_DIALING,
    SIT_CALL_STATE_ALERTING,
    SIT_CALL_STATE_INCOMING,
    SIT_CALL_STATE_WAITING,

    SIT_CALL_STATE_MAX
} sit_call_state_e_type;

typedef enum
{
    SIT_CALL_IS_MPTY_SINGLE = 0x00,
    SIT_CALL_IS_MPTY_MULTIPARTY,

    SIT_CALL_IS_MPTY_MAX
}sit_call_is_mpty_e_type;

typedef enum
{
    SIT_CALL_IS_MT_MO = 0x00,
    SIT_CALL_IS_MT_MT,

    SIT_CALL_IS_MT_MAX
}sit_call_is_mt_e_type;

/*
   typedef enum
   {
   SIT_CALL_ALS_LINE1 = 0x00,

   SIT_CALL_ALS_MAX
   }sit_call_als_e_type;
 */

typedef enum
{
    SIT_CALL_CALL_TYPE_NULL = 0x00,
    SIT_CALL_CALL_TYPE_VOICE,
    SIT_CALL_CALL_TYPE_DATA,
    SIT_CALL_CALL_TYPE_VIDEO,
    SIT_CALL_CALL_TYPE_EMERGENCY,
    SIT_CALL_CALL_TYPE_VOLTE,

    SIT_CALL_CALL_TYPE_CDMA_VOICE = 0x0A,
    SIT_CALL_CALL_TYPE_CDMA_OTASP,
    SIT_CALL_CALL_TYPE_CDMA_EMERGENCY,
    SIT_CALL_CALL_TYPE_CDMA_MARKOV8K,
    SIT_CALL_CALL_TYPE_CDMA_MARKOV13K,
    SIT_CALL_CALL_TYPE_CDMA_LOOPBACK8K,
    SIT_CALL_CALL_TYPE_CDMA_LOOPBACK13K,

    SIT_CALL_CALL_TYPE_MAX
}sit_call_call_type_e_type;

typedef enum
{
    SIT_CALL_IS_VOICE_PRIVACY_INACTIVATED = 0x00,
    SIT_CALL_IS_VOICE_PRIVACY_ACTIVATED,

    SIT_CALL_IS_VOICE_PRIVACY_MAX
}sit_call_is_voice_privacy_e_type;

typedef enum
{
    SIT_CALL_PRESENTATION_ALLOWED = 0x00,
    SIT_CALL_PRESENTATION_RESTRICTED,
    SIT_CALL_PRESENTATION_NOT_SPECIFIED,
    SIT_CALL_PRESENTATION_PAYPHONE,

    SIT_CALL_PRESENTATION_MAX
}sit_call_presentation_e_type;

typedef enum
{
    SIT_CALL_UUS_TYPE_TYPE1_IMPLICIT = 0x00,
    SIT_CALL_UUS_TYPE_TYPE1_REQUIRED,
    SIT_CALL_UUS_TYPE_TYPE1_NOT_REQUIRED,
    SIT_CALL_UUS_TYPE_TYPE2_REQUIRED,
    SIT_CALL_UUS_TYPE_TYPE2_NOT_REQUIRED,
    SIT_CALL_UUS_TYPE_TYPE3_REQUIRED,
    SIT_CALL_UUS_TYPE_TYPE3_NOT_REQUIRED,

    SIT_CALL_UUS_TYPE_MAX
}sit_call_uus_type_e_type;

typedef enum
{
    SIT_CALL_UUS_DCS_USP = 0x00,
    SIT_CALL_UUS_DCS_OSIHLP,
    SIT_CALL_UUS_DCS_X244RMCF,
    SIT_CALL_UUS_DCS_RMCF,
    SIT_CALL_UUS_DCS_IA5C,

    SIT_CALL_UUS_DCS_MAX
}sit_call_uus_dcs_e_type;

typedef enum
{
    SIT_CALL_AUDIO_QUALITY_UNSPECIFIED  = 0x0,
    SIT_CALL_AUDIO_QUALITY_AMR          = 0x1,  /* AMR (Narrowband) audio codec */
    SIT_CALL_AUDIO_QUALITY_AMR_WB       = 0x2,  /* AMR (Wideband) audio codec */
    SIT_CALL_AUDIO_QUALITY_GSM_EFR      = 0x3,  /* GSM Enhanced Full-Rate audio codec */
    SIT_CALL_AUDIO_QUALITY_GSM_FR       = 0x4,  /* GSM Full-Rate audio codec */
    SIT_CALL_AUDIO_QUALITY_GSM_HR       = 0x5,  /* GSM Half-Rate audio codec */
    SIT_CALL_AUDIO_QUALITY_EVRC         = 0x6,  /* Enhanced Variable rate codec */
    SIT_CALL_AUDIO_QUALITY_EVRC_B       = 0x7,  /* Enhanced Variable rate codec revision B */
    SIT_CALL_AUDIO_QUALITY_EVRC_WB      = 0x8,  /* Enhanced Variable rate codec (Wideband) */
    SIT_CALL_AUDIO_QUALITY_EVRC_NW      = 0x9,  /* Enhanced Variable rate codec (Narrowband)*/
    SIT_CALL_AUDIO_QUALITY_EVS_NB       = 0xA,  /* Enhanced Voice Service Narrowband */
    SIT_CALL_AUDIO_QUALITY_EVS_WB       = 0xB,  /* Enhanced Voice Service Wideband */
    SIT_CALL_AUDIO_QUALITY_EVS_SWB      = 0xC,  /* Enhanced Voice Service Super-Wideband */
    SIT_CALL_AUDIO_QUALITY_EVS_FB       = 0xD,  /* Enhanced Voice Service Fullband */

    SIT_CALL_AUDIO_MAX
}sit_call_audio_quality_e_type;

typedef enum
{
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_DEFAULT_EMERGENCY_CENTER = 0x00,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_POLICE = 0x01,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_AMBULANCE = 0x02,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_FIRE_BRIGADE = 0x04,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_MARINE_GUARD = 0x08,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_MOUNTAIN_RESCUE = 0x10,
    SIT_CALL_EMERGENCY_CALL_SUBTYPE_NONE = 0xff,

    SIT_CALL_EMERGENCY_CALL_SUBTYPE_MAX
}sit_call_emergency_call_subtype_e_type;

typedef enum
{
    SIT_CALL_NUMBER_TYPE_UNKNOWN = 0x00,
    SIT_CALL_NUMBER_TYPE_INTERNATIONAL = 0x10,
    SIT_CALL_NUMBER_TYPE_NATIONAL = 0x20,
    SIT_CALL_NUMBER_TYPE_NETWORK_SPECIFIC = 0x30,
    SIT_CALL_NUMBER_TYPE_DEDICATED_ACCESS_SHORT_CODE = 0x40,

    SIT_CALL_NUMBER_TYPE_MAX
}sit_call_number_type_e_type;

typedef enum
{
    SIT_CALL_NUMBER_PLAN_UNKNOWN = 0x00,
    SIT_CALL_NUMBER_PLAN_ISDN = 0x01,
    SIT_CALL_NUMBER_PLAN_DATA = 0x03,
    SIT_CALL_NUMBER_PLAN_TELEX = 0x04,
    SIT_CALL_NUMBER_PLAN_NATIONAL = 0x08,
    SIT_CALL_NUMBER_PLAN_PRIVATE = 0x09,

    SIT_CALL_NUMBER_PLAN_MAX
}sit_call_number_plan_e_type;

typedef enum
{
    SIT_CALL_CLIR_DEFAULT = 0x00,
    SIT_CALL_CLIR_INVOCATION,
    SIT_CALL_CLIR_SUPPRESSION,

    SIT_CALL_CLIR_MAX
}sit_call_clir_e_type;

typedef enum
{
    SIT_CALL_CUG_CALL_DISABLED = 0X00,
    SIT_CALL_CUG_CALL_ENABLED,

    SIT_CALL_CUG_CALL_MAX
}sit_call_cug_call_e_type;

typedef enum
{
    SIT_CALL_CUG_INFO_NONE = 0x00,
    SIT_CALL_CUG_INFO_SUPPRESS_OA,
    SIT_CALL_CUG_INFO_SUPPRESS_PREFERENTIAL,
    SIT_CALL_CUG_INFO_SUPPRESS_OA_AND_PREFERENTIAL,

    SIT_CALL_CUG_INFO_MAX
}sit_call_cug_info_e_type;

typedef enum
{
    SIT_CALL_LAST_CALL_FAIL_UNOBTAINABLE_NUMBER = 0x0001,
    SIT_CALL_LAST_CALL_FAIL_NORMAL = 0x0010,
    SIT_CALL_LAST_CALL_FAIL_BUSY=  0x0011,
    SIT_CALL_LAST_CALL_FAIL_NORMAL_UNSPECIFIED = 0x001F,
    SIT_CALL_LAST_CALL_FAIL_CONGESTION = 0x0022,
    SIT_CALL_LAST_CALL_FAIL_ACM_LIMIT_EXCEEDED = 0x0044,
    SIT_CALL_LAST_CALL_FAIL_CALL_BARRED = 0x00F0,
    SIT_CALL_LAST_CALL_FAIL_FDN_BLOCKED = 0x00F1,
    SIT_CALL_LAST_CALL_FAIL_IMSI_UNKNOWN_IN_VLR = 0x00F2,
    SIT_CALL_LAST_CALL_FAIL_IMEI_NOT_ACCEPTED = 0x00F3,
    SIT_CALL_LAST_CALL_FAIL_CDMA_LOCKED_UNTIL_POWER_CYCLE = 0x03E8,
    SIT_CALL_LAST_CALL_FAIL_CDMA_DROP = 0x03E9,
    SIT_CALL_LAST_CALL_FAIL_CDMA_INTERCEPT = 0x03EA,
    SIT_CALL_LAST_CALL_FAIL_CDMA_REORDER = 0x03EB,
    SIT_CALL_LAST_CALL_FAIL_CDMA_SO_REJECT = 0x03EC,
    SIT_CALL_LAST_CALL_FAIL_CDMA_RETRY_ORDER = 0x03ED,
    SIT_CALL_LAST_CALL_FAIL_CDMA_ACCESS_FAILURE = 0x03EE,
    SIT_CALL_LAST_CALL_FAIL_CDMA_PREEMPTED = 0x03EF,
    SIT_CALL_LAST_CALL_FAIL_CDMA_NOT_EMERGENCY = 0x03F0,
    SIT_CALL_LAST_CALL_FAIL_CDMA_ACCESS_BLOCKED = 0x03F1,
    SIT_CALL_LAST_CALL_FAIL_EMC_REDIAL_ON_IMS = 0x0BB9,
    SIT_CALL_LAST_CALL_FAIL_EMC_REDIAL_ON_VOWIFI = 0x0BBA,
    SIT_CALL_LAST_CALL_FAIL_ERROR_UNSPECIFIED = 0xFFFF,

    SIT_CALL_LAST_CALL_FAIL_MAX
}sit_call_last_call_fail_cause_e_type;

typedef enum
{
    SIT_CALL_LOCAL_DTMF_OFF = 0x00,
    SIT_CALL_LOCAL_DTMF_ON,

    SIT_CALL_LOCAL_DTMF_MAX
}sit_call_dtmf_local_tone_e_type;

typedef enum
{
    SIT_CALL_DTMF_TONE_DURATION_SHORT = 0x01,
    SIT_CALL_DTMF_TONE_DURATION_LONG,

    SIT_CALL_DTMF_TONE_DURATION_MAX
}sit_call_dtmf_tone_duration_e_type;

typedef enum {
    SIT_NET_EMERGENCY_CALL_CATEGORY_POLICE       = 1, //0b00000001
    SIT_NET_EMERGENCY_CALL_CATEGORY_AMBULANCE    = 2,
    SIT_NET_EMERGENCY_CALL_CATEGORY_FIRE         = 4,
    SIT_NET_EMERGENCY_CALL_CATEGORY_MARINE       = 8,
    SIT_NET_EMERGENCY_CALL_CATEGORY_MOUNTAIN     = 16,
    SIT_NET_EMERGENCY_CALL_CATEGORY_MANUAL       = 32,
    SIT_NET_EMERGENCY_CALL_CATEGORY_AUTO         = 64,
    SIT_NET_EMERGENCY_CALL_CATEGORY_RESERVED     = 128,
}sit_call_emergency_call_category_e_type;

typedef enum {
   SIT_CALL_EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING   = 1, // 0b00000001
   SIT_CALL_EMERGENCY_NUMBER_SOURCE_SIM                 = 2, // 0b00000010
   SIT_CALL_EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG        = 4, // 0b00000100
   SIT_CALL_EMERGENCY_NUMBER_SOURCE_DEFAULT             = 8, // 0b00001000

   SIT_CALL_EMERGENCY_NUMBER_SOURCE_MAX
}sit_call_emergency_number_source_e_type;

typedef enum {
    SIT_EMERGENCY_CONDITION_ALWAYS                    = 1 << 0,
    SIT_EMERGENCY_CONDITION_NO_SIM                    = 1 << 1,
    SIT_EMERGENCY_CONDITION_TESTMODE_NORMAL           = 1 << 2,
    SIT_EMERGENCY_CONDITION_NOT_IMS_REGI              = 1 << 3,
    SIT_EMERGENCY_CONDITION_UI_ONLY                   = 1 << 4,
    SIT_EMERGENCY_CONDITION_EMC_AVAILABLE             = 1 << 5,
    SIT_EMERGENCY_CONDITION_NOT_CS_REGI               = 1 << 6,
    SIT_EMERGENCY_CONDITION_BOTH_NOT_REGI             = 1 << 7,
}sit_emergency_condition;

typedef enum {
    SIT_CALL_SRVCC_HO_STATUS_STARTED                = 0x00,
    SIT_CALL_SRVCC_HO_STATUS_COMPLETED              = 0x01,
    SIT_CALL_SRVCC_HO_STATUS_REINVITED_REQUESTED    = 0x02,
    SIT_CALL_SRVCC_HO_STATUS_DISCONNECT_REQUESTED   = 0x03,
    SIT_CALL_SRVCC_HO_STATUS_FAILED                 = 0x04,
    SIT_CALL_SRVCC_HO_STATUS_START_FAILED           = 0x05,

    SIT_CALL_SRVCC_HO_STATUS_MAX
}sit_call_srvcc_ho_status_e_type;

typedef enum
{
    SIT_OTA_TYPE_OTASP = 1,
    SIT_OTA_TYPE_OTAPA,
}sit_ota_e_type;

typedef enum
{
    SIT_OTASP_STATUS_OK_SPL_UNLOCKED = 1,
    SIT_OTASP_STATUS_OK_AKEYEX,
    SIT_OTASP_STATUS_OK_SSDUPDT,
    SIT_OTASP_STATUS_OK_NAMDWNLD,
    SIT_OTASP_STATUS_OK_MDNDWNLD,
    SIT_OTASP_STATUS_OK_IMSIDWNLD,
    SIT_OTASP_STATUS_OK_PRLDWNLD,
    SIT_OTASP_STATUS_OK_COMMIT,
    SIT_OTASP_STATUS_OK_PROGRAMMING,
    SIT_OTASP_STATUS_SUCCESSFUL,
    SIT_OTASP_STATUS_UNSUCCESSFUL,
    SIT_OTASP_STATUS_OK_OTAPAVERIFY,
    SIT_OTASP_STATUS_PROGRESS,
    SIT_OTASP_STATUS_FAILURES_EXCESS_SPC,
    SIT_OTASP_STATUS_LOCK_CODE_PASSWORD_SET,
}sit_otasp_status_e_type;

typedef enum
{
    SIT_OTAPA_STATUS_CALL_STOP_MODE = 0,
    SIT_OTAPA_STATUS_CALL_START_MODE,
}sit_otapa_status_e_type;

typedef enum
{
    SIT_SUPPORT_RAT_MODE_3GPP = 0,
    SIT_SUPPORT_RAT_MODE_3GPP2,
    SIT_SUPPORT_RAT_MODE_ALL,
}sit_emergency_support_rat_mode_e_type;

typedef enum
{
    SIT_CDMA_DISPLAY_INFO_REC = 0x0,
    SIT_CDMA_CALLED_PARTY_NUMBER_INFO_REC = 0x1,
    SIT_CDMA_CALLING_PARTY_NUMBER_INFO_REC = 0x2,
    SIT_CDMA_CONNECTED_NUMBER_INFO_REC = 0x3,
    SIT_CDMA_SIGNAL_INFO_REC = 0x4,
    SIT_CDMA_REDIRECTING_NUMBER_INFO_REC = 0x5,
    SIT_CDMA_LINE_CONTROL_INFO_REC = 0x6,
    SIT_CDMA_EXTENDED_DISPLAY_INFO_REC = 0x7,
}sit_cdma_info_rec_name_e_type;

typedef enum
{
    SIT_REDIRECTING_REASON_UNKNOWN = 0x0,
    SIT_REDIRECTING_REASON_CALL_FORWARDING_BUSY = 0x1,
    SIT_REDIRECTING_REASON_CALL_FORWARDING_NO_REPLY = 0x2,
    SIT_REDIRECTING_REASON_CALLED_DTE_OUT_OF_ORDER = 0x9,
    SIT_REDIRECTING_REASON_CALL_FORWARDING_BY_THE_CALLED_DTE = 0xA,
    SIT_REDIRECTING_REASON_CALL_FORWARDING_UNCONDITIONAL = 0xF,
    SIT_REDIRECTING_REASON_RESERVED
}sit_cdma_redirecting_reason_e_type;

typedef enum
{
    SIT_SS_USSD_USER_INITIATED = 0X00,
    SIT_SS_USSD_USER_RESPONSE,
    SIT_SS_USSD_USER_RELEASE,

    SIT_SS_USSD_MAX
}sit_ss_ussd_type_e_type;

typedef enum {
    SIT_ECC_INFO_TYPE_ENL = 0,
    SIT_ECC_INFO_TYPE_EENL = 1,  // including ENL
    SIT_ECC_INFO_TYPE_MAX
} sit_ecc_info_type;

// for aoc, refer sit_call_clir_e_type in dial
typedef enum
{
    SIT_SS_GET_CLIR_STATUS_NOT_PROVISIONED = 0,
    SIT_SS_GET_CLIR_STATUS_PROVISIONED,
    SIT_SS_GET_CLIR_STATUS_UNKNOWN,
    SIT_SS_GET_CLIR_STATUS_TEMP_RESTRICTED,
    SIT_SS_GET_CLIR_STATUS_TEMP_ALLOWED,

    SIT_SS_GET_CLIR_STATUS_MAX
}sit_ss_get_clir_status_e_type;

typedef enum
{
    SIT_SS_GET_CLIP_STATUS_NOT_PROVISIONED = 0,
    SIT_SS_GET_CLIP_STATUS_PROVISIONED,
    SIT_SS_GET_CLIP_STATUS_UNKNOWN,

    SIT_SS_GET_CLIP_STATUS_MAX
}sit_ss_get_clip_status_e_type;

typedef enum
{
    SIT_SS_USSD_IND_STATUS_USSD_NOTIFY = 0,
    SIT_SS_USSD_IND_STATUS_USSD_REQUEST,
    SIT_SS_USSD_IND_STATUS_SESSION_TERMINATED_BY_NETWORK,
    SIT_SS_USSD_IND_STATUS_OTHER_LOCAL_CLIENT_HAS_RESPONDED,
    SIT_SS_USSD_IND_STATUS_OPERATION_NOT_SUPPORTED,
    SIT_SS_USSD_IND_STATUS_NETWORK_TIMEOUT,

    SIT_SS_USSD_IND_STATUS_MAX
}sit_ss_ussd_ind_status_e_type;

typedef enum
{
    SIT_SS_SSNOTI_TYPE_MO,
    SIT_SS_SSNOTI_TYPE_MT
}sit_ss_ssnoti_type_e_type;

typedef enum
{
    SIT_SS_CODE1_UNCOND_CF_ACTIVE = 0,        /* unconditional call forwarding is active */
    SIT_SS_CODE1_SOME_COND_CF_ACTIVE = 1,    /* some of the conditional call forwardings are active */
    SIT_SS_CODE1_CALL_FORWARDED = 2,        /* call has been forwarded */
    SIT_SS_CODE1_CALL_WAITING = 3,            /* call is waiting */
    SIT_SS_CODE1_CUG_CALL = 4,                /* this is a CUG call (also <index> present) */
    SIT_SS_CODE1_OUTGOING_BARRED = 5,        /* outgoing calls are barred */
    SIT_SS_CODE1_INCOMING_BARRED = 6,        /* incoming calls are barred */
    SIT_SS_CODE1_CLIR_SUPP_REJECTED = 7,        /* CLIR suppression rejected */
    SIT_SS_CODE1_CALL_DEFLECTED = 8            /* call has been deflected */
}sit_ss_code1_e_type;

typedef enum
{
    SIT_SS_CODE2_FORWARDED_CALL = 0,        /* this is a forwarded call (MT call setup) */
    SIT_SS_CODE2_CUG_CALL = 1,                /* this is a CUG call (also <index> present) (MT call setup) */
    SIT_SS_CODE2_HOLD = 2,                    /* call has been put on hold (during a voice call) */
    SIT_SS_CODE2_RETRIEVED = 3,                /* call has been retrieved (during a voice call) */
    SIT_SS_CODE2_MPTY_ENTERED = 4,            /* multiparty call entered (during a voice call) */
    SIT_SS_CODE2_HOLD_CALL_RELEASED = 5,    /* call on hold has been released (this is not a SS notification) (during a voice call) */
    SIT_SS_CODE2_FORWARD_CHECK_RECEIVED = 6,    /* forward check SS message received (can be received whenever) */
    SIT_SS_CODE2_EXPLICIT_CF_INCOMING = 7,    /* call is being connected (alerting) with the remote party in alerting state in explicit call transfer operation
                                                 (during a voice call) */
    SIT_SS_CODE2_EXPLICIT_CF_CONNECTED = 8,    /* call has been connected with the other remote party in explicit call transfer operation (also number and
                                                  subaddress parameters may be present) (during a voice call or MT call setup) */
    SIT_SS_CODE2_DEFLECTED_CALL = 9,            /* this is a deflected call (MT call setup) */
    SIT_SS_CODE2_ADD_INCOMING_CALL_FORWARDED = 10    /* additional incoming call forwarded */
}sit_ss_code2_e_type;

typedef enum
{
    SIT_SS_CALL_FARWARD_STATUS_DISABLE = 0,
    SIT_SS_CALL_FARWARD_STATUS_NOT_ACTIVE = 0,    /* GET : not active */
    SIT_SS_CALL_FARWARD_STATUS_ENABLE = 1,
    SIT_SS_CALL_FARWARD_STATUS_ACTIVE = 1,        /* GET : active */
    SIT_SS_CALL_FARWARD_STATUS_INTERROGATE,
    SIT_SS_CALL_FARWARD_STATUS_REGISTRATION,
    SIT_SS_CALL_FARWARD_STATUS_ERASURE,

    SIT_SS_CALL_FARWARD_STATUS_MAX
}sit_ss_call_forward_status_e_type;

typedef enum
{
    SIT_SS_CALL_FORWARD_READON_UNCONDITIONAL = 0,
    SIT_SS_CALL_FORWARD_READON_MOBILE_BUSY,
    SIT_SS_CALL_FORWARD_READON_NO_REPLY,
    SIT_SS_CALL_FORWARD_READON_NOT_REACHABLE,
    SIT_SS_CALL_FORWARD_READON_ALL,
    SIT_SS_CALL_FORWARD_READON_ALL_CONDITIONAL,

    SIT_SS_CALL_FORWARD_READON_MAX
}sit_ss_call_forward_reason_e_type;

typedef enum
{
    SIT_SS_SERVICE_CLASS_VOICE = 1,
    SIT_SS_SERVICE_CLASS_DATA = 2,
    SIT_SS_SERVICE_CLASS_FAX = 4,
    SIT_SS_SERVICE_CLASS_SMS = 8,
    SIT_SS_SERVICE_CLASS_DATA_CIRCUIT_SYNC = 16,
    SIT_SS_SERVICE_CLASS_DATA_CIRCUIT_ASYNC = 32,
    SIT_SS_SERVICE_CLASS_DEDICATED_PACKET_ACCESS = 64,
    SIT_SS_SERVICE_CLASS_DEDICATED_PAD_ACCESS = 128,

    SIT_SS_SERVICE_CLASS_MAX
}sit_ss_service_class_e_type;

typedef enum
{
    SIT_SS_TOA_UNKNOWN = 0x00,
    SIT_SS_TOA_INTERNATIONAL = 0x10,
    SIT_SS_TOA_NATIONAL = 0x20,
    SIT_SS_TOA_NETWORK_SPECIFIC = 0x30,
    SIT_SS_TOA_DEDICATED_SHORT_ACCESS_CODE = 0x40,

    SIT_SS_TOA_MAX
}sit_ss_toa_e_type;

/**
 *  SIM definitions
 */
typedef enum
{
    SIT_SIM_FAC_CS = 0,
    SIT_SIM_FAC_PS,
    SIT_SIM_FAC_PF,
    SIT_SIM_FAC_SC,
    SIT_SIM_FAC_AO,
    SIT_SIM_FAC_OI,
    SIT_SIM_FAC_OX,
    SIT_SIM_FAC_AI,
    SIT_SIM_FAC_IR,
    SIT_SIM_FAC_NT,
    SIT_SIM_FAC_NM, /*10*/
    SIT_SIM_FAC_NS,
    SIT_SIM_FAC_NA,
    SIT_SIM_FAC_AB,
    SIT_SIM_FAC_AG,
    SIT_SIM_FAC_AC,
    SIT_SIM_FAC_FD,
    SIT_SIM_FAC_PN,
    SIT_SIM_FAC_PU,
    SIT_SIM_FAC_PP,
    SIT_SIM_FAC_PC, /*20*/
    SIT_SIM_FAC_SC2,

    SIT_SIM_FAC_MAX
}sit_sim_fac_lock_type_e_type;

typedef enum
{
    SIT_SIM_SIM_IO_COMMAND_READ_BINARY = 0xB0,
    SIT_SIM_SIM_IO_COMMAND_READ_RECORD = 0xB2,
    SIT_SIM_SIM_IO_COMMAND_GET_RESPONSE = 0xC0,
    SIT_SIM_SIM_IO_COMMAND_UPDATE_BINARY = 0xD6,
    SIT_SIM_SIM_IO_COMMAND_UPDATE_RECORD = 0xDC,
    SIT_SIM_SIM_IO_COMMAND_STATUS = 0xF2,

    SIT_SIM_SIM_IO_COMMAND_MAX
}sit_sim_sim_io_command_e_type;

typedef enum
{
    SIT_SIM_FAC_LOCK_MODE_UNLOCK = 0x00,
    SIT_SIM_FAC_LOCK_MODE_LOCK,

    SIT_SIM_FAC_LOCK_MODE_MAX
}sit_sim_facility_lock_mode_e_type;

typedef enum
{
    SIT_SIM_CARD_STATE_ABSENT = 0x00,
    SIT_SIM_CARD_STATE_PRESENT,
    SIT_SIM_CARD_STATE_ERROR,
    SIT_SIM_CARD_STATE_DETECTED,
    SIT_SIM_CARD_STATE_RESTRICTED,
    SIT_SIM_CARD_STATE_MAX
}sit_sim_card_state_e_type;

typedef enum
{
    SIT_SIM_PIN_STATE_UNKNOWN = 0x00,
    SIT_SIM_PIN_STATE_ENABLED_NOT_VERIFIED,
    SIT_SIM_PIN_STATE_ENABLED_VERIFIED,
    SIT_SIM_PIN_STATE_DISABLED,
    SIT_SIM_PIN_STATE_ENABLED_BLOCKED,
    SIT_SIM_PIN_STATE_ENABLED_PERM_BLOCKED,

    SIT_SIM_PIN_STATE_MAX
}sit_sim_pin_state_e_type;

typedef enum
{
    SIT_SIM_APPS_TYPE_UNKNOWN = 0x00,
    SIT_SIM_APPS_TYPE_SIM,
    SIT_SIM_APPS_TYPE_USIM,
    SIT_SIM_APPS_TYPE_RUIM,
    SIT_SIM_APPS_TYPE_CSIM,
    SIT_SIM_APPS_TYPE_ISIM,

    SIT_SIM_APPS_TYPE_MAX
}sit_sim_apps_type_e_type;

typedef enum
{
    SIT_SIM_APPS_STATE_UNKNOWN = 0x00,
    SIT_SIM_APPS_STATE_DETECTED,
    SIT_SIM_APPS_STATE_PIN_REQUIRED,
    SIT_SIM_APPS_STATE_PUK_REQUIRED,
    SIT_SIM_APPS_STATE_SUBSCRIPTION_PERSO,
    SIT_SIM_APPS_STATE_READY,

    SIT_SIM_APPS_STATE_MAX
}sit_sim_apps_state_e_type;

typedef enum
{
    SIT_SIM_PERSO_SUBSTATE_UNKNOWN = 0x00,
    SIT_SIM_PERSO_SUBSTATE_IN_PROGRESS,
    SIT_SIM_PERSO_SUBSTATE_READY,
    SIT_SIM_PERSO_SUBSTATE_SIM_NETWORK,
    SIT_SIM_PERSO_SUBSTATE_SIM_NETWORK_SUBSET,
    SIT_SIM_PERSO_SUBSTATE_SIM_CORPORATE,
    SIT_SIM_PERSO_SUBSTATE_SIM_SERVICE_PROVIDER,
    SIT_SIM_PERSO_SUBSTATE_SIM_SIM,
    SIT_SIM_PERSO_SUBSTATE_SIM_NETWORK_PUK,
    SIT_SIM_PERSO_SUBSTATE_SIM_NETWORK_SUBSET_PUK,
    SIT_SIM_PERSO_SUBSTATE_SIM_CORPORATE_PUK,
    SIT_SIM_PERSO_SUBSTATE_SIM_SERVICE_PROVIDER_PUK,
    SIT_SIM_PERSO_SUBSTATE_SIM_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_NETWORK1,
    SIT_SIM_PERSO_SUBSTATE_RUIM_NETWORK2,
    SIT_SIM_PERSO_SUBSTATE_RUIM_HRPD,
    SIT_SIM_PERSO_SUBSTATE_RUIM_CORPORATE,
    SIT_SIM_PERSO_SUBSTATE_RUIM_SERVICE_PROVIDER,
    SIT_SIM_PERSO_SUBSTATE_RUIM_RUIM,
    SIT_SIM_PERSO_SUBSTATE_RUIM_NETWORK1_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_NETWORK2_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_HRPD_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_CORPORATE_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_SERVICE_PROVIDER_PUK,
    SIT_SIM_PERSO_SUBSTATE_RUIM_RUIM_PUK,

    SIT_SIM_PERSO_SUBSTATE_MAX
}sit_sim_perso_substate_e_type;

typedef enum
{
    SIT_ISIM_AUTH_USIM = 0x00,
    SIT_ISIM_AUTH_ISIM
}sit_sim_get_sim_gba_auth_type;

typedef enum
{
    SIT_SIM_AUTH_IMS = 0x00,
    SIT_SIM_AUTH_GSM,
    SIT_SIM_AUTH_3G
}sit_sim_get_sim_auth_type;

/**
 * Network related definition
 */
enum {
    SIT_NET_ACCESS_RADIO_TYPE_UNKNOWN_ALLRAN = 0,
    SIT_NET_ACCESS_RADIO_TYPE_GERAN = 1,
    SIT_NET_ACCESS_RADIO_TYPE_UTRAN = 2,
    SIT_NET_ACCESS_RADIO_TYPE_EUTRAN = 3,
    SIT_NET_ACCESS_RADIO_TYPE_NGRAN = 4,
    SIT_NET_ACCESS_RADIO_TYPE_CDMA2000 = 5,
}sit_net_ran_e_type;

typedef enum
{
    SIT_NET_DISABLE = 0,
    SIT_NET_ENABLE = 1,
}sit_net_enable_e_type;

typedef enum {
    SERVICE_NOT_AVAILABLE = 0x00,
    SERVICE_AVAILABLE = 0x01,
} sit_net_service_state_e_type;

typedef enum
{
    SIT_RAT_TYPE_UNKNOWN = 0x00,
    SIT_RAT_TYPE_GPRS, // 0x01 (01)
    SIT_RAT_TYPE_EDGE,
    SIT_RAT_TYPE_UMTS,
    SIT_RAT_TYPE_IS95A,
    SIT_RAT_TYPE_IS95B, // 0x05 (05)
    SIT_RAT_TYPE_1xRTT,
    SIT_RAT_TYPE_EVDO_0,
    SIT_RAT_TYPE_EVDO_A,
    SIT_RAT_TYPE_HSDPA,
    SIT_RAT_TYPE_HSUPA, // 0x0A (10)
    SIT_RAT_TYPE_HSPA,
    SIT_RAT_TYPE_EVDO_B,
    SIT_RAT_TYPE_EHRPD,
    SIT_RAT_TYPE_LTE,
    SIT_RAT_TYPE_HSPAP,
    SIT_RAT_TYPE_GSM,           // 0x10 (16)
    SIT_RAT_TYPE_IWLAN,         // 0x11 (17)
    SIT_RAT_TYPE_TD_SCDMA,      // 0x12 (18)
    SIT_RAT_TYPE_HSPADCPLUS,    // 0x13 (19)

    SIT_RAT_TYPE_LTE_CA,        // 0x14 (20)
    SIT_RAT_TYPE_5G,            // 0x15 (21)
    SIT_RAT_TYPE_MAX,
    SIT_RAT_TYPE_UNSPECIFIED = 0xFF,
}sit_rat_type_e_type;

enum {
    RAF_CP_UNKNOWN = (1 << 0),
    RAF_CP_GPRS = (1 << 1),
    RAF_CP_EDGE = (1 << 2),
    RAF_CP_UMTS = (1 << 3),
    RAF_CP_HSDPA = (1 << 4),
    RAF_CP_HSUPA = (1 << 5),
    RAF_CP_HSPA = (1 << 6),
    RAF_CP_LTE = (1 << 7),
    RAF_CP_HSPAP = (1 << 8),
    RAF_CP_GSM = (1 << 9),
    RAF_CP_TD_SCDMA = (1 << 10),
    RAF_CP_IS95A = (1 << 11),
    RAF_CP_IS95B = (1 << 12),
    RAF_CP_1xRTT = (1 << 13),
    RAF_CP_EVDO_0 = (1 << 14),
    RAF_CP_EVDO_A = (1 << 15),
    RAF_CP_EVDO_B = (1 << 16),
    RAF_CP_EHRPD = (1 << 17),
    RAF_CP_5G = (1 << 18)
};

typedef enum
{
    SIT_NET_DS_NET_TYPE_GSM_WCDMA               = 0x00,
    SIT_NET_DS_NET_TYPE_LTE_GSM_WCDMA           = 0x01,
    SIT_NET_DS_NET_TYPE_GSM                     = 0x02,
    SIT_NET_DS_NET_TYPE_CDMA_EVDO_AUTO          = 0x03,
    SIT_NET_DS_NET_TYPE_LTE_CDMA_EVDO           = 0x04,
    SIT_NET_DS_NET_TYPE_LTE_CDMA_EVDO_GSM_WCDMA = 0x05,
    SIT_NET_DS_NET_TYPE_CDMA                    = 0x06,
    SIT_NET_DS_NET_TYPE_MAX
}sit_net_pref_ds_type_e_type;

typedef enum
{
    SIT_NET_REG_STATE_NOT_REG_NO_SEARCH = 0x00,
    SIT_NET_REG_STATE_REGISTERED,
    SIT_NET_REG_STATE_NOT_REG_SEARCHING,
    SIT_NET_REG_STATE_DENIED,
    SIT_NET_REG_STATE_UNKNOWN,
    SIT_NET_REG_STATE_ROAMING,

    SIT_NET_REG_FOR_SMS_ONLY_HN,
    SIT_NET_REG_FOR_SMS_ONLY_RM,
    SIT_NET_REG_ATTCH_FOR_EMG_SVC_ONLY,
    SIT_NET_REG_FOR_CSFB_NOT_PREFER_HN,

    SIT_NET_REG_STATE_NOT_REG_NO_SEARCH_EMGCALL = 0x0A,
    SIT_NET_REG_STATE_NOT_REG_SEARCHING_EMGCALL = 0x0C,
    SIT_NET_REG_STATE_DENIED_EMGCALL = 0x0D,
    SIT_NET_REG_STATE_UNKNOWN_EMGCALL = 0x0E,

    //------------------------------------------
    SIT_NET_REG_STATE_DENIED_ROAMING = 50,

    SIT_NET_REG_STATE_MAX
}sit_net_reg_state_e_type;

typedef enum
{
    SIT_NET_REJ_CAUSE_GENERAL = 0,
    SIT_NET_REJ_CAUSE_AUTH_FAIL,
    SIT_NET_REJ_CAUSE_IMSI_UNKNOWN_IN_HLR,
    SIT_NET_REJ_CAUSE_ILLEGAL_MS,
    SIT_NET_REJ_CAUSE_ILLEGAL_ME,
    SIT_NET_REJ_CAUSE_PLMN_NOT_ALLOWED,
    SIT_NET_REJ_CAUSE_LOCATION_AREA_NOT_ALLOWED,
    SIT_NET_REJ_CAUSE_ROAMING_NOT_ALLOWED,
    SIT_NET_REJ_CAUSE_NO_SUITABLE_CELLS_IN_THIS_LOCATION_AREA,
    SIT_NET_REJ_CAUSE_NETWORK_FAIL,

    ///TODO:
    /*
    SIT_NET_REJ_CAUSE_PLMN_NOT_ALLOWED,
    ... will be added after duplicated value is revised
    */

}sit_net_rej_cause_e_type;

typedef enum
{
    SIT_NET_NETWORK_MODE_AUTOMATIC = 0x00,
    SIT_NET_NETWORK_MODE_MANUAL,

    SIT_NET_NETWORK_MODE_MAX
}sit_net_network_mode_e_type;

typedef enum {
    SIT_NET_CELL_INFO_TYPE_GSM = 0x00,
    SIT_NET_CELL_INFO_TYPE_CDMA = 0x01,
    SIT_NET_CELL_INFO_TYPE_LTE = 0x02,
    SIT_NET_CELL_INFO_TYPE_WCDMA = 0x03,
    SIT_NET_CELL_INFO_TYPE_TDSCDMA = 0x04,
    SIT_NET_CELL_INFO_TYPE_NR = 0x05,
}sit_net_cell_info_type_e_type;

typedef enum {
    SIT_NET_UNREGISTERED = 0x00,
    SIT_NET_REGISTERED = 0x01,
}sit_net_reg_status_e_type;

// Emergency Call Status
enum {
    SIT_NET_EMERGENCY_CALL_START        = 0x01,
    SIT_NET_EMERGENCY_CALL_END          = 0x02,
    SIT_NET_EMERGENCY_CALL_CANCELED     = 0x03,
    SIT_NET_EMERGENCY_CALL_FAIL         = 0x04,
};

enum {
    SIT_NET_NO_MORE_ACT_EMERGENCY_CALL  = 0x00,
    SIT_NET_CURRENT_ACT_EMERGENCY_CALL  = 0x01,
    SIT_NET_RETRY_ACT_EMERGENCY_CALL    = 0x02,
};

typedef enum
{
    SIT_NET_PREFERRED_PLMN_MODE_INVALID = 0x00,
    SIT_NET_PREFERRED_PLMN_MODE_ADD = 0x01,
    SIT_NET_PREFERRED_PLMN_MODE_EDIT = 0x02,
    SIT_NET_PREFERRED_PLMN_MODE_DELETE = 0x03,
}sit_net_preferred_plmn_mode_e_type;

typedef enum
{
    SIT_NET_PREFERRED_PLMN_ACT_UNKNOWN = 0x00,
    SIT_NET_PREFERRED_PLMN_ACT_GSM = 0x01,
    SIT_NET_PREFERRED_PLMN_ACT_GSM_COMPACT = 0x02,
    SIT_NET_PREFERRED_PLMN_ACT_UTRAN = 0x03,
    SIT_NET_PREFERRED_PLMN_ACT_EUTRAN = 0x04,
    SIT_NET_PREFERRED_PLMN_ACT_MAX,
}sit_net_preferred_plmn_act_e_type;

typedef enum
{
    SIT_NET_PREF_NET_TYPE_GSM_WCDMA = 0x00,
    SIT_NET_PREF_NET_TYPE_GSM_ONLY,
    SIT_NET_PREF_NET_TYPE_WCDMA,
    SIT_NET_PREF_NET_TYPE_GSM_WCDMA_AUTO,
    SIT_NET_PREF_NET_TYPE_CDMA_EVDO_AUTO,
    SIT_NET_PREF_NET_TYPE_CDMA_ONLY,
    SIT_NET_PREF_NET_TYPE_EVDO_ONLY,
    SIT_NET_PREF_NET_TYPE_GSM_WCDMA_CDMA_EVDO_AUTO,
    SIT_NET_PREF_NET_TYPE_LTE_CDMA_EVDO,
    SIT_NET_PREF_NET_TYPE_LTE_GSM_WCDMA,
    SIT_NET_PREF_NET_TYPE_LTE_CDMA_EVDO_GSM_WCDMA,
    SIT_NET_PREF_NET_TYPE_LTE_ONLY,
    SIT_NET_PREF_NET_TYPE_LTE_WCDMA,    // 0x0C

    SIT_NET_PREF_NET_TYPE_NR_ONLY,      // 0x0D
    SIT_NET_PREF_NET_TYPE_NR_LTE,
    SIT_NET_PREF_NET_TYPE_NR_LTE_CDMA_EVDO,
    SIT_NET_PREF_NET_TYPE_NR_LTE_GSM_WCDMA,  // 0x10
    SIT_NET_PREF_NET_TYPE_NR_LTE_CDMA_EVDO_GSM_WCDMA,
    SIT_NET_PREF_NET_TYPE_NR_LTE_WCDMA,

    SIT_NET_PREF_NET_TYPE_NR_LTE_GSM, // 0x13
    SIT_NET_PREF_NET_TYPE_NR_WCDMA,
    SIT_NET_PREF_NET_TYPE_NR_GSM_WCDMA,
    SIT_NET_PREF_NET_TYPE_NR_GSM,

    SIT_NET_PREF_NET_TYPE_TDSCDMA_ONLY,                       /* TD-SCDMA only */
    SIT_NET_PREF_NET_TYPE_TDSCDMA_WCDMA,                      /* TD-SCDMA and WCDMA */
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA,                        /* TD-SCDMA and LTE */
    SIT_NET_PREF_NET_TYPE_TDSCDMA_GSM,                        /* TD-SCDMA and GSM */
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA_GSM,                    /* TD-SCDMA,GSM and LTE */
    SIT_NET_PREF_NET_TYPE_TDSCDMA_GSM_WCDMA,                  /* TD-SCDMA, GSM/WCDMA */
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA_WCDMA,                  /* TD-SCDMA, WCDMA and LTE */
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA_GSM_WCDMA,              /* TD-SCDMA, GSM/WCDMA and LTE */
    SIT_NET_PREF_NET_TYPE_TDSCDMA_CDMA_EVDO_GSM_WCDMA,        /* TD-SCDMA,EvDo,CDMA,GSM/WCDMA*/
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA_CDMA_EVDO_GSM_WCDMA,    /* TD-SCDMA/LTE/GSM/WCDMA, CDMA, and EvDo */

    SIT_NET_PREF_NET_TYPE_NR_LTE_TDSCDMA, // 0x21
    SIT_NET_PREF_NET_TYPE_NR_LTE_TDSCDMA_GSM,
    SIT_NET_PREF_NET_TYPE_NR_LTE_TDSCDMA_WCDMA,
    SIT_NET_PREF_NET_TYPE_NR_LTE_TDSCDMA_GSM_WCDMA,
    SIT_NET_PREF_NET_TYPE_NR_LTE_TDSCDMA_CDMA_EVDO_GSM_WCDMA,

    SIT_NET_PREF_NET_TYPE_TDSCDMA_CDMA = 50,
    SIT_NET_PREF_NET_TYPE_TDSCDMA_CDMA_NO_EVDO,
    SIT_NET_PREF_NET_TYPE_LTE_TDSCDMA_CDMA_EVDO,
    SIT_NET_PREF_NET_TYPE_TDSCDMA_EVDO_NO_CDMA,

    SIT_NET_PREF_NET_TYPE_MAX
}sit_net_pref_network_type_e_type;

typedef enum {
    CARRIER_MATCH_ALL,
    CARRIER_MATCH_SPN,
    CARRIER_MATCH_IMSI_PREFIX,
    CARRIER_MATCH_GID1,
    CARRIER_MATCH_GID2
}sit_carrier_match_type_e_type;

typedef enum {
    SIT_NO_MULTISIM_POLICY = 0,
    SIT_ONE_VALID_SIM_MUST_BE_PRESENT = 1,
}sit_multi_sim_lock_policy_e_type;

enum {
    SIT_FREQUENCY_RANGE_NONE = 0,
    SIT_FREQUENCY_RANGE_LOW = 1,
    SIT_FREQUENCY_RANGE_MID = 2,
    SIT_FREQUENCY_RANGE_HIGH = 3,
    SIT_FREQUENCY_RANGE_MMWAVE = 4,
};

typedef enum
{
    SERVICE_DOMAIN_UNKNOWN = 0x00,
    SERVICE_DOMAIN_CSPS = 0x01,
    SERVICE_DOMAIN_CS = 0x02,
    SERVICE_DOMAIN_PS = 0x03,
}sit_service_domain_type;

typedef enum
{
    REG_REJ_CAUSE_UNUSED = 0xFF,
}sit_reg_rej_cause;

typedef enum
{
    SIT_NET_PLMN_STATUS_UNKONWN = 0x00,
    SIT_NET_PLMN_STATUS_AVAILABLE = 0x01,
    SIT_NET_PLMN_STATUS_CURRENT = 0x02,
    SIT_NET_PLMN_STATUS_FORBIDDEN = 0x03,
    SIT_NET_PLMN_STATUS_MAX
}sit_net_plmn_status_e_type;

typedef enum
{
    SIT_ENDC_NOT_RELEASE = 0,
    SIT_ENDC_RELEASE = 1,
}sit_endc_release_e_type;

typedef enum
{
    SIT_NR_MODE_NO_NR = 0,
    SIT_NR_MODE_NSA = 1,
    SIT_NR_MODE_SA = 2,
    SIT_NR_MODE_NSA_SA = 3,
    SIT_NR_MODE_DEFAULT = 4,
}sit_nr_mode_e_type;

enum {
    SIT_SCG_NONE = 0,
    SIT_SCG_ADDED = 1,
};

enum {
    SIT_AC_BARRING_TYPE_NONE = 0,
    SIT_AC_BARRING_TYPE_MO_SIG = 1,
    SIT_AC_BARRING_TYPE_MO_DATA = 2,
    SIT_AC_BARRING_TYPE_MMTEL_VOICE = 3,
    SIT_AC_BARRING_TYPE_MMTEL_VIDEO = 4,
};

typedef enum
{
    SIT_NET_DUPLEX_MODE_FDD = 0x01,
    SIT_NET_DUPLEX_MODE_TDD = 0x02,
    SIT_NET_DUPLEX_MODE_FDD_TDD = 0x03,
    SIT_NET_DUPLEX_MODE_MAX
}sit_net_duplex_mode_e_type;

typedef enum
{
    SIT_MC_SRCH_MODE_MANUAL = 0,
    SIT_MC_SRCH_MODE_AUTO = 1,
    SIT_MC_SRCH_MODE_CANCEL = 2,
}sit_net_mc_srch_mode_type;

typedef enum
{
    SIT_MC_SRCH_RESUT_SUCCESS = 0,
    SIT_MC_SRCH_RESUT_NW_NOT_SUPPORT = 1,
    SIT_MC_SRCH_RESUT_MODE_NOT_AVAILABLE = 2,
    SIT_MC_SRCH_RESUT_NO_CELL_LIST = 3,
}sit_net_mc_srch_result_type;

typedef enum
{
    SIT_CDMA_RM_HOME = 0,
    SIT_CDMA_RM_AFFILIATED,
    SIT_CDMA_RM_ANY,
}sit_net_cdma_roaming_type;

// scan type
enum {
    SIT_SCAN_TYPE_ONESHOT = 0,
    SIT_SCAN_TYPE_PERIODIC = 1,
    SIT_SCAN_TYPE_STOP = 2,
};

enum {
    SIT_SCAN_NO_INCREMENTAL_RESULT = 0,
    SIT_SCAN_INCREMENTAL_RESULT = 1,
};

typedef enum
{
    SIT_NET_SCAN_STATUS_PARTIAL = 0x01,
    SIT_NET_SCAN_STATUS_COMPLETE = 0x02,
    SIT_NET_SCAN_STATUS_ABORT = 0x03,    // no use case in json doc
}sit_net_scan_type;

typedef enum
{
    SIT_NET_BAND_UNSPECIFIED = 0x00,
    SIT_NET_BAND_EURO,
    SIT_NET_BAND_US,
    SIT_NET_BAND_JPN,
    SIT_NET_BAND_AUS,
    SIT_NET_BAND_AUS2,
    SIT_NET_BAND_CELLULAR,
    SIT_NET_BAND_PCS,
    SIT_NET_BAND_CLASS3,
    SIT_NET_BAND_CLASS4,
    SIT_NET_BAND_CLASS5,
    SIT_NET_BAND_CLASS6,
    SIT_NET_BAND_CLASS7,
    SIT_NET_BAND_CLASS8,
    SIT_NET_BAND_CLASS9,
    SIT_NET_BAND_CLASS10,
    SIT_NET_BAND_CLASS11,
    SIT_NET_BAND_CLASS15,
    SIT_NET_BAND_CLASS16,

    SIT_NET_BAND_MAX
}sit_net_band_e_type;

// GERAN bands
enum {
    SIT_GERAN_BAND_UNKNOWN = 0,
    SIT_GERAN_BAND_T380 = 1,
    SIT_GERAN_BAND_T410 = 2,
    SIT_GERAN_BAND_450 = 3,
    SIT_GERAN_BAND_480 = 4,
    SIT_GERAN_BAND_710 = 5,
    SIT_GERAN_BAND_750 = 6,
    SIT_GERAN_BAND_T810 = 7,
    SIT_GERAN_BAND_850 = 8,
    SIT_GERAN_BAND_P900 = 9,
    SIT_GERAN_BAND_E900 = 10,
    SIT_GERAN_BAND_R900 = 11,
    SIT_GERAN_BAND_DCS1800 = 12,
    SIT_GERAN_BAND_PCS1900 = 13,
    SIT_GERAN_BAND_ER900 = 14,
    STI_GERAN_BAND_MAX,
};

// UTRAN bands
enum {
    SIT_UTRAN_BAND_UNKNOWN = 0,
    SIT_UTRAN_BAND_1 = 1,
    SIT_UTRAN_BAND_26 = 26,
    SIT_UTRAN_BAND_MAX,
};

// EUTRAN bands
enum {
    SIT_EUTRAN_BAND_UNKNOWN = 0,
    SIT_EUTRAN_BAND_1 = 1,
    SIT_EUTRAN_BAND_70 = 70,
    SIT_EUTRAN_BAND_MAX,
};

enum {
    /** 3GPP TS 38.101-1, Table 5.2-1: FR1 bands */
    SIT_NGRAN_BAND_1 = 1,
    SIT_NGRAN_BAND_90 = 90,
    /** 3GPP TS 38.101-2, Table 5.2-1: FR2 bands */
    SIT_NGRAN_BAND_257 = 257,
    SIT_NGRAN_BAND_258 = 258,
    SIT_NGRAN_BAND_260 = 260,
    SIT_NGRAN_BAND_261 = 261,
    SIT_NGRAN_BAND_MAX,
};

typedef enum
{
    SIT_RF_DESENSE_OP_STOP = 0x00,
    SIT_RF_DESENSE_OP_START = 0x01,
    SIT_RF_DESENSE_OP_PAUSE = 0x02,
}sit_rf_desense_opmode_e_type;

typedef enum
{
    SIT_RF_DESENSE_RAT_GSM = 0x00,
    SIT_RF_DESENSE_RAT_WCDMA = 0x01,
    SIT_RF_DESENSE_RAT_LTE = 0x02,
    SIT_RF_DESENSE_RAT_CDMA = 0x03,
}sit_rf_desense_rat_e_type;

typedef enum
{
    SIT_FREQ_LOCK_RAT_UNKNOWN = 0x00,
    SIT_FREQ_LOCK_RAT_GSM     = 0x01,
    SIT_FREQ_LOCK_RAT_WCDMA   = 0x02,
    SIT_FREQ_LOCK_RAT_LTE     = 0x03,
}sit_freq_lock_rat_e_type;

typedef enum
{
    RRC_IDLE = 0,
    RRC_CONNECT = 1,
}sit_net_rrc_info_state;

/**
 *  VSIM definitions
 */
typedef enum
{
    SIT_VSIM_NOTI_EN_EXTERNAL_SIM = 0x00,
    SIT_VSIM_NOTI_DIS_EXTERNAL_SIM = 0x01,
    SIT_VSIM_NOTI_PLUG_OUT = 0x02,
    SIT_VSIM_NOTI_PLUG_IN = 0x03,
}sit_vsim_notification_e_type;

typedef enum
{
    SIT_VSIM_SIM_TYPE_LOCAL = 0,
    SIT_VSIM_SIM_TYPE_REMOTE = 1
}sit_vsim_sim_type_e_type;

typedef enum
{
    SIT_VSIM_OPERATION_ATR = 0x00,
    SIT_VSIM_OPERATION_APDU = 0x01,
    SIT_VSIM_OPERATION_POWERDOWN = 0x02,
}sit_vsim_operation_e_type;

/**
 * MISC definitions
 */
typedef enum
{
    SIT_MISC_SIG_RAT_SIG_GSM = 0x01,
    SIT_MISC_SIG_RAT_SIG_WCDMA = 0x02,
    SIT_MISC_SIG_RAT_SIG_LTE_V1_4 = 0x04,
    SIT_MISC_SIG_RAT_SIG_CDMA_V1_4 = 0x08,
    SIT_MISC_SIG_RAT_SIG_EVDO_V1_4 = 0x10,
    SIT_MISC_SIG_RAT_SIG_TD_SCDMA_V1_4 = 0x20,
    SIT_MISC_SIG_RAT_SIG_NR_V1_4 = 0x40,
}sit_misc_get_signal_strength_rat_sig_e_type_v1_4;

typedef enum
{
    SIT_MISC_SCREEN_STATE_OFF = 0x00,
    SIT_MISC_SCREEN_STATE_ON
}sit_misc_screen_state_e_type;

typedef enum
{
    SIT_MISC_TTY_MODE_OFF = 0x00,
    SIT_MISC_TTY_MODE_FULL,
    SIT_MISC_TTY_MODE_HCO,    /*hearing carryover*/
    SIT_MISC_TTY_MODE_VCO,    /*voice carryover*/

    SIT_MISC_TTY_MODE_MAX
}sit_misc_tty_mode_e_type;

typedef enum
{
    // EUOPEN GCF
    SIT_ID_SGC_SP_GCF = 0x0000,

    //GLOBAL
    SIT_ID_SGC_SP_WHITE = 0x0100,
    SIT_ID_SGC_SP_EUROPEN = 0x0101,
    SIT_ID_SGC_SP_TMO = 0x0102,
    SIT_ID_SGC_SP_SEAOPEN = 0x0103,
    SIT_ID_SGC_SP_AUS_TELSTRA = 0x0104,
    SIT_ID_SGC_SP_SEANZC = 0x0105,
    SIT_ID_SGC_SP_HUTCH = 0x0106,
    SIT_ID_SGC_SP_ORG = 0x0107,
    SIT_ID_SGC_SP_VODA = 0x0108,
    SIT_ID_SGC_SP_AUSOPEN = 0x0109,

    //N_AMERICA
    SIT_ID_SGC_SP_RED = 0x0200,
    SIT_ID_SGC_SP_AIO = 0x0201,
    SIT_ID_SGC_SP_ATT = 0x0202,
    SIT_ID_SGC_SP_TMOUSA = 0x0203,
    SIT_ID_SGC_SP_ATT_MVNO = 0x0204,
    SIT_ID_SGC_SP_TMOUSA_MVNO = 0x0205,
    SIT_ID_SGC_SP_NA_GCF = 0x0207,
    SIT_ID_SGC_SP_DISH = 0x0208,

    //LATIN_AMERICA
    SIT_ID_SGC_SP_PUMPKIN = 0x0400,
    SIT_ID_SGC_SP_LATIN = 0x0401,
    SIT_ID_SGC_SP_LATIN_GCF = 0x0402,

    //N_AMERICA_CAN
    SIT_ID_SGC_SP_YELLOW = 0x0800,
    SIT_ID_SGC_SP_BMC = 0x0801,
    SIT_ID_SGC_SP_TELUS = 0x0802,
    SIT_ID_SGC_SP_ROGERS = 0x0803,
    SIT_ID_SGC_SP_FREEDOM = 0x0804,

    //N_AMERICA_3GPP2
    SIT_ID_SGC_SP_GREEN = 0x1000,
    SIT_ID_SGC_SP_VZW = 0x1001,
    SIT_ID_SGC_SP_USCC = 0x1002,
    SIT_ID_SGC_SP_SPR = 0x1003,

    //CHINA
    SIT_ID_SGC_SP_BLUE = 0x2000,
    SIT_ID_SGC_SP_CHNOPEN = 0x2001,
    SIT_ID_SGC_SP_CMCC = 0x2002,
    SIT_ID_SGC_SP_HKTW = 0x2003,
    SIT_ID_SGC_SP_CTC = 0x2004,
    SIT_ID_SGC_SP_CUCC = 0x2005,
    SIT_ID_SGC_SP_CHNOPEN_GCF = 0x2006,

    //KOR
    SIT_ID_SGC_SP_INDIGO = 0x4000,
    SIT_ID_SGC_SP_KT = 0x4001,
    SIT_ID_SGC_SP_LGU = 0x4002,
    SIT_ID_SGC_SP_KOROPEN = 0x4003,
    SIT_ID_SGC_SP_SKT = 0x4004,

    //JPN
    SIT_ID_SGC_SP_VIOLET = 0x8000,
    SIT_ID_SGC_SP_NTT = 0x8001,
    SIT_ID_SGC_SP_KDDI = 0x8002,
    SIT_ID_SGC_SP_SBM = 0x8003,
    SIT_ID_SGC_SP_RKT = 0x8004,

    //LATAM
    SIT_ID_SGC_CLARO_AR = 0x0403,
    SIT_ID_SGC_MOV_AR = 0x0404,
    SIT_ID_SGC_TUENTI_AR = 0x0405,
    SIT_ID_SGC_NII_AR = 0x0406,
    SIT_ID_SGC_NUESTRO_AR = 0x0407,
    SIT_ID_SGC_PERSONAL_AR = 0x0407,
    SIT_ID_SGC_TIGO_BO = 0x0408,
    SIT_ID_SGC_VIVA_BO = 0x0409,
    SIT_ID_SGC_CLARO_BR = 0x040A,
    SIT_ID_SGC_VIVO_BR = 0x040B,
    SIT_ID_SGC_NII_BR = 0x040C,
    SIT_ID_SGC_OI_BR = 0x040D,
    SIT_ID_SGC_PORTO_CONECTA_BR = 0x040E,
    SIT_ID_SGC_SURF_BR = 0x040F,
    SIT_ID_SGC_TIM_BR = 0x0410,
    SIT_ID_SGC_CLARO_CL = 0x0411,
    SIT_ID_SGC_MOV_CL = 0x0412,
    SIT_ID_SGC_ENTEL_CL = 0x0413,
    SIT_ID_SGC_WOM_CL = 0x0414,
    SIT_ID_SGC_CLARO_CO = 0x0415,
    SIT_ID_SGC_MOV_CO = 0x0416,
    SIT_ID_SGC_AVANTEL_CO = 0x0417,
    SIT_ID_SGC_ETB_CO = 0x0418,
    SIT_ID_SGC_TIGO_CO = 0x0419,
    SIT_ID_SGC_CLARO_CR = 0x041A,
    SIT_ID_SGC_CLARO_DO = 0x041B,
    SIT_ID_SGC_CLARO_EC = 0x041C,
    SIT_ID_SGC_MOV_EC = 0x041D,
    SIT_ID_SGC_CNT_EC = 0x041E,
    SIT_ID_SGC_CLARO_SV = 0x041F,
    SIT_ID_SGC_TIGO_SV = 0x0420,
    SIT_ID_SGC_CLARO_GT = 0x0421,
    SIT_ID_SGC_TIGO_GT = 0x0422,
    SIT_ID_SGC_CLARO_HN = 0x0423,
    SIT_ID_SGC_TIGO_HO = 0x0424,
    SIT_ID_SGC_TELCEL_MX = 0x025,
    SIT_ID_SGC_MOV_MX = 0x0426,
    SIT_ID_SGC_ALTAN_MX = 0x0427,
    SIT_ID_SGC_ATT_MX = 0x0428,
    SIT_ID_SGC_CLARO_NI = 0x0429,
    SIT_ID_SGC_CLARO_PA = 0x042A,
    SIT_ID_SGC_CLARO_PY = 0x042B,
    SIT_ID_SGC_PERSONAL_PY = 0x042C,
    SIT_ID_SGC_TIGO_PY = 0x042D,
    SIT_ID_SGC_CLARO_PE = 0x042E,
    SIT_ID_SGC_MOV_PE = 0x042F,
    SIT_ID_SGC_ENTEL_PE = 0x0430,
    SIT_ID_SGC_CLARO_PR = 0x0431,
    SIT_ID_SGC_OPEN_MOBILE_PR = 0x0432,
    SIT_ID_SGC_CLARO_UY = 0x0433,
    SIT_ID_SGC_MOV_UY = 0x0434,
    SIT_ID_SGC_ANTEL_UY = 0x0435,
    SIT_ID_SGC_MOV_UZ = 0x0436,

    SIT_ID_SGC_SP_IDX_MAX
}sit_id_sgc_op_idx_e_type;

typedef enum
{
    SIT_NITZ_DAYLIGHT_INFO_VALID = 0x00,
    SIT_NITZ_DAYLIGHT_INFO_INVALID = 0x01
}sit_misc_nitz_daylight_valid_e_type;

typedef enum
{
    SIT_NITZ_DAYLIGHT_ADJUST_NOADJUST = 0x00,
    SIT_NITZ_DAYLIGHT_ADJUST_PLUS1HOUR,
    SIT_NITZ_DAYLIGHT_ADJUST_PLUS2HOUR
}sit_misc_nitz_daylight_adjust_e_type;

typedef enum
{
    SIT_NITZ_DAY_OF_WEEK_SUN = 0x00,
    SIT_NITZ_DAY_OF_WEEK_MON,
    SIT_NITZ_DAY_OF_WEEK_TUE,
    SIT_NITZ_DAY_OF_WEEK_WED,
    SIT_NITZ_DAY_OF_WEEK_THU,
    SIT_NITZ_DAY_OF_WEEK_FRI,
    SIT_NITZ_DAY_OF_WEEK_SAT
}sit_misc_nitz_day_of_week_e_type;

typedef enum
{
    SIT_MISC_CFG_RESET_FACTORY = 0, // factory reset
    SIT_MISC_CFG_RESET_NETWORK = 1, // Reset network related NV and USIM data only
    SIT_MISC_CFG_RESET_MODEM = 2 // modem reset
}sit_misc_cfg_reset_e_type;

// feature bitmask
enum {
    SIT_FEATURE_IWLAN_AP_ASSIST = 0x00000001,
};

enum ScanRat {
    SCAN_RAT_2G,
    SCAN_RAT_3G,
    SCAN_RAT_LTE,
    SCAN_RAT_LTE_CA,
    SCAN_RAT_CDMA,
    SCAN_RAT_TDSCDMA,
    SCAN_RAT_NR,
};

enum Band2G {
    BAND_380T_GSM = 0x01,
    BAND_410_GSM = 0x02,
    BAND_450 = 0x03,
    BAND_480 = 0x04,
    BAND_710 = 0x05,
    BAND_750 = 0x06,
    BAND_810T_GSM = 0x07,
    BAND_850 = 0x08,
    BAND_900P = 0x09,
    BAND_900E = 0x0A,
    BAND_900R = 0x0B,
    BAND_1800DCS = 0x0C,
    BAND_1900PCS = 0x0D,
    BAND_2G_MAX = BAND_1900PCS,
};

// B1 = 0x01, B2 = 0x02, ..., B255 = 0xFF
enum Band3G {
    BAND_3G_MAX = 0xFF,
};

// B1 = 0x01, B2 = 0x02, ..., B255 = 0xFF
enum BandLTE {
    BAND_LTE_MAX = 0xFF,
};

// B1 = 0x01, B2 = 0x02, ..., B255 = 0xFF
enum BandLTECA {
    BAND_LTE_CA_MAX = 0xFF,
};

// B1 = 0x01, B2 = 0x02, ..., B255 = 0xFF
enum BandTDSCDMA {
    BAND_TDSCDMA_MAX = 0xFF,
};

enum BandCDMA {
    BAND_BC0  = 0x01,
    BAND_BC1  = 0x02,
    BAND_BC10 = 0x03,
    BAND_BC15 = 0x04,
    BAND_CDMA_MAX = BAND_BC15,
};

// n1 = 0x01, n2 = 0x02, ..., n86 = 0x56
enum BandNR {
    BAND_NR_MAX = 0x56,
};

enum ScanMode {
    SCAN_ALL = 0x00,
    SCAN_PARTIAL = 0x01,
};

enum ScanFrequency {
    FREQUENCY_MIN = 0,
    FREQUENCY_MAX = 59250,
    FREQUENCY_INVALID,
    FREQUENCY_DEFAULT = 0xFFFF,
};

enum ScanAntennaSel {
    ANTENNA_ALL = 0x00,
    ANTENNA_MAIN_ONLY = 0x01,
    ANTENNA_SUB_ONLY = 0x02,
    ANTENNA_ALL_PRESET = 0x03,
    ANTENNA_MAIN_PRESET = 0x04,
    ANTENNA_SUB_PRESET = 0x05,
    ANTENNA_DEFAULT = 0xFF,
};

/**
 * SMS definitions
 */
typedef enum
{
    SIT_SIM_STATUS_RECEIVED_UNREAD = 0x00,
    SIT_SIM_STATUS_RECEIVED_READ,
    SIT_SIM_STATUS_STORED_UNSENT,
    SIT_SIM_STATUS_STORED_SENT,

    SIT_SIM_STATUS_MAX
}sit_sms_status_e_type;

typedef enum
{
    SIT_SMS_BCST_ACT_ACTIVATE = 0x00,
    SIT_SMS_BCST_ACT_DEACTIVATE,

    SIT_SMS_BCST_ACT_MAX
}sit_sms_bcst_act_e_type;

enum {
    MEMORY_CAPACITY_EXCEEDED = 0x00,
    MEMORY_AVAILABLE = 0x01,
};

typedef enum
{
    SIT_SMS_CDMA_BCST_ACT_ACTIVATE = 0x00,
    SIT_SMS_CDMA_BCST_ACT_DEACTIVATE,

    SIT_SMS_CDMA_BCST_ACT_MAX
}sit_sms_cdma_bcst_act_e_type;

typedef enum
{
    // See 3GPP2 C.S0023 3.4.27
    SIT_RUIM_STATUS_RECEIVED_READ = 0x01,
    SIT_RUIM_STATUS_RECEIVED_UNREAD = 0x03,
    SIT_RUIM_STATUS_STORED_SENT = 0x05,
    SIT_RUIM_STATUS_STORED_UNSENT = 0x07,

    SIT_RUIM_STATUS_MAX
}sit_sms_cdma_status_e_type;

enum {
    STORED_SIM = 0x00,
    STORED_RUIM = 0x01,
};

#define MAX_MCC_LEN (3)
#define MAX_MNC_LEN (3)
#define MAX_CELLID_LEN (4)
#define MAX_SIT_AT_COMMAND_LENGTH    1000 // As per CP JSON document it is 1500

/**
 * Packed data structure
 */
#define SIT_MAX_NO_RAS (4)
#define SPECIAL_AC_LIST (5)

#pragma pack(push)
#pragma pack(1)
typedef struct {
    BYTE desense_operation;
    BYTE rat;      // sit_rf_desense_rat_e_type
    BYTE lte[32];
    BYTE wcdma[8];
    BYTE gsm;
    BYTE cdma[2];
    BYTE power_level[2];
    BYTE arfcn[4];
    BYTE afc[2];
    BYTE tsc[2];
    BYTE pattern;
    BYTE duplex;
    BYTE ul_bw;
    BYTE ul_freq[4];
    BYTE config_index;
    BYTE special_sf_config_index;
    BYTE vrb_start;
    BYTE vrb_length;
    BYTE mcs;
    BYTE cdma_modulation;
}sit_rf_desense_info_type;

typedef struct {
    BYTE for_emc;
    BYTE for_mo_sig_factor;
    INT16 for_mo_sig_time;
    BYTE for_mo_sig_ac_list[SPECIAL_AC_LIST];
    BYTE for_mo_data_factor;
    INT16 for_mo_data_time;
    BYTE for_mo_data_ac_list[SPECIAL_AC_LIST];
    BYTE for_mmtel_voice_factor;
    INT16 for_mmtel_voice_time;
    BYTE for_mmtel_voice_ac_list[SPECIAL_AC_LIST];
    BYTE for_mmtel_video_factor;
    INT16 for_mmtel_video_time;
    BYTE for_mmtel_video_ac_list[SPECIAL_AC_LIST];
} AC_BARRING_INFO;

#pragma pack(pop)

//Sound common enums starts
typedef enum
{
    SIT_SND_RINGBACK_STATE_STOP = 0x00,
    SIT_SND_RINGBACK_STATE_START
}sit_snd_ringback_state_e_type;

typedef enum
{
    SIT_SND_RINGBACK_TONE_FLAG_LOCAL_PLAY = 0x00,
    SIT_SND_RINGBACK_TONE_FLAG_NW_PLAY
}sit_snd_ringback_tone_flag_e_type;

typedef enum
{
    SITRIL_AUDIO_PATH_NONE = 0,
    SITRIL_AUDIO_PATH_HANDSET = 1,                     // Phone MIC -> RECEIVER
    SITRIL_AUDIO_PATH_HEADSET = 2,                     // Headset (MIC -> SPK)
    SITRIL_AUDIO_PATH_HANDSFREE = 3,                   // Handfree (MIC -> SPK)
    SITRIL_AUDIO_PATH_BLUETOOTH = 4,                   // Narrow Band Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_STEREO_BLUETOOTH = 5,            // Narrow Band Stereo Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_SPEAKRERPHONE = 6,               // Phone MIC -> SPEAKER Phone
    SITRIL_AUDIO_PATH_35PI_HEADSET = 7,                // Phone MIC -> Headset SPK
    SITRIL_AUDIO_PATH_BT_NS_EC_OFF = 8,                // Narrow Band Bluetooth (MIC -> SPK) + Noise/Eco Cancellation OFF
    SITRIL_AUDIO_PATH_WB_BLUETOOTH = 9,                // Wide Band Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_WB_BT_NS_EC_OFF = 10,            // Wide Band Bluetooth (MIC -> SPK) + Noise/Eco Cancellation OFF
    SITRIL_AUDIO_PATH_HANDSET_HAC = 11,                // Phone MIC -> RECEIVER for HAC(Hearing Aid Compatibility
    SITRIL_AUDIO_PATH_LINEOUT = 12,                    // Lineout

    SITRIL_AUDIO_PATH_VOLTE_HANDSET = 65,              // VoLTE : Phone MIC -> RECEIVER
    SITRIL_AUDIO_PATH_VOLTE_HEADSET = 66,              // VoLTE : Headset (MIC -> SPK)
    SITRIL_AUDIO_PATH_VOLTE_HFK = 67,                  // VoLTE : Hands Free Kit (MIC -> SPK)
    SITRIL_AUDIO_PATH_VOLTE_BLUETOOTH = 68,            // VoLTE : Narrow Band Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_VOLTE_STEREO_BLUETOOTH = 69,     // VoLTE : Narrow Band Stereo Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_VOLTE_SPEAKRERPHONE = 70,        // VoLTE : Phone MIC -> SPEAKER Pone
    SITRIL_AUDIO_PATH_VOLTE_35PI_HEADSET = 71,         // VoLTE : Phone MIC -> Headset SPK
    SITRIL_AUDIO_PATH_VOLTE_BT_NS_EC_OFF = 72,         // VoLTE : Narrow Band Bluetooth (MIC -> SPK) + Noise/Eco Cancellation OFF
    SITRIL_AUDIO_PATH_VOLTE_WB_BLUETOOTH = 73,         // VoLTE : Wide Band Bluetooth (MIC -> SPK)
    SITRIL_AUDIO_PATH_VOLTE_WB_BT_NS_EC_OFF = 74,      // VoLTE : Wide Band Bluetooth (MIC -> SPK) + Noise/Eco Cancellation OFF
    SITRIL_AUDIO_PATH_VOLTE_VOLTE_HANDSET_HAC = 75,    // VoLTE : Phone MIC -> RECEIVER for HAC(Hearing Aid Compatibility
    SITRIL_AUDIO_PATH_VOLTE_LINEOUT = 76,              // VoLTE Lineout

    SITRIL_AUDIO_PATH_MAX
}sit_snd_audiopath_e_mode;

typedef enum
{
    SITRIL_MULTIMIC_NONE = 0x00,    // Off
    SITRIL_MULTIMIC_ONE = 0x01,
    SITRIL_MULTIMIC_TWO = 0x02,
    SITRIL_MULTIMIC_THREE = 0x03,
    SITRIL_MULTIMIC_MAX
} sit_snd_multiMIC_e_mode;

typedef enum
{
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_OFF = 0,   //0x00 : WB-AMR Off
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_ON = 1,    //0x01 : WB-AMR On
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_NB = 0,    // Narrow Band
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_WB = 1,    // Wide Band
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_SWB = 8,   // Super WB
    SITRIL_AUDIO_WB_AMR_REPORT_STATUS_FB = 9,    // Full Band
} sit_snd_wb_amr_report_status_e_type;

enum {
    SIT_AUDIO_CALL_TYPE_UNKNOWN = 0,
    SIT_AUDIO_CALL_TYPE_GSM     = 1,
    SIT_AUDIO_CALL_TYPE_CDMA    = 2,
    SIT_AUDIO_CALL_TYPE_IMS     = 4,
    SIT_AUDIO_CALL_TYPE_OTHERS  = 8,
}sit_snd_wb_amr_report_rat_e_type;

typedef enum
{
    SITRIL_AUDIO_WMAMR_3GNARROW_2GNARROW = 0,    //0: 3G Narrow & 2G Narrow
    SITRIL_AUDIO_WMAMR_3GWIDE_2GNARROW = 1,    //1: 3G Wide & 2G Narrow
    SITRIL_AUDIO_WMAMR_3GNARROW_2GWIDE = 2,    //2: 3G Narrow & 2G Wide
    SITRIL_AUDIO_WMAMR_3GWIDE_2GWIDE = 3,    //3: 3G Wide & 2G Wide

    SITRIL_AUDIO_WMAMR_MAX
} sit_snd_wbamr_capability_e_type;

/**
 * eMBMS
 */
typedef enum {
    EMBMS_NO_COVERAGE = 0,
    EMBMS_UNICAST_COVERAGE,
    EMBMS_FULL_COVERAGE,
    EMBMS_UNKNOW_STATE_COVERAGE = 0xFF
} sit_embms_coverage_e_type;

/*
    BIP
*/
enum {
    WIFI_CHANNEL_EVENT_RECEIVED = 0x01,
    WIFI_CHANNEL_EVENT_CONNECTED = 0x02,
    WIFI_CHANNEL_EVENT_CLOSED = 0x03
};

enum {
    BIP_TRANSPORT_TCP = 0x01,
    BIP_TRANSPORT_UDP = 0x02
};

enum {
    BIP_IPV4 = 0x01,
    BIP_IPV6 = 0x02,
    BIP_IPV4V6 = 0x03,
    BIP_PDP_PPP = 0x04,
    BIP_PDP_NON_IP = 0x05
};

enum {
    WIFI_RESULT_SUCCESS = 0x00,
    WIFI_RESULT_FAILURE = 0x01
};
