#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ifeq ($(TARGET_SOC_BASE), s5e9815)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := tlkeymasterM
LOCAL_MODULE_STEM := 0706000000000000000000000000004d
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlwvdrm
LOCAL_MODULE_STEM := 00060308060501020000000000000000
LOCAL_MODULE_SUFFIX := .tabin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlcmdrv
LOCAL_MODULE_STEM := FFFFFFFFD00000000000000000000016
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlcmtest
LOCAL_MODULE_STEM := 04010000000000000000000000000000
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := cm_test
LOCAL_MODULE_STEM := cm_test
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := whitelist
LOCAL_MODULE_STEM := public.libraries
LOCAL_MODULE_SUFFIX := .txt
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/etc
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := gatekeeper.$(TARGET_SOC)
LOCAL_MODULE_STEM := 07061000000000000000000000000000
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlrpmb
LOCAL_MODULE_STEM := 09090000070100010000000000000000
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlrpmb_64
LOCAL_MODULE_STEM := 09090000070100010000000000000604
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := bRPMB
LOCAL_MODULE_STEM := bRPMB
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := bRPMB-CMD
LOCAL_MODULE_STEM := bRPMB-CMD
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)

LOCAL_MODULE := tlspidrv
LOCAL_MODULE_STEM := ffffffffd0000000000000000000000e
LOCAL_MODULE_SUFFIX := .tlbin
LOCAL_SRC_FILES := $(LOCAL_MODULE_STEM)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_APPS)/mcRegistry
LOCAL_MODULE_OWNER := samsung

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := km_keybox_attestation
LOCAL_SRC_FILES := tools/km_keybox_attestation
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/bin
LOCAL_MODULE_OWNER := samsung

LOCAL_MULTILIB := 32
LOCAL_SHARED_LIBRARIES := libMcClient libc libc++ libcrypto libcutils libdl liblog libm libutils libxml2

include $(BUILD_PREBUILT)


endif
