/* copyright Samsung Electronics Co., LTD.
 *
 * This software is proprietary of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed, transmitted,
 * transcribed, stored in a retrieval system or translated into any human or computer language in any form by any means,
 * electronic, mechanical, manual or otherwise, or disclosed
 * to third parties without the express written permission of Samsung Electronics.
 */


/* RIL OEM  */
#ifndef _RIL_OEM_H
#define _RIL_OEM_H

#ifndef RIL_OEM_REQUEST_BASE
#define RIL_OEM_REQUEST_BASE 10000
#endif

#ifndef RIL_OEM_UNSOL_RESPONSE_BASE
#define RIL_OEM_UNSOL_RESPONSE_BASE 20000
#endif

/******************** OEM Requests *****************************/
#define RIL_REQUEST_OEM_INVALID                                 (0)
#define RIL_REQUEST_OEM_MODEM_DUMP                              (RIL_OEM_REQUEST_BASE + 100)
#define RIL_REQUEST_OEM_VOLUME_SET                              (RIL_OEM_REQUEST_BASE + 101)
#define RIL_REQUEST_OEM_VOLUME_GET                              (RIL_OEM_REQUEST_BASE + 102)
#define RIL_REQUEST_OEM_AUDIO_PATH_SET                          (RIL_OEM_REQUEST_BASE + 103)
#define RIL_REQUEST_OEM_AUDIO_PATH_GET                          (RIL_OEM_REQUEST_BASE + 104)
#define RIL_REQUEST_OEM_MICROPHONE_SET                          (RIL_OEM_REQUEST_BASE + 105)
#define RIL_REQUEST_OEM_MICROPHONE_GET                          (RIL_OEM_REQUEST_BASE + 106)
#define RIL_REQUEST_OEM_SET_PS_ATTACH_DETACH                    (RIL_OEM_REQUEST_BASE + 107)
#define RIL_REQUEST_OEM_GET_PS_ATTACH_DETACH                    (RIL_OEM_REQUEST_BASE + 108)
#define RIL_REQUEST_OEM_GET_RADIO_STATE                         (RIL_OEM_REQUEST_BASE + 109)
#define RIL_REQUEST_OEM_IMS_SET_CONFIGURATION                   (RIL_OEM_REQUEST_BASE + 110)
#define RIL_REQUEST_OEM_IMS_GET_CONFIGURATION                   (RIL_OEM_REQUEST_BASE + 111)
#define RIL_REQUEST_OEM_IMS_SIM_AUTH                            (RIL_OEM_REQUEST_BASE + 112)
#define RIL_REQUEST_OEM_IMS_SET_EMERGENCY_CALL_STATUS           (RIL_OEM_REQUEST_BASE + 113)
#define RIL_REQUEST_OEM_IMS_SET_SRVCC_CALL_LIST                 (RIL_OEM_REQUEST_BASE + 114)
#define RIL_REQUEST_OEM_IMS_GET_GBA_AUTH                        (RIL_OEM_REQUEST_BASE + 115)
#define RIL_REQUEST_OEM_MODEM_RESET                             (RIL_OEM_REQUEST_BASE + 116)
#define RIL_REQUEST_OEM_GET_MANUAL_RAT_MODE                     (RIL_OEM_REQUEST_BASE + 117)
#define RIL_REQUEST_OEM_SET_MANUAL_RAT_MODE                     (RIL_OEM_REQUEST_BASE + 118)
#define RIL_REQUEST_OEM_GET_FREQUENCY_LOCK                      (RIL_OEM_REQUEST_BASE + 119)
#define RIL_REQUEST_OEM_SET_FREQUENCY_LOCK                      (RIL_OEM_REQUEST_BASE + 120)
#define RIL_REQUEST_OEM_SET_ENDC_MODE                           (RIL_OEM_REQUEST_BASE + 121)
#define RIL_REQUEST_OEM_GET_ENDC_MODE                           (RIL_OEM_REQUEST_BASE + 122)
#define RIL_REQUEST_OEM_IMS_SIM_IO                              (RIL_OEM_REQUEST_BASE + 123)
#define RIL_REQUEST_OEM_SET_IMS_TEST_MODE                       (RIL_OEM_REQUEST_BASE + 124)
#define RIL_REQUEST_OEM_AUDIO_CLOCK_SET                         (RIL_OEM_REQUEST_BASE + 125)
#define RIL_REQUEST_OEM_AUDIO_LOOPBACK_SET                      (RIL_OEM_REQUEST_BASE + 126)
#define RIL_REQUEST_OEM_SET_TTY_MODE                            (RIL_OEM_REQUEST_BASE + 127)
#define RIL_REQUEST_OEM_SET_UICC_SUBSCRIPTION                   (RIL_OEM_REQUEST_BASE + 128)
#define RIL_REQUEST_OEM_SET_ENG_MODE                            (RIL_OEM_REQUEST_BASE + 129)
#define RIL_REQUEST_OEM_SET_SCR_LINE                            (RIL_OEM_REQUEST_BASE + 130)
#define RIL_REQUEST_OEM_SET_DEBUG_TRACE                         (RIL_OEM_REQUEST_BASE + 131)
#define RIL_REQUEST_OEM_CANCEL_AVAILABLE_NETWORKS               (RIL_OEM_REQUEST_BASE + 132)
//#define RIL_REQUEST_OEM_SIM_AUTHENTICATION                      (RIL_OEM_REQUEST_BASE + 133)  // deprecated
#define RIL_REQUEST_OEM_IF_EXECUTE_AM                           (RIL_OEM_REQUEST_BASE + 134)
#define RIL_REQUEST_OEM_DETACH                                  (RIL_OEM_REQUEST_BASE + 135)
#define RIL_REQUEST_OEM_SET_AP_SYSTEM_TIME                      (RIL_OEM_REQUEST_BASE + 136)
#define RIL_REQUEST_OEM_SET_CARRIER_CONFIG                      (RIL_OEM_REQUEST_BASE + 137)
#define RIL_REQUEST_OEM_SET_ENG_STRING_INPUT                    (RIL_OEM_REQUEST_BASE + 138)
#define RIL_REQUEST_OEM_APN_SETTINGS                            (RIL_OEM_REQUEST_BASE + 139)
#define RIL_REQUEST_OEM_GET_MSL_CODE                            (RIL_OEM_REQUEST_BASE + 140)
#define RIL_REQUEST_OEM_SET_PIN_CONTROL                         (RIL_OEM_REQUEST_BASE + 141)
#define RIL_REQUEST_OEM_SEND_SGC                                (RIL_OEM_REQUEST_BASE + 142)
#define RIL_REQUEST_OEM_GET_MANUAL_BAND_MODE                    (RIL_OEM_REQUEST_BASE + 143)
#define RIL_REQUEST_OEM_SET_MANUAL_BAND_MODE                    (RIL_OEM_REQUEST_BASE + 144)
#define RIL_REQUEST_OEM_GET_RF_DESENSE_MODE                     (RIL_OEM_REQUEST_BASE + 145)
#define RIL_REQUEST_OEM_SET_RF_DESENSE_MODE                     (RIL_OEM_REQUEST_BASE + 146)
#define RIL_REQUEST_OEM_GET_IMS_SUPPORT_SERVICE                 (RIL_OEM_REQUEST_BASE + 147)
#define RIL_REQUEST_OEM_SCAN_RSSI                               (RIL_OEM_REQUEST_BASE + 148)
#define RIL_REQUEST_OEM_FORWARDING_AT_COMMAND                   (RIL_OEM_REQUEST_BASE + 149)
#define RIL_REQUEST_OEM_SET_MODEM_LOG_DUMP                      (RIL_OEM_REQUEST_BASE + 150)
#define RIL_REQUEST_OEM_SET_PREFERRED_CALL_CAPABILITY           (RIL_OEM_REQUEST_BASE + 151)
#define RIL_REQUEST_OEM_GET_PREFERRED_CALL_CAPABILITY           (RIL_OEM_REQUEST_BASE + 152)
#define RIL_REQUEST_OEM_TS25TABLE_DUMP                          (RIL_OEM_REQUEST_BASE + 153)
#define RIL_REQUEST_OEM_SET_VOICE_OPERATION                     (RIL_OEM_REQUEST_BASE + 154)
#define RIL_REQUEST_OEM_GET_VOICE_OPERATION                     (RIL_OEM_REQUEST_BASE + 155)
#define RIL_REQUEST_OEM_SET_NR_MODE                             (RIL_OEM_REQUEST_BASE + 156)
#define RIL_REQUEST_OEM_GET_NR_MODE                             (RIL_OEM_REQUEST_BASE + 157)

/* getAvilableNetwork with RAN(Radio Access Network) */
#define RIL_REQUEST_OEM_GET_AVAILABLE_NETWORKS                  (RIL_OEM_REQUEST_BASE + 158)
#define RIL_REQUEST_OEM_GET_FREQUENCY_INFO                      (RIL_OEM_REQUEST_BASE + 159)
#define RIL_REQUEST_OEM_SET_FEATURE_INFO                        (RIL_OEM_REQUEST_BASE + 160)
#define RIL_REQUEST_OEM_SET_URSP                                (RIL_OEM_REQUEST_BASE + 161)
#define RIL_REQUEST_OEM_SET_NR_SILENCE_MODE                     (RIL_OEM_REQUEST_BASE + 162)
#define RIL_REQUEST_OEM_GET_NR_SILENCE_MODE                     (RIL_OEM_REQUEST_BASE + 163)
#define RIL_REQUEST_OEM_SET_EMC_LAB_TEST_MODE                   (RIL_OEM_REQUEST_BASE + 164)
#define RIL_REQUEST_OEM_SET_VONR_CAPA                           (RIL_OEM_REQUEST_BASE + 165)
#define RIL_REQUEST_OEM_GET_VONR_CAPA                           (RIL_OEM_REQUEST_BASE + 166)
#define RIL_REQUEST_OEM_SET_PLMN_LIST                           (RIL_OEM_REQUEST_BASE + 167)
#define RIL_REQUEST_OEM_GET_PLMN_LIST                           (RIL_OEM_REQUEST_BASE + 168)
#define RIL_REQUEST_OEM_SET_IMS_REGISTRATION_STATE              (RIL_OEM_REQUEST_BASE + 169)
#define RIL_REQUEST_OEM_SET_MOBILE_DATA_STATE                   (RIL_OEM_REQUEST_BASE + 170)
#define RIL_REQUEST_OEM_SEND_TEST_JSON_DATA                     (RIL_OEM_REQUEST_BASE + 171)
#define RIL_REQUEST_OEM_SET_SIGNAL_STRENGTH_REPORTING_CRITERIA  (RIL_OEM_REQUEST_BASE + 172)
#define RIL_REQUEST_OEM_SET_INTERNAL_IA                         (RIL_OEM_REQUEST_BASE + 173)
#define RIL_REQUEST_OEM_GET_SERVING_NETWORK_PLMN                (RIL_OEM_REQUEST_BASE + 174)
#define RIL_REQUEST_OEM_GET_NITZ_TIME                           (RIL_OEM_REQUEST_BASE + 175)
#define RIL_REQUEST_OEM_RRC_INFO                                (RIL_OEM_REQUEST_BASE + 176)

//AIMS support start ---------------------
#define RIL_REQUEST_OEM_AIMS_DIAL                               (RIL_OEM_REQUEST_BASE + 300)
#define RIL_REQUEST_OEM_AIMS_ANSWER                             (RIL_OEM_REQUEST_BASE + 301)
#define RIL_REQUEST_OEM_AIMS_HANGUP                             (RIL_OEM_REQUEST_BASE + 302)
#define RIL_REQUEST_OEM_AIMS_DEREGISTRATION                     (RIL_OEM_REQUEST_BASE + 303)
#define RIL_REQUEST_OEM_AIMS_HIDDEN_MENU                        (RIL_OEM_REQUEST_BASE + 304)
#define RIL_REQUEST_OEM_AIMS_ADD_PDN_INFO                       (RIL_OEM_REQUEST_BASE + 305)
#define RIL_REQUEST_OEM_AIMS_CALL_MANAGE                        (RIL_OEM_REQUEST_BASE + 306)
#define RIL_REQUEST_OEM_AIMS_SEND_DTMF                          (RIL_OEM_REQUEST_BASE + 307)
#define RIL_REQUEST_OEM_AIMS_SET_FRAME_TIME                     (RIL_OEM_REQUEST_BASE + 308)
#define RIL_REQUEST_OEM_AIMS_GET_FRAME_TIME                     (RIL_OEM_REQUEST_BASE + 309)
#define RIL_REQUEST_OEM_AIMS_CALL_MODIFY                        (RIL_OEM_REQUEST_BASE + 310)
#define RIL_REQUEST_OEM_AIMS_RESPONSE_CALL_MODIFY               (RIL_OEM_REQUEST_BASE + 311)
#define RIL_REQUEST_OEM_AIMS_TIME_INFO                          (RIL_OEM_REQUEST_BASE + 312)
#define RIL_REQUEST_OEM_AIMS_CONF_CALL_ADD_REMOVE_USER          (RIL_OEM_REQUEST_BASE + 313)
#define RIL_REQUEST_OEM_AIMS_ENHANCED_CONF_CALL                 (RIL_OEM_REQUEST_BASE + 314)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_FORWARD_STATUS            (RIL_OEM_REQUEST_BASE + 315)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_FORWARD_STATUS            (RIL_OEM_REQUEST_BASE + 316)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_WAITING                   (RIL_OEM_REQUEST_BASE + 317)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_WAITING                   (RIL_OEM_REQUEST_BASE + 318)
#define RIL_REQUEST_OEM_AIMS_GET_CALL_BARRING                   (RIL_OEM_REQUEST_BASE + 319)
#define RIL_REQUEST_OEM_AIMS_SET_CALL_BARRING                   (RIL_OEM_REQUEST_BASE + 320)
#define RIL_REQUEST_OEM_AIMS_SEND_SMS                           (RIL_OEM_REQUEST_BASE + 321)
#define RIL_REQUEST_OEM_AIMS_SEND_EXPECT_MORE                   (RIL_OEM_REQUEST_BASE + 322)
#define RIL_REQUEST_OEM_AIMS_SEND_SMS_ACK                       (RIL_OEM_REQUEST_BASE + 323)
#define RIL_REQUEST_OEM_AIMS_SEND_ACK_INCOMING_SMS              (RIL_OEM_REQUEST_BASE + 324)
#define RIL_REQUEST_OEM_AIMS_CHG_BARRING_PWD                    (RIL_OEM_REQUEST_BASE + 325)
#define RIL_REQUEST_OEM_AIMS_SEND_USSD_INFO                     (RIL_OEM_REQUEST_BASE + 326)
#define RIL_REQUEST_OEM_AIMS_GET_PRESENTATION_SETTINGS          (RIL_OEM_REQUEST_BASE + 327)
#define RIL_REQUEST_OEM_AIMS_SET_PRESENTATION_SETTINGS          (RIL_OEM_REQUEST_BASE + 328)
#define RIL_REQUEST_OEM_AIMS_SET_SELF_CAPABILITY                (RIL_OEM_REQUEST_BASE + 329)
#define RIL_REQUEST_OEM_AIMS_HO_TO_WIFI_READY                   (RIL_OEM_REQUEST_BASE + 330)
#define RIL_REQUEST_OEM_AIMS_HO_TO_WIFI_CANCEL_IND              (RIL_OEM_REQUEST_BASE + 331)
#define RIL_REQUEST_OEM_AIMS_HO_PAYLOAD_IND                     (RIL_OEM_REQUEST_BASE + 332)
#define RIL_REQUEST_OEM_AIMS_HO_TO_3GPP                         (RIL_OEM_REQUEST_BASE + 333)
#define RIL_REQUEST_OEM_AIMS_SEND_ACK_INCOMING_CDMA_SMS         (RIL_OEM_REQUEST_BASE + 334)
#define RIL_REQUEST_OEM_AIMS_MEDIA_STATE_IND                    (RIL_OEM_REQUEST_BASE + 335)
#define RIL_REQUEST_OEM_AIMS_DEL_PDN_INFO                       (RIL_OEM_REQUEST_BASE + 336)
#define RIL_REQUEST_OEM_AIMS_STACK_START_REQ                    (RIL_OEM_REQUEST_BASE + 337)
#define RIL_REQUEST_OEM_AIMS_STACK_STOP_REQ                     (RIL_OEM_REQUEST_BASE + 338)
#define RIL_REQUEST_OEM_AIMS_XCAPM_START_REQ                    (RIL_OEM_REQUEST_BASE + 339)
#define RIL_REQUEST_OEM_AIMS_XCAPM_STOP_REQ                     (RIL_OEM_REQUEST_BASE + 340)
#define RIL_REQUEST_OEM_AIMS_RTT_SEND_TEXT                      (RIL_OEM_REQUEST_BASE + 341)
#define RIL_REQUEST_OEM_AIMS_EXIT_EMERGENCY_CB_MODE             (RIL_OEM_REQUEST_BASE + 342)
#define RIL_REQUEST_OEM_AIMS_SET_GEO_LOCATION_INFO              (RIL_OEM_REQUEST_BASE + 343)
#define RIL_REQUEST_OEM_AIMS_CDMA_SEND_SMS                      (RIL_OEM_REQUEST_BASE + 344)
#define RIL_REQUEST_OEM_AIMS_SET_PDN_EST_STATUS                 (RIL_OEM_REQUEST_BASE + 345)
#define RIL_REQUEST_OEM_AIMS_SET_HIDDEN_MENU_ITEM               (RIL_OEM_REQUEST_BASE + 346)
#define RIL_REQUEST_OEM_AIMS_GET_HIDDEN_MENU_ITEM               (RIL_OEM_REQUEST_BASE + 347)
#define RIL_REQUEST_OEM_AIMS_SET_RTP_RX_STATISTICS              (RIL_OEM_REQUEST_BASE + 348)
#define RIL_REQUEST_OEM_AIMS_AT_CMD_FORWARDING                  (RIL_OEM_REQUEST_BASE + 349)
#define RIL_REQUEST_OEM_AIMS_CALL_TRANSFER                      (RIL_OEM_REQUEST_BASE + 350)
#define RIL_REQUEST_OEM_AIMS_COMMON_IMS_SVC_INFO                (RIL_OEM_REQUEST_BASE + 351)
#define RIL_REQUEST_OEM_AIMS_COMPOSER_MMTEL                     (RIL_OEM_REQUEST_BASE + 352)
#define RIL_REQUEST_OEM_AIMS_CANCEL_COMPOSER_MMTEL              (RIL_OEM_REQUEST_BASE + 353)
#define RIL_REQUEST_OEM_AIMS_SET_RTP_HEADER_EXTENSION_TYPE      (RIL_OEM_REQUEST_BASE + 354)
#define RIL_REQUEST_OEM_AIMS_SEND_RTP_HEADER_EXTENSION          (RIL_OEM_REQUEST_BASE + 355)
#define RIL_REQUEST_OEM_AIMS_SEND_UL_SIP_MSG_IND                (RIL_OEM_REQUEST_BASE + 357)
#define RIL_REQUEST_OEM_AIMS_DL_SIP_MSG_RESULT_IND              (RIL_OEM_REQUEST_BASE + 358)
#define RIL_REQUEST_OEM_AIMS_REGISTER_IND                       (RIL_OEM_REQUEST_BASE + 359)
#define RIL_REQUEST_OEM_AIMS_ENRICHED_CALLING                   (RIL_OEM_REQUEST_BASE + 360)
#define RIL_REQUEST_OEM_AIMS_EMERGENCY_VOWIFI_CAPABILITY        (RIL_OEM_REQUEST_BASE + 361)
#define RIL_REQUEST_OEM_AIMS_CALL_DEFLECTION_REQ                (RIL_OEM_REQUEST_BASE + 362)
#define RIL_REQUEST_OEM_AIMS_SET_TEMP_EMERGENCY_NUMBER          (RIL_OEM_REQUEST_BASE + 363)
#define RIL_REQUEST_OEM_AIMS_DC_SESSION_UPDATE                  (RIL_OEM_REQUEST_BASE + 364)
#define RIL_REQUEST_OEM_AIMS_DC_SESSION_MANAGE                  (RIL_OEM_REQUEST_BASE + 365)
#define RIL_REQUEST_OEM_AIMS_DC_SESSION_MODIFY_IND              (RIL_OEM_REQUEST_BASE + 366)

//AIMS support end ---------------------

//AGPS support start ---------------------
#define RIL_REQUEST_OEM_GPS_SET_FREQUENCY_AIDING                (RIL_OEM_REQUEST_BASE + 400)
#define RIL_REQUEST_OEM_GPS_GET_LPP_SUPL_REQ_ECID_INFO          (RIL_OEM_REQUEST_BASE + 401)
#define RIL_REQUEST_OEM_GPS_SET_RRLP_SUPL_REQ_ECID_INFO         (RIL_OEM_REQUEST_BASE + 402)
#define RIL_REQUEST_OEM_GPS_MO_LOCATION_REQUEST                 (RIL_OEM_REQUEST_BASE + 403)
#define RIL_REQUEST_OEM_GPS_GET_LPP_REQ_SERVING_CELL_INFO       (RIL_OEM_REQUEST_BASE + 404)
#define RIL_REQUEST_OEM_GPS_SET_SUPL_NI_READY                   (RIL_OEM_REQUEST_BASE + 405)
#define RIL_REQUEST_OEM_GPS_GET_GSM_EXT_INFO_MSG                (RIL_OEM_REQUEST_BASE + 406)
#define RIL_REQUEST_OEM_GPS_CONTROL_PLANE_ENABLE                (RIL_OEM_REQUEST_BASE + 407)
#define RIL_REQUEST_OEM_GPS_GNSS_LPP_PROFILE_SET                (RIL_OEM_REQUEST_BASE + 408)
#define RIL_REQUEST_OEM_GPS_SET_GNSS_BLANKING                   (RIL_OEM_REQUEST_BASE + 409)
#define RIL_REQUEST_OEM_GPS_GET_SIM_STATE                       (RIL_OEM_REQUEST_BASE + 410)
#define RIL_REQUEST_OEM_GPS_GET_NETWORK_TYPE                    (RIL_OEM_REQUEST_BASE + 411)
#define RIL_REQUEST_OEM_IS_CAMPING_ON_LTE                       (RIL_OEM_REQUEST_BASE + 412)

// Indication from AP, No resp
#define RIL_REQUEST_OEM_GPS_MEASURE_POS_RSP                     (RIL_OEM_REQUEST_BASE + 430)
#define RIL_REQUEST_OEM_GPS_RELEASE_GPS                         (RIL_OEM_REQUEST_BASE + 431)
#define RIL_REQUEST_OEM_GPS_MT_LOCATION_REQUEST                 (RIL_OEM_REQUEST_BASE + 432)
#define RIL_REQUEST_OEM_GPS_LPP_PROVIDE_CAPABILITIES            (RIL_OEM_REQUEST_BASE + 433)
#define RIL_REQUEST_OEM_GPS_LPP_REQUEST_ASSIST_DATA             (RIL_OEM_REQUEST_BASE + 434)
#define RIL_REQUEST_OEM_GPS_LPP_PROVIDE_LOCATION_INFO           (RIL_OEM_REQUEST_BASE + 435)
#define RIL_REQUEST_OEM_GPS_LPP_GPS_ERROR_IND                   (RIL_OEM_REQUEST_BASE + 436)
#define RIL_REQUEST_OEM_GPS_SUPL_LPP_DATA_INFO                  (RIL_OEM_REQUEST_BASE + 437)
#define RIL_REQUEST_OEM_GPS_SUPL_NI_MESSAGE                     (RIL_OEM_REQUEST_BASE + 438)
#define RIL_REQUEST_OEM_GPS_RETRIEVE_LOC_INFO                   (RIL_OEM_REQUEST_BASE + 439)
#define RIL_REQUEST_OEM_GPS_SET_GNSS_BLANKING_TDL               (RIL_OEM_REQUEST_BASE + 440)

// for CDMA & HEDGE GANSS
#define RIL_REQUEST_OEM_GPS_SET_GANSS_MEAS_POS_RSP              (RIL_OEM_REQUEST_BASE + 450)
#define RIL_REQUEST_OEM_GPS_SET_GPS_LOCK_MODE                   (RIL_OEM_REQUEST_BASE + 451)
#define RIL_REQUEST_OEM_GPS_GET_REFERENCE_LOCATION              (RIL_OEM_REQUEST_BASE + 452)
#define RIL_REQUEST_OEM_GPS_SET_PSEUDO_RANGE_MEASUREMENTS       (RIL_OEM_REQUEST_BASE + 453)
#define RIL_REQUEST_OEM_GPS_GET_CDMA_PRECISE_TIME_AIDING_INFO   (RIL_OEM_REQUEST_BASE + 454)
#define RIL_REQUEST_OEM_GPS_CDMA_FREQ_AIDING                    (RIL_OEM_REQUEST_BASE + 455)

// Indication from AP, No resp
#define RIL_REQUEST_OEM_GPS_GANSS_AP_POS_CAP_RSP                (RIL_OEM_REQUEST_BASE + 480)
//AGPS support end ---------------------


/* WFC */
#define RIL_REQUEST_OEM_WFC_MEDIA_CHANNEL_CONFIG                (RIL_OEM_REQUEST_BASE + 500)
#define RIL_REQUEST_OEM_WFC_DTMF_START                          (RIL_OEM_REQUEST_BASE + 501)
#define RIL_REQUEST_OEM_WFC_SET_VOWIFI_HO_THRESHOLD             (RIL_OEM_REQUEST_BASE + 502)

/* Secure Element */
#define RIL_REQUEST_OEM_SIM_OPEN_CHANNEL                        (RIL_OEM_REQUEST_BASE + 520)
#define RIL_REQUEST_OEM_SIM_TRANSMIT_APDU_LOGICAL               (RIL_OEM_REQUEST_BASE + 521)
#define RIL_REQUEST_OEM_SIM_TRANSMIT_APDU_BASIC                 (RIL_OEM_REQUEST_BASE + 522)
#define RIL_REQUEST_OEM_SIM_PRESENT                             (RIL_OEM_REQUEST_BASE + 523)
#define RIL_REQUEST_OEM_SIM_RESET                               (RIL_OEM_REQUEST_BASE + 524)

/* eMBMS */
#define RIL_REQUEST_OEM_EMBMS_ENABLE_SERVICE                    (RIL_OEM_REQUEST_BASE + 540)
#define RIL_REQUEST_OEM_EMBMS_DISABLE_SERVICE                   (RIL_OEM_REQUEST_BASE + 541)
#define RIL_REQUEST_OEM_EMBMS_SET_SESSION                       (RIL_OEM_REQUEST_BASE + 542)
#define RIL_REQUEST_OEM_EMBMS_GET_SESSION_LIST                  (RIL_OEM_REQUEST_BASE + 543)
#define RIL_REQUEST_OEM_EMBMS_GET_SIGNAL_STRENGTH               (RIL_OEM_REQUEST_BASE + 544)
#define RIL_REQUEST_OEM_EMBMS_GET_NETWORK_TIME                  (RIL_OEM_REQUEST_BASE + 545)
#define RIL_REQUEST_OEM_EMBMS_CHECK_AVAIABLE_EMBMS              (RIL_OEM_REQUEST_BASE + 546)

/* BIP Channel Manager */
#define RIL_REQUEST_OEM_WIFI_STATUS_RESPONSE                    (RIL_OEM_REQUEST_BASE + 560)
#define RIL_REQUEST_OEM_WIFI_CHANNEL_STATUS_REPORT              (RIL_OEM_REQUEST_BASE + 561)
#define RIL_REQUEST_OEM_WIFI_OPEN_CHANNEL_RESPONSE              (RIL_OEM_REQUEST_BASE + 562)
#define RIL_REQUEST_OEM_WIFI_SEND_DATA_RESPONSE                 (RIL_OEM_REQUEST_BASE + 563)
#define RIL_REQUEST_OEM_WIFI_RECEIVE_DATA_RESPONSE              (RIL_OEM_REQUEST_BASE + 564)
#define RIL_REQUEST_OEM_WIFI_CLOSE_CHANNEL_RESPONSE             (RIL_OEM_REQUEST_BASE + 565)

/* RCS command */
#define RIL_REQUEST_OEM_AIMS_RCS_MULTI_FRAME                    (RIL_OEM_REQUEST_BASE + 580)
#define RIL_REQUEST_OEM_AIMS_RCS_CHAT                           (RIL_OEM_REQUEST_BASE + 581)
#define RIL_REQUEST_OEM_AIMS_RCS_GROUP_CHAT                     (RIL_OEM_REQUEST_BASE + 582)
#define RIL_REQUEST_OEM_AIMS_RCS_OFFLINE_MODE                   (RIL_OEM_REQUEST_BASE + 583)
#define RIL_REQUEST_OEM_AIMS_RCS_FILE_TRANSFER                  (RIL_OEM_REQUEST_BASE + 584)
#define RIL_REQUEST_OEM_AIMS_RCS_COMMON_MESSAGE                 (RIL_OEM_REQUEST_BASE + 585)
#define RIL_REQUEST_OEM_AIMS_RCS_CONTENT_SHARE                  (RIL_OEM_REQUEST_BASE + 586)
#define RIL_REQUEST_OEM_AIMS_RCS_PRESENCE                       (RIL_OEM_REQUEST_BASE + 587)
#define RIL_REQUEST_OEM_AIMS_XCAP_MANAGE                        (RIL_OEM_REQUEST_BASE + 588)
#define RIL_REQUEST_OEM_AIMS_RCS_CONFIG_MANAGE                  (RIL_OEM_REQUEST_BASE + 589)
#define RIL_REQUEST_OEM_AIMS_RCS_TLS_MANAGE                     (RIL_OEM_REQUEST_BASE + 590)

/* Call Barring */
#define RIL_REQUEST_OEM_CHANGE_BARRING_PASSWORD_OVER_MMI        (RIL_OEM_REQUEST_BASE + 600)

#define RIL_REQUEST_OEM_IMS_SIP_MESSAGE                         (RIL_OEM_REQUEST_BASE + 680)
#define RIL_REQUEST_OEM_IMS_UPDATE_REGISTRATION_INFO            (RIL_OEM_REQUEST_BASE + 681)
#define RIL_REQUEST_OEM_IMS_START_IMS_TRAFFIC                   (RIL_OEM_REQUEST_BASE + 682)
#define RIL_REQUEST_OEM_IMS_STOP_IMS_TRAFFIC                    (RIL_OEM_REQUEST_BASE + 683)
#define RIL_REQUEST_OEM_IMS_TRIGGER_EPS_FALLBACK                (RIL_OEM_REQUEST_BASE + 684)
#define RIL_REQUEST_OEM_IMS_SET_SRVCC_CALL_INFO                 (RIL_OEM_REQUEST_BASE + 685)
#define RIL_REQUEST_OEM_IMS_MT_CALL_GUARDTMR_STATUS_IND         (RIL_OEM_REQUEST_BASE + 686)

/*REQ IMS MEDIA HAL*/
#define RIL_REQUEST_OEM_IMS_TEST_RCM                           (RIL_OEM_REQUEST_BASE + 700)
#define RIL_REQUEST_OEM_IMS_MEDIA_INIT                         (RIL_OEM_REQUEST_BASE + 701)
#define RIL_REQUEST_OEM_IMS_MEDIA_OPEN_SESSION                 (RIL_OEM_REQUEST_BASE + 702)
#define RIL_REQUEST_OEM_IMS_MEDIA_CLOSE_SESSION                (RIL_OEM_REQUEST_BASE + 703)
#define RIL_REQUEST_OEM_IMS_MEDIA_MODIFY_SESSION               (RIL_OEM_REQUEST_BASE + 704)
#define RIL_REQUEST_OEM_IMS_MEDIA_SEND_DTMF                    (RIL_OEM_REQUEST_BASE + 705)
#define RIL_REQUEST_OEM_IMS_MEDIA_START_DTMF                   (RIL_OEM_REQUEST_BASE + 706)
#define RIL_REQUEST_OEM_IMS_MEDIA_STOP_DTMF                    (RIL_OEM_REQUEST_BASE + 707)
#define RIL_REQUEST_OEM_IMS_MEDIA_SEND_TEXT                    (RIL_OEM_REQUEST_BASE + 708)
#define RIL_REQUEST_OEM_IMS_MEDIA_SEND_HEADER_EXTENSION        (RIL_OEM_REQUEST_BASE + 709)
#define RIL_REQUEST_OEM_IMS_MEDIA_SET_MEDIA_QUALITY_THRESHOLD  (RIL_OEM_REQUEST_BASE + 710)
#define RIL_REQUEST_OEM_IMS_MEDIA_GET_OPERATION_MODE           (RIL_OEM_REQUEST_BASE + 711)
#define RIL_REQUEST_OEM_IMS_MEDIA_WIFI_CONFIG                  (RIL_OEM_REQUEST_BASE + 712)
#define RIL_REQUEST_OEM_IMS_MEDIA_QUERY_MAC_CE_INFO            (RIL_OEM_REQUEST_BASE + 713)

#define RIL_REQUEST_OEM_UPDATE_EMERGENCY_NUMBER_LIST            (RIL_OEM_REQUEST_BASE + 903)

#define RIL_REQUEST_OEM_MISC_SET_TELEPHONY_STATUS_LOGGING       (RIL_OEM_REQUEST_BASE + 989)
#define RIL_REQUEST_OEN_MISC_TEST_UNSOL                         (RIL_OEM_REQUEST_BASE + 990)


/******************** OEM Specific Requests *****************************/
#define RIL_REQUEST_OEM_SPECIFIC_BASE                           (RIL_OEM_REQUEST_BASE + 1000)

/******************** OEM1 ********************/
#define RIL_REQUEST_OEM_STORE_ADB_SERIAL_NUMBER                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 100)
#define RIL_REQUEST_OEM_READ_ADB_SERIAL_NUMBER                  (RIL_REQUEST_OEM_SPECIFIC_BASE + 101)

/******************** OEM2 ********************/
/* P-SENSOR */
#define RIL_REQUEST_OEM_PSENSOR_SET_STATUS                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 210)
#define RIL_UNSOL_OEM_PSENSOR_CONTROL_STATE                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 211)
#define RIL_REQUEST_OEM_SET_CA_BANDWIDTH_FILTER                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 212)
#define RIL_REQUEST_OEM_ICC_DEPERSONALIZATION                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 213)

/* VSIM */
#define RIL_REQUEST_OEM_VSIM_NOTIFICATION                       (RIL_REQUEST_OEM_SPECIFIC_BASE + 220)
#define RIL_REQUEST_OEM_VSIM_OPERATION                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 221)

/* SAR */
#define RIL_REQUEST_OEM_SAR_SET_STATE                           (RIL_REQUEST_OEM_SPECIFIC_BASE + 230)
#define RIL_REQUEST_OEM_SAR_GET_STATE                           (RIL_REQUEST_OEM_SPECIFIC_BASE + 231)

#define RIL_REQUEST_OEM_GET_RADIO_NODE                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 240)
#define RIL_REQUEST_OEM_SET_RADIO_NODE                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 241)
#define RIL_REQUEST_OEM_GET_PROVISION_UPDATE_REQUEST            (RIL_REQUEST_OEM_SPECIFIC_BASE + 242)
#define RIL_REQUEST_OEM_SET_PROVISION_UPDATE_DONE_REQUEST       (RIL_REQUEST_OEM_SPECIFIC_BASE + 243)
#define RIL_REQUEST_OEM_RADIO_CONFIG_RESET                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 244)

/* SE13 Table */
#define RIL_REQUEST_OEM_GET_PLMN_NAME_FROM_SE13TABLE            0x0A0006

/******************** OEM5 ********************/
#define RIL_REQUEST_OEM_SET_SELFLOG                             (RIL_REQUEST_OEM_SPECIFIC_BASE + 500)
#define RIL_REQUEST_OEM_GET_SELFLOG_STATUS                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 501)
#define RIL_REQUEST_OEM_MODEM_INFO                              (RIL_REQUEST_OEM_SPECIFIC_BASE + 502)
#define RIL_REQUEST_OEM_SWITCH_MODEM_FUNCTION                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 504)
#define RIL_REQUEST_OEM_REQ_SET_PDCP_DISCARD_TIMER              (RIL_REQUEST_OEM_SPECIFIC_BASE + 505)
#define RIL_REQUEST_OEM_GET_CQI_INFO                            (RIL_REQUEST_OEM_SPECIFIC_BASE + 506)
#define RIL_REQUEST_OEM_SET_SAR_SETTING                         (RIL_REQUEST_OEM_SPECIFIC_BASE + 507)
#define RIL_REQUEST_OEM_SET_GMO_SWITCH                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 508)
#define RIL_REQUEST_OEM_SET_TCS_FCI                             (RIL_REQUEST_OEM_SPECIFIC_BASE + 509)
#define RIL_REQUEST_OEM_GET_TCS_FCI                             (RIL_REQUEST_OEM_SPECIFIC_BASE + 510)
#define RIL_REQUEST_OEM_SET_SELFLOG_PROFILE                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 511)
#define RIL_REQUEST_OEM_SET_FORBID_LTE_CELL                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 512)
#define RIL_REQUEST_OEM_SET_ELEVATOR_SENSOR                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 513)
#define RIL_REQUEST_OEM_GET_MODEM_ACTIVITY_INFO                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 514)
#define RIL_REQUEST_OEM_SET_SVN                                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 515)
#define RIL_REQUEST_OEM_SET_FORBID_FREQUENCY                    (RIL_REQUEST_OEM_SPECIFIC_BASE + 516)
#define RIL_REQUEST_OEM_SET_FORBID_LTE_BAND                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 517)
#define RIL_REQUEST_OEM_SET_FORBID_LTE_TAC                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 518)
#define RIL_REQUEST_OEM_SET_SELFLOG_TCP_DUMP_MODE               (RIL_REQUEST_OEM_SPECIFIC_BASE + 519)
#define RIL_REQUEST_OEM_SET_ALL_DIV_SETTING                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 520)
#define RIL_REQUEST_OEM_SET_BSR_PARA                            (RIL_REQUEST_OEM_SPECIFIC_BASE + 521)
#define RIL_REQUEST_OEM_SET_DRDV                                (RIL_REQUEST_OEM_SPECIFIC_BASE + 522)
#define RIL_REQUEST_OEM_SET_AHEAD_RRE                           (RIL_REQUEST_OEM_SPECIFIC_BASE + 523)
#define RIL_REQUEST_OEM_SET_FORBID_NR_CELL                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 524)
#define RIL_REQUEST_OEM_GET_CDMA_CAPABILITY_INFO                (RIL_REQUEST_OEM_SPECIFIC_BASE + 525)
#define RIL_REQUEST_OEM_SET_SRS_PWR_LIMIT                       (RIL_REQUEST_OEM_SPECIFIC_BASE + 526)
#define RIL_REQUEST_OEM_SET_TRACE_DUMP_CFG                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 527)
#define RIL_REQUEST_OEM_GET_TRACE_DUMP_CFG                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 528)
#define RIL_REQUEST_OEM_SET_UE_OPERATION_MODE                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 529)
#define RIL_REQUEST_OEM_GET_UE_OPERATION_MODE                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 530)
#define RIL_REQUEST_OEM_SET_NRRRM_MIN_REQ_ENABLE                (RIL_REQUEST_OEM_SPECIFIC_BASE + 533)
#define RIL_REQUEST_OEM_GET_NRRRM_MIN_REQ_ENABLE                (RIL_REQUEST_OEM_SPECIFIC_BASE + 534)
#define RIL_REQUEST_OEM_SET_PWR_DETECT_THR                      (RIL_REQUEST_OEM_SPECIFIC_BASE + 535)
#define RIL_REQUEST_OEM_SET_VCRT                                (RIL_REQUEST_OEM_SPECIFIC_BASE + 536)
#define RIL_REQUEST_OEM_SET_ENABLE_N28                          (RIL_REQUEST_OEM_SPECIFIC_BASE + 537)
#define RIL_REQUEST_OEM_SET_UL_MIMO                             (RIL_REQUEST_OEM_SPECIFIC_BASE + 538)
#define RIL_REQUEST_OEM_GET_BINARY_VERSION_INFO                 (RIL_REQUEST_OEM_SPECIFIC_BASE + 539)
#define RIL_REQUEST_OEM_SET_BTL_BUFMAX_SIZE                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 540)
#define RIL_REQUEST_OEM_GET_VCRT                                (RIL_REQUEST_OEM_SPECIFIC_BASE + 541)
#define RIL_REQUEST_OEM_SET_NR_DISABLE_BAND                     (RIL_REQUEST_OEM_SPECIFIC_BASE + 542)

/******************** OEM7 ********************/
#define RIL_REQUEST_OEM_SET_CP_CARRIER_CONFIG                   (RIL_REQUEST_OEM_SPECIFIC_BASE + 600)

/******************** OEM Unsolicited responses ********************/
#define RIL_UNSOL_OEM_MODEM_STATE_CHANGED                       (RIL_OEM_UNSOL_RESPONSE_BASE + 3)
#define RIL_UNSOL_OEM_LAST_CALL_FAIL_CAUSE                      (RIL_OEM_UNSOL_RESPONSE_BASE + 4)
#define RIL_UNSOL_OEM_NAS_TIMER_STATUS                          (RIL_OEM_UNSOL_RESPONSE_BASE + 7)
#define RIL_UNSOL_OEM_IMS_BEARER_INFO                           (RIL_OEM_UNSOL_RESPONSE_BASE + 101)
#define RIL_UNSOL_OEM_IMS_EMERGENCY_ACT_INFO                    (RIL_OEM_UNSOL_RESPONSE_BASE + 102)
#define RIL_UNSOL_OEM_IMS_SET_SRVCC_INFO                        (RIL_OEM_UNSOL_RESPONSE_BASE + 103)
#define RIL_UNSOL_OEM_IMS_EMERGENCY_CALL_LIST                   (RIL_OEM_UNSOL_RESPONSE_BASE + 104)
#define RIL_UNSOL_OEM_IMS_SUPPORT_SERVICE                       (RIL_OEM_UNSOL_RESPONSE_BASE + 105)
#define RIL_UNSOL_OEM_IMS_OPEN_CARRIER_INFO                     (RIL_OEM_UNSOL_RESPONSE_BASE + 106)
#define RIL_UNSOL_OEM_SCAN_RSSI_RESULT                          (RIL_OEM_UNSOL_RESPONSE_BASE + 107)
#define RIL_UNSOL_OEM_FORWARDING_AT_COMMAND                     (RIL_OEM_UNSOL_RESPONSE_BASE + 108)
#define RIL_UNSOL_OEM_RINGBACK_TONE_BY_NETWORK                  (RIL_OEM_UNSOL_RESPONSE_BASE + 109)
#define RIL_UNSOL_OEM_LTE_RRC_STATE_CHANGED                     (RIL_OEM_UNSOL_RESPONSE_BASE + 110)

#define RIL_UNSOL_OEM_DISPLAY_ENG_MODE                          (RIL_OEM_UNSOL_RESPONSE_BASE + 111)
#define RIL_UNSOL_OEM_AM                                        (RIL_OEM_UNSOL_RESPONSE_BASE + 112)
#define RIL_UNSOL_OEM_PIN_CONTROL                               (RIL_OEM_UNSOL_RESPONSE_BASE + 113)
#define RIL_UNSOL_OEM_VSIM_OPERATION                            (RIL_OEM_UNSOL_RESPONSE_BASE + 114)
#define RIL_UNSOL_OEM_TOTAL_OOS                                 (RIL_OEM_UNSOL_RESPONSE_BASE + 115)
#define RIL_UNSOL_OEM_PS_DATA_OFF_STATUS                        (RIL_OEM_UNSOL_RESPONSE_BASE + 117)
#define RIL_UNSOL_OEM_SIM_OPERATOR_NUMERIC                      (RIL_OEM_UNSOL_RESPONSE_BASE + 118)
#define RIL_UNSOL_OEM_BARRING_INFO_LOCATION_SANTIZED            (RIL_OEM_UNSOL_RESPONSE_BASE + 119)
#define RIL_UNSOL_OEM_PHYSICAL_CHANNEL_CONFIGS                  (RIL_OEM_UNSOL_RESPONSE_BASE + 120)

//AIMS support start ---------------------
#define RIL_UNSOL_OEM_AIMS_CALL_RING                            (RIL_OEM_UNSOL_RESPONSE_BASE + 300)
#define RIL_UNSOL_OEM_AIMS_CALL_STATUS                          (RIL_OEM_UNSOL_RESPONSE_BASE + 301)
#define RIL_UNSOL_OEM_AIMS_REGISTRATION                         (RIL_OEM_UNSOL_RESPONSE_BASE + 302)
#define RIL_UNSOL_OEM_AIMS_CALL_MODIFY                          (RIL_OEM_UNSOL_RESPONSE_BASE + 303)
#define RIL_UNSOL_OEM_AIMS_FRAME_TIME                           (RIL_OEM_UNSOL_RESPONSE_BASE + 304)
#define RIL_UNSOL_OEM_AIMS_SUPP_SVC_NOTIFICATION                (RIL_OEM_UNSOL_RESPONSE_BASE + 305)
#define RIL_UNSOL_OEM_AIMS_NEW_SMS                              (RIL_OEM_UNSOL_RESPONSE_BASE + 306)
#define RIL_UNSOL_OEM_AIMS_NEW_SMS_STATUS_REPORT                (RIL_OEM_UNSOL_RESPONSE_BASE + 307)
#define RIL_UNSOL_OEM_AIMS_ON_USSD                              (RIL_OEM_UNSOL_RESPONSE_BASE + 308)
#define RIL_UNSOL_OEM_AIMS_CONFERENCE_CALL_EVENT                (RIL_OEM_UNSOL_RESPONSE_BASE + 309)
#define RIL_UNSOL_OEM_AIMS_PAYLOAD_INFO                         (RIL_OEM_UNSOL_RESPONSE_BASE + 310)
#define RIL_UNSOL_OEM_AIMS_VOWIFI_HO_CALL_INFO                  (RIL_OEM_UNSOL_RESPONSE_BASE + 311)
#define RIL_UNSOL_OEM_AIMS_NEW_CDMA_SMS                         (RIL_OEM_UNSOL_RESPONSE_BASE + 312)
#define RIL_UNSOL_OEM_AIMS_RINGBACK_TONE                        (RIL_OEM_UNSOL_RESPONSE_BASE + 313)
#define RIL_UNSOL_OEM_AIMS_CALL_MANAGE                          (RIL_OEM_UNSOL_RESPONSE_BASE + 314)
#define RIL_UNSOL_OEM_AIMS_CONF_CALL_ADD_REMOVE_USER            (RIL_OEM_UNSOL_RESPONSE_BASE + 315)
#define RIL_UNSOL_OEM_AIMS_ENHANCED_CONF_CALL                   (RIL_OEM_UNSOL_RESPONSE_BASE + 316)
#define RIL_UNSOL_OEM_AIMS_CALL_MODIFY_RSP                      (RIL_OEM_UNSOL_RESPONSE_BASE + 317)
#define RIL_UNSOL_OEM_AIMS_DTMF_EVENT                           (RIL_OEM_UNSOL_RESPONSE_BASE + 318)
#define RIL_UNSOL_OEM_AIMS_RTT_NEW_TEXT                         (RIL_OEM_UNSOL_RESPONSE_BASE + 319)
#define RIL_UNSOL_OEM_AIMS_RTT_FAIL_SENDING_TEXT                (RIL_OEM_UNSOL_RESPONSE_BASE + 320)
#define RIL_UNSOL_OEM_AIMS_RCS_MULTI_FRAME                      (RIL_OEM_UNSOL_RESPONSE_BASE + 321)
#define RIL_UNSOL_OEM_AIMS_RCS_CHAT                             (RIL_OEM_UNSOL_RESPONSE_BASE + 322)
#define RIL_UNSOL_OEM_AIMS_RCS_GROUP_CHAT                       (RIL_OEM_UNSOL_RESPONSE_BASE + 323)
#define RIL_UNSOL_OEM_AIMS_RCS_OFFLINE_MODE                     (RIL_OEM_UNSOL_RESPONSE_BASE + 324)
#define RIL_UNSOL_OEM_AIMS_RCS_FILE_TRANSFER                    (RIL_OEM_UNSOL_RESPONSE_BASE + 325)
#define RIL_UNSOL_OEM_AIMS_RCS_COMMON_MESSAGE                   (RIL_OEM_UNSOL_RESPONSE_BASE + 326)
#define RIL_UNSOL_OEM_AIMS_RCS_CONTENT_SHARE                    (RIL_OEM_UNSOL_RESPONSE_BASE + 327)
#define RIL_UNSOL_OEM_AIMS_RCS_PRESENCE                         (RIL_OEM_UNSOL_RESPONSE_BASE + 328)
#define RIL_UNSOL_OEM_AIMS_RCS_XCAP_MANAGE                      (RIL_OEM_UNSOL_RESPONSE_BASE + 329)
#define RIL_UNSOL_OEM_AIMS_RCS_CONFIG_MANAGE                    (RIL_OEM_UNSOL_RESPONSE_BASE + 330)
#define RIL_UNSOL_OEM_AIMS_RCS_TLS_MANAGE                       (RIL_OEM_UNSOL_RESPONSE_BASE + 331)
#define RIL_UNSOL_OEM_AIMS_EXIT_EMERGENCY_CB_MODE               (RIL_OEM_UNSOL_RESPONSE_BASE + 332)
#define RIL_UNSOL_OEM_AIMS_AC_BARRING_INFO                      (RIL_OEM_UNSOL_RESPONSE_BASE + 333)
#define RIL_UNSOL_OEM_AIMS_DIALOG_INFO                          (RIL_OEM_UNSOL_RESPONSE_BASE + 334)
#define RIL_UNSOL_OEM_AIMS_MEDIA_STATUS                         (RIL_OEM_UNSOL_RESPONSE_BASE + 335)
#define RIL_UNSOL_OEM_AIMS_SIP_MSG_INFO                         (RIL_OEM_UNSOL_RESPONSE_BASE + 336)
#define RIL_UNSOL_OEM_AIMS_VOICE_RTP_QUALITY                    (RIL_OEM_UNSOL_RESPONSE_BASE + 337)
#define RIL_UNSOL_OEM_AIMS_RTP_RX_STATISTICS                    (RIL_OEM_UNSOL_RESPONSE_BASE + 338)
#define RIL_UNSOL_OEM_AIMS_FEAT_SUPP                            (RIL_OEM_UNSOL_RESPONSE_BASE + 339)
#define RIL_UNSOL_OEM_AIMS_AT_CMD_FORWARDING                    (RIL_OEM_UNSOL_RESPONSE_BASE + 340)
#define RIL_UNSOL_OEM_AIMS_EXPIRE_INFO                          (RIL_OEM_UNSOL_RESPONSE_BASE + 341)
#define RIL_UNSOL_OEM_AIMS_CALL_TRANSFER_RSP                    (RIL_OEM_UNSOL_RESPONSE_BASE + 342)
#define RIL_UNSOL_OEM_AIMS_CALL_TRANSFER                        (RIL_OEM_UNSOL_RESPONSE_BASE + 343)
#define RIL_UNSOL_OEM_AIMS_EMERGENCY_NUMBER_LIST                (RIL_OEM_UNSOL_RESPONSE_BASE + 344)
#define RIL_UNSOL_OEM_AIMS_MWI_INFO                             (RIL_OEM_UNSOL_RESPONSE_BASE + 345)
#define RIL_UNSOL_OEM_AIMS_COMPOSER_MMTEL                       (RIL_OEM_UNSOL_RESPONSE_BASE + 346)
#define RIL_UNSOL_OEM_AIMS_RTP_HEADER_EXTENSION_TYPE            (RIL_OEM_UNSOL_RESPONSE_BASE + 347)
#define RIL_UNSOL_OEM_AIMS_RTP_HEADER_EXTENSION                 (RIL_OEM_UNSOL_RESPONSE_BASE + 348)
#define RIL_UNSOL_OEM_AIMS_SIP_CONFIG                           (RIL_OEM_UNSOL_RESPONSE_BASE + 349)
#define RIL_UNSOL_OEM_AIMS_UL_SIP_MSG_RESULT                    (RIL_OEM_UNSOL_RESPONSE_BASE + 350)
#define RIL_UNSOL_OEM_AIMS_SEND_DL_SIP_MSG                      (RIL_OEM_UNSOL_RESPONSE_BASE + 351)
#define RIL_UNSOL_OEM_AIMS_ENRICHED_CALLING                     (RIL_OEM_UNSOL_RESPONSE_BASE + 352)
#define RIL_UNSOL_OEM_AIMS_RADIO_POWER_STATE                    (RIL_OEM_UNSOL_RESPONSE_BASE + 353)
#define RIL_UNSOL_OEM_AIMS_DC_SESS_UPDATE                       (RIL_OEM_UNSOL_RESPONSE_BASE + 354)
#define RIL_UNSOL_OEM_AIMS_DC_SESSION_MANAGE                    (RIL_OEM_UNSOL_RESPONSE_BASE + 355)
#define RIL_UNSOL_OEM_AIMS_DC_SESS_MODIFY                       (RIL_OEM_UNSOL_RESPONSE_BASE + 356)
#define RIL_UNSOL_OEM_AIMS_CODEC_INFO                           (RIL_OEM_UNSOL_RESPONSE_BASE + 357)
//AIMS support end ---------------------

//AGPS support start ---------------------
#define RIL_UNSOL_OEM_GPS_MEASURE_POS_REQ                       (RIL_OEM_UNSOL_RESPONSE_BASE + 400)
#define RIL_UNSOL_OEM_GPS_ASSIST_DATA                           (RIL_OEM_UNSOL_RESPONSE_BASE + 401)
#define RIL_UNSOL_OEM_GPS_RELEASE_GPS                           (RIL_OEM_UNSOL_RESPONSE_BASE + 402)
#define RIL_UNSOL_OEM_GPS_MT_LOCATION_REQUEST                   (RIL_OEM_UNSOL_RESPONSE_BASE + 403)
#define RIL_UNSOL_OEM_GPS_RESET_GPS_ASSIST_DATA                 (RIL_OEM_UNSOL_RESPONSE_BASE + 404)
#define RIL_UNSOL_OEM_GPS_LPP_REQUEST_CAPABILITIES              (RIL_OEM_UNSOL_RESPONSE_BASE + 405)
#define RIL_UNSOL_OEM_GPS_LPP_PROVIDE_ASSIST_DATA               (RIL_OEM_UNSOL_RESPONSE_BASE + 406)
#define RIL_UNSOL_OEM_GPS_LPP_REQUEST_LOCATION_INFO             (RIL_OEM_UNSOL_RESPONSE_BASE + 407)
#define RIL_UNSOL_OEM_GPS_LPP_GPS_ERROR_IND                     (RIL_OEM_UNSOL_RESPONSE_BASE + 408)
#define RIL_UNSOL_OEM_GPS_SUPL_LPP_DATA_INFO                    (RIL_OEM_UNSOL_RESPONSE_BASE + 409)
#define RIL_UNSOL_OEM_GPS_SUPL_NI_MESSAGE                       (RIL_OEM_UNSOL_RESPONSE_BASE + 410)
#define RIL_UNSOL_OEM_GPS_SUPL_NI_READY                         (RIL_OEM_UNSOL_RESPONSE_BASE + 411)
#define RIL_UNSOL_OEM_GPS_START_MDT_LOC                         (RIL_OEM_UNSOL_RESPONSE_BASE + 412)
#define RIL_UNSOL_OEM_GPS_LPP_UPDATE_UE_LOC_INFO                (RIL_OEM_UNSOL_RESPONSE_BASE + 413)
#define RIL_UNSOL_OEM_GPS_LOCK_MODE                             (RIL_OEM_UNSOL_RESPONSE_BASE + 414)
#define RIL_UNSOL_OEM_GPS_CAMPING_ON_LTE                        (RIL_OEM_UNSOL_RESPONSE_BASE + 415)

// CDMA & HEDGE GANSS
#define RIL_UNSOL_OEM_GPS_3GPP_SEND_GANSS_ASSIT_DATA            (RIL_OEM_UNSOL_RESPONSE_BASE + 450)
#define RIL_UNSOL_OEM_GPS_GANSS_MEAS_POS_MSG                    (RIL_OEM_UNSOL_RESPONSE_BASE + 451)
#define RIL_UNSOL_OEM_GPS_CDMA_GPS_POWER_ON                     (RIL_OEM_UNSOL_RESPONSE_BASE + 452)
#define RIL_UNSOL_OEM_GPS_CDMA_SEND_ACQUSITION_ASSIT_DATA       (RIL_OEM_UNSOL_RESPONSE_BASE + 453)
#define RIL_UNSOL_OEM_GPS_CDMA_SESSION_CANCELLATION             (RIL_OEM_UNSOL_RESPONSE_BASE + 454)
#define RIL_UNSOL_OEM_GPS_GANSS_AP_POS_CAP_REQ                  (RIL_OEM_UNSOL_RESPONSE_BASE + 455)
//AGPS support end ---------------------


/* WFC */
#define RIL_UNSOL_OEM_WFC_RTP_RTCP_TIMEOUT                      (RIL_OEM_UNSOL_RESPONSE_BASE + 500)
#define RIL_UNSOL_OEM_WFC_FIRST_RTP                             (RIL_OEM_UNSOL_RESPONSE_BASE + 501)
#define RIL_UNSOL_OEM_WFC_RTCP_RX_SR                            (RIL_OEM_UNSOL_RESPONSE_BASE + 502)
#define RIL_UNSOL_OEM_WFC_RCV_DTMF_NOTI                         (RIL_OEM_UNSOL_RESPONSE_BASE + 503)
#define RIL_UNSOL_OEM_WFC_SIGNAL_STRENGTH                       (RIL_OEM_UNSOL_RESPONSE_BASE + 504)

/* Secure Element */
#define RIL_UNSOL_OEM_SE_SIM_STATE_CHANGED                      (RIL_OEM_UNSOL_RESPONSE_BASE + 520)

/* eMBMS */
#define RIL_UNSOL_OEM_EMBMS_COVERAGE                            (RIL_OEM_UNSOL_RESPONSE_BASE + 540)
#define RIL_UNSOL_OEM_EMBMS_SESSION_LIST                        (RIL_OEM_UNSOL_RESPONSE_BASE + 541)
#define RIL_UNSOL_OEM_EMBMS_SIGNAL_STRENGTH                     (RIL_OEM_UNSOL_RESPONSE_BASE + 542)
#define RIL_UNSOL_OEM_EMBMS_NETWORK_TIME                        (RIL_OEM_UNSOL_RESPONSE_BASE + 543)
#define RIL_UNSOL_OEM_EMBMS_SAI_LIST                            (RIL_OEM_UNSOL_RESPONSE_BASE + 544)
#define RIL_UNSOL_OEM_EMBMS_GLOBAL_CELL_ID                      (RIL_OEM_UNSOL_RESPONSE_BASE + 545)
#define RIL_UNSOL_OEM_EMBMS_RADIO_STATE_CHANGED                 (RIL_OEM_UNSOL_RESPONSE_BASE + 546)
#define RIL_UNSOL_OEM_EMBMS_MODEM_STATUS                        (RIL_OEM_UNSOL_RESPONSE_BASE + 547)
#define RIL_UNSOL_OEM_EMBMS_SESSION_CONTROL                     (RIL_OEM_UNSOL_RESPONSE_BASE + 548)

/* BIP Channel Manager */
#define RIL_UNSOL_OEM_WIFI_STATUS_REQUEST                       (RIL_OEM_UNSOL_RESPONSE_BASE + 560)
#define RIL_UNSOL_OEM_WIFI_OPEN_CHANNEL_REQUEST                 (RIL_OEM_UNSOL_RESPONSE_BASE + 561)
#define RIL_UNSOL_OEM_WIFI_SEND_DATA_REQUEST                    (RIL_OEM_UNSOL_RESPONSE_BASE + 562)
#define RIL_UNSOL_OEM_WIFI_RECEIVE_DATA_REQUEST                 (RIL_OEM_UNSOL_RESPONSE_BASE + 563)
#define RIL_UNSOL_OEM_WIFI_CLOSE_CHANNEL_REQUEST                (RIL_OEM_UNSOL_RESPONSE_BASE + 564)

/* IMS MEDIA UNSOL REQ*/
#define RIL_UNSOL_OEM_IMS_TEST_RCM                             (RIL_OEM_UNSOL_RESPONSE_BASE + 650)
#define RIL_UNSOL_OEM_IMS_MEDIA_ON_DTMF_RECEIVED               (RIL_OEM_UNSOL_RESPONSE_BASE + 651)
#define RIL_UNSOL_OEM_IMS_MEDIA_ON_TEXT_RECEIVED               (RIL_OEM_UNSOL_RESPONSE_BASE + 652)
#define RIL_UNSOL_OEM_IMS_MEDIA_ON_HEADER_EXTENSION_RECEIVED   (RIL_OEM_UNSOL_RESPONSE_BASE + 653)
#define RIL_UNSOL_OEM_IMS_MEDIA_ON_FIRST_MEDIA_RECEIVED        (RIL_OEM_UNSOL_RESPONSE_BASE + 654)
#define RIL_UNSOL_OEM_IMS_MEDIA_NOTIFY_MEDIA_INACTIVITY        (RIL_OEM_UNSOL_RESPONSE_BASE + 655)
#define RIL_UNSOL_OEM_IMS_MEDIA_NOTIFY_PACKET_LOSS             (RIL_OEM_UNSOL_RESPONSE_BASE + 656)
#define RIL_UNSOL_OEM_IMS_MEDIA_NOTIFY_JITTER                  (RIL_OEM_UNSOL_RESPONSE_BASE + 657)
#define RIL_UNSOL_OEM_IMS_MEDIA_ON_CALL_QUALITY_CHANGED        (RIL_OEM_UNSOL_RESPONSE_BASE + 658)
#define RIL_UNSOL_OEM_IMS_MEDIA_TRIGGER_ANBR_QUERY             (RIL_OEM_UNSOL_RESPONSE_BASE + 659)
#define RIL_UNSOL_OEM_IMS_MEDIA_MAC_CE_INFO                    (RIL_OEM_UNSOL_RESPONSE_BASE + 660)

#define RIL_UNSOL_OEM_IMS_TRIGGER_EPS_FALLBACK                 (RIL_OEM_UNSOL_RESPONSE_BASE + 670)
#define RIL_UNSOL_OEM_IMS_MT_CSFB                              (RIL_OEM_UNSOL_RESPONSE_BASE + 671)

/******************** OEM Specific Unsolicited responses ********************/
#define RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE                    (RIL_OEM_UNSOL_RESPONSE_BASE + 1000)

/******************** OEM2 ********************/
#define RIL_UNSOL_OEM_SAR_RF_CONNECTION                         (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 200)
#define RIL_UNSOL_OEM_CA_BANDWIDTH_FILTER                       (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 201)

/******************** OEM5 ********************/
#define RIL_UNSOL_OEM_SELFLOG_STATUS                            (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 500)
#define RIL_UNSOL_OEM_MODEM_INFO                                (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 501)
#define RIL_UNSOL_OEM_FREQUENCY_INFO                            (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 503)
#define RIL_UNSOL_OEM_AMBR                                      (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 504)
#define RIL_UNSOL_B2_B1_CONFIG_INFO                             (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 505)
#define RIL_UNSOL_OEM_BASESTATION_INFO                          (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 506)
#define RIL_UNSOL_OEM_DROPPED_MT_CALL_INFO                      (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 507)

/******************** OEM7 ********************/
#define RIL_UNSOL_OEM_CP_CARRIER_CONFIG_CHANGED                 (RIL_OEM_SPECIFIC_UNSOL_RESPONSE_BASE + 700)

#endif // _RIL_OEM_H
