/*
 * Copyright (c) 2022 Samsung Electronics Co., Ltd All Rights Reserved
 * PROPRIETARY/CONFIDENTIAL
 *
 * This software is the confidential and proprietary information of
 * SAMSUNG ELECTRONICS ("Confidential Information").
 *
 * You shall not disclose such Confidential Information and shall use it
 * only in accordance with the terms of the license agreement
 * you entered into with SAMSUNG ELECTRONICS.
 *
 * SAMSUNG make no representations or warranties about the suitability of
 * the software, either express or implied, including but not limited to
 * the implied warranties of merchantability, fitness for a particular
 * purpose, or non-infringement. SAMSUNG shall not be liable for any
 * damages suffered by license as a result of using, modifying or
 * distributing this software or its derivatives.
 */
#include <testutils.h>
#include <hidl/1.6/radio_hidl_utils_1_6.h>

using namespace ::android::hardware::radio;

TEST(radio_hidl_utils_1_6, RadioResponseBase_1_6) {
    TestChecker checker;
    auto test = ::android::sp<RadioResponseBase_1_6>::make();
    test->getIccCardStatusResponse({}, {});
    test->supplyIccPinForAppResponse({}, 0);
    test->supplyIccPukForAppResponse({}, 0);
    test->supplyIccPin2ForAppResponse({}, 0);
    test->supplyIccPuk2ForAppResponse({}, 0);
    test->changeIccPinForAppResponse({}, 0);
    test->changeIccPin2ForAppResponse({}, 0);
    test->supplyNetworkDepersonalizationResponse({}, 0);
    test->getCurrentCallsResponse({}, {});
    test->dialResponse({});
    test->getIMSIForAppResponse({}, "");
    test->hangupConnectionResponse({});
    test->hangupWaitingOrBackgroundResponse({});
    test->hangupForegroundResumeBackgroundResponse({});
    test->switchWaitingOrHoldingAndActiveResponse({});
    test->conferenceResponse({});
    test->rejectCallResponse({});
    test->getLastCallFailCauseResponse({}, {});
    test->getSignalStrengthResponse({}, {});
    test->getVoiceRegistrationStateResponse({}, {});
    test->getDataRegistrationStateResponse({}, {});
    test->getOperatorResponse({}, "", "", "");
    test->setRadioPowerResponse({});
    test->sendDtmfResponse({});
    test->sendSmsResponse({}, {});
    test->sendSMSExpectMoreResponse({}, {});
    test->setupDataCallResponse({}, {});
    test->iccIOForAppResponse({}, {});
    test->sendUssdResponse({});
    test->cancelPendingUssdResponse({});
    test->getClirResponse({}, 0, 0);
    test->setClirResponse({});
    test->getCallForwardStatusResponse({}, {});
    test->setCallForwardResponse({});
    test->getCallWaitingResponse({}, true, 0);
    test->setCallWaitingResponse({});
    test->acknowledgeLastIncomingGsmSmsResponse({});
    test->acceptCallResponse({});
    test->deactivateDataCallResponse({});
    test->getFacilityLockForAppResponse({}, 0);
    test->setFacilityLockForAppResponse({}, 0);
    test->setBarringPasswordResponse({});
    test->getNetworkSelectionModeResponse({}, true);
    test->setNetworkSelectionModeAutomaticResponse({});
    test->setNetworkSelectionModeManualResponse({});
    test->getAvailableNetworksResponse({}, {});
    test->startDtmfResponse({});
    test->stopDtmfResponse({});
    test->getBasebandVersionResponse({}, "");
    test->separateConnectionResponse({});
    test->setMuteResponse({});
    test->getMuteResponse({}, true);
    test->getClipResponse({}, V1_0::ClipStatus(0));
    test->getDataCallListResponse({}, {});
    test->sendOemRilRequestRawResponse({}, {});
    test->sendOemRilRequestStringsResponse({}, {});
    test->setSuppServiceNotificationsResponse({});
    test->writeSmsToSimResponse({}, 0);
    test->deleteSmsOnSimResponse({});
    test->setBandModeResponse({});
    test->getAvailableBandModesResponse({}, {});
    test->sendEnvelopeResponse({}, "");
    test->sendTerminalResponseToSimResponse({});
    test->handleStkCallSetupRequestFromSimResponse({});
    test->explicitCallTransferResponse({});
    test->setPreferredNetworkTypeResponse({});
    test->getPreferredNetworkTypeResponse({}, V1_0::PreferredNetworkType(0));
    test->getNeighboringCidsResponse({}, {});
    test->setLocationUpdatesResponse({});
    test->setCdmaSubscriptionSourceResponse({});
    test->setCdmaRoamingPreferenceResponse({});
    test->getCdmaRoamingPreferenceResponse({}, V1_0::CdmaRoamingType(0));
    test->setTTYModeResponse({});
    test->getTTYModeResponse({}, V1_0::TtyMode(0));
    test->setPreferredVoicePrivacyResponse({});
    test->getPreferredVoicePrivacyResponse({}, true);
    test->sendCDMAFeatureCodeResponse({});
    test->sendBurstDtmfResponse({});
    test->sendCdmaSmsResponse({}, {});
    test->acknowledgeLastIncomingCdmaSmsResponse({});
    test->getGsmBroadcastConfigResponse({}, {});
    test->setGsmBroadcastConfigResponse({});
    test->setGsmBroadcastActivationResponse({});
    test->getCdmaBroadcastConfigResponse({}, {});
    test->setCdmaBroadcastConfigResponse({});
    test->setCdmaBroadcastActivationResponse({});
    test->getCDMASubscriptionResponse({}, "", "", "", "", "");
    test->writeSmsToRuimResponse({}, 0);
    test->deleteSmsOnRuimResponse({});
    test->getDeviceIdentityResponse({}, "", "", "", "");
    test->exitEmergencyCallbackModeResponse({});
    test->getSmscAddressResponse({}, {});
    test->setSmscAddressResponse({});
    test->reportSmsMemoryStatusResponse({});
    test->reportStkServiceIsRunningResponse({});
    test->getCdmaSubscriptionSourceResponse({}, V1_0::CdmaSubscriptionSource(0));
    test->requestIsimAuthenticationResponse({}, "");
    test->acknowledgeIncomingGsmSmsWithPduResponse({});
    test->sendEnvelopeWithStatusResponse({}, {});
    test->getVoiceRadioTechnologyResponse({}, V1_0::RadioTechnology(0));
    test->getCellInfoListResponse({}, {});
    test->setCellInfoListRateResponse({});
    test->setInitialAttachApnResponse({});
    test->getImsRegistrationStateResponse({}, true, V1_0::RadioTechnologyFamily(0));
    test->sendImsSmsResponse({}, {});
    test->iccTransmitApduBasicChannelResponse({}, {});
    test->iccOpenLogicalChannelResponse({}, 0, {});
    test->iccCloseLogicalChannelResponse({});
    test->iccTransmitApduLogicalChannelResponse({}, {});
    test->nvReadItemResponse({}, "");
    test->nvWriteItemResponse({});
    test->nvWriteCdmaPrlResponse({});
    test->nvResetConfigResponse({});
    test->setUiccSubscriptionResponse({});
    test->setDataAllowedResponse({});
    test->getHardwareConfigResponse({}, {});
    test->requestIccSimAuthenticationResponse({}, {});
    test->setDataProfileResponse({});
    test->requestShutdownResponse({});
    test->getRadioCapabilityResponse({}, {});
    test->setRadioCapabilityResponse({}, {});
    test->startLceServiceResponse({}, {});
    test->stopLceServiceResponse({}, {});
    test->pullLceDataResponse({}, {});
    test->getModemActivityInfoResponse({}, {});
    test->setAllowedCarriersResponse({}, 0);
    test->getAllowedCarriersResponse({}, true, {});
    test->sendDeviceStateResponse({});
    test->setIndicationFilterResponse({});
    test->setSimCardPowerResponse({});
    test->acknowledgeRequest(0);
    test->setCarrierInfoForImsiEncryptionResponse({});
    test->setSimCardPowerResponse_1_1({});
    test->startNetworkScanResponse({});
    test->stopNetworkScanResponse({});
    test->startKeepaliveResponse({}, {});
    test->stopKeepaliveResponse({});
    test->setSignalStrengthReportingCriteriaResponse({});
    test->setLinkCapacityReportingCriteriaResponse({});
    test->getIccCardStatusResponse_1_2({}, {});
    test->getCurrentCallsResponse_1_2({}, {});
    test->getSignalStrengthResponse_1_2({}, {});
    test->getCellInfoListResponse_1_2({}, {});
    test->getVoiceRegistrationStateResponse_1_2({}, {});
    test->getDataRegistrationStateResponse_1_2({}, {});
    test->setSystemSelectionChannelsResponse({});
    test->enableModemResponse({});
    test->getModemStackStatusResponse({}, true);
    test->emergencyDialResponse({});
    test->startNetworkScanResponse_1_4({});
    test->getSignalStrengthResponse_1_4({}, {});
    test->getCellInfoListResponse_1_4({}, {});
    test->getDataRegistrationStateResponse_1_4({}, {});
    test->getIccCardStatusResponse_1_4({}, {});
    test->getPreferredNetworkTypeBitmapResponse({}, 0);
    test->setPreferredNetworkTypeBitmapResponse({});
    test->getDataCallListResponse_1_4({}, {});
    test->setupDataCallResponse_1_4({}, {});
    test->setAllowedCarriersResponse_1_4({});
    test->getAllowedCarriersResponse_1_4({}, {}, V1_4::SimLockMultiSimPolicy(0));
    test->setSignalStrengthReportingCriteriaResponse_1_5({});
    test->setLinkCapacityReportingCriteriaResponse_1_5({});
    test->enableUiccApplicationsResponse({});
    test->areUiccApplicationsEnabledResponse({}, true);
    test->canToggleUiccApplicationsEnablementResponse({}, true);
    test->setSystemSelectionChannelsResponse_1_5({});
    test->startNetworkScanResponse_1_5({});
    test->setupDataCallResponse_1_5({}, {});
    test->getDataCallListResponse_1_5({}, {});
    test->setInitialAttachApnResponse_1_5({});
    test->setDataProfileResponse_1_5({});
    test->setRadioPowerResponse_1_5({});
    test->setIndicationFilterResponse_1_5({});
    test->getBarringInfoResponse({}, {}, {});
    test->getVoiceRegistrationStateResponse_1_5({}, {});
    test->getDataRegistrationStateResponse_1_5({}, {});
    test->getCellInfoListResponse_1_5({}, {});
    test->setNetworkSelectionModeManualResponse_1_5({});
    test->sendCdmaSmsExpectMoreResponse({}, {});
    test->supplySimDepersonalizationResponse({}, V1_5::PersoSubstate(0), 0);
    test->getIccCardStatusResponse_1_5({}, {});
    test->setRadioPowerResponse_1_6({});
    test->setupDataCallResponse_1_6({}, {});
    test->getDataCallListResponse_1_6({}, {});
    test->sendSmsResponse_1_6({}, {});
    test->sendSmsExpectMoreResponse_1_6({}, {});
    test->sendCdmaSmsResponse_1_6({}, {});
    test->setSimCardPowerResponse_1_6({});
    test->sendCdmaSmsExpectMoreResponse_1_6({}, {});
    test->setNrDualConnectivityStateResponse({});
    test->isNrDualConnectivityEnabledResponse({}, true);
    test->allocatePduSessionIdResponse({}, 0);
    test->releasePduSessionIdResponse({});
    test->startHandoverResponse({});
    test->cancelHandoverResponse({});
    test->setAllowedNetworkTypesBitmapResponse({});
    test->getAllowedNetworkTypesBitmapResponse({}, 0);
    test->setDataThrottlingResponse({});
    test->getSystemSelectionChannelsResponse({}, {});
    test->getSignalStrengthResponse_1_6({}, {});
    test->getCellInfoListResponse_1_6({}, {});
    test->getVoiceRegistrationStateResponse_1_6({}, {});
    test->getDataRegistrationStateResponse_1_6({}, {});
    test->getCurrentCallsResponse_1_6({}, {});
    test->getSlicingConfigResponse({}, {});
    test->getSimPhonebookRecordsResponse({});
    test->getSimPhonebookCapacityResponse({}, {});
    test->updateSimPhonebookRecordsResponse({}, 0);
    checker.checked();
}

TEST(radio_hidl_utils_1_6, RadioIndicationBase_1_6) {
    TestChecker checker;
    auto test = ::android::sp<RadioIndicationBase_1_6>::make();
    test->uiccApplicationsEnablementChanged(V1_0::RadioIndicationType::UNSOLICITED, true);
    test->registrationFailed(V1_0::RadioIndicationType::UNSOLICITED, {}, "", 0, 0, 0);
    test->barringInfoChanged(V1_0::RadioIndicationType::UNSOLICITED, {}, {});
    test->networkScanResult_1_5(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cellInfoList_1_5(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->dataCallListChanged_1_5(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentEmergencyNumberList(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cellInfoList_1_4(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentSignalStrength_1_4(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->networkScanResult_1_4(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentPhysicalChannelConfigs_1_4(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->dataCallListChanged_1_4(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->networkScanResult_1_2(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cellInfoList_1_2(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentLinkCapacityEstimate(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentPhysicalChannelConfigs(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentSignalStrength_1_2(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->carrierInfoForImsiEncryption(V1_0::RadioIndicationType::UNSOLICITED);
    test->networkScanResult(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->keepaliveStatus(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->radioStateChanged(V1_0::RadioIndicationType::UNSOLICITED, V1_0::RadioState(0));
    test->callStateChanged(V1_0::RadioIndicationType::UNSOLICITED);
    test->networkStateChanged(V1_0::RadioIndicationType::UNSOLICITED);
    test->newSms(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->newSmsStatusReport(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->newSmsOnSim(V1_0::RadioIndicationType::UNSOLICITED, 0);
    test->onUssd(V1_0::RadioIndicationType::UNSOLICITED, V1_0::UssdModeType(0), "");
    test->nitzTimeReceived(V1_0::RadioIndicationType::UNSOLICITED, "", 0);
    test->currentSignalStrength(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->dataCallListChanged(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->suppSvcNotify(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->stkSessionEnd(V1_0::RadioIndicationType::UNSOLICITED);
    test->stkProactiveCommand(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->stkEventNotify(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->stkCallSetup(V1_0::RadioIndicationType::UNSOLICITED, 0);
    test->simSmsStorageFull(V1_0::RadioIndicationType::UNSOLICITED);
    test->simRefresh(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->callRing(V1_0::RadioIndicationType::UNSOLICITED, true, {});
    test->simStatusChanged(V1_0::RadioIndicationType::UNSOLICITED);
    test->cdmaNewSms(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->newBroadcastSms(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cdmaRuimSmsStorageFull(V1_0::RadioIndicationType::UNSOLICITED);
    test->restrictedStateChanged(V1_0::RadioIndicationType::UNSOLICITED, V1_0::PhoneRestrictedState(0));
    test->enterEmergencyCallbackMode(V1_0::RadioIndicationType::UNSOLICITED);
    test->cdmaCallWaiting(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cdmaOtaProvisionStatus(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cdmaInfoRec(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->indicateRingbackTone(V1_0::RadioIndicationType::UNSOLICITED, true);
    test->resendIncallMute(V1_0::RadioIndicationType::UNSOLICITED);
    test->cdmaSubscriptionSourceChanged(V1_0::RadioIndicationType::UNSOLICITED, V1_0::CdmaSubscriptionSource(0));
    test->cdmaPrlChanged(V1_0::RadioIndicationType::UNSOLICITED, 0);
    test->exitEmergencyCallbackMode(V1_0::RadioIndicationType::UNSOLICITED);
    test->rilConnected(V1_0::RadioIndicationType::UNSOLICITED);
    test->voiceRadioTechChanged(V1_0::RadioIndicationType::UNSOLICITED, V1_0::RadioTechnology(0));
    test->cellInfoList(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->imsNetworkStateChanged(V1_0::RadioIndicationType::UNSOLICITED);
    test->subscriptionStatusChanged(V1_0::RadioIndicationType::UNSOLICITED, true);
    test->srvccStateNotify(V1_0::RadioIndicationType::UNSOLICITED, V1_0::SrvccState(0));
    test->hardwareConfigChanged(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->radioCapabilityIndication(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->onSupplementaryServiceIndication(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->stkCallControlAlphaNotify(V1_0::RadioIndicationType::UNSOLICITED, "");
    test->lceData(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->pcoData(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->modemReset(V1_0::RadioIndicationType::UNSOLICITED, "");
    test->dataCallListChanged_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->unthrottleApn(V1_0::RadioIndicationType::UNSOLICITED, "");
    test->currentSignalStrength_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->networkScanResult_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->cellInfoList_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentLinkCapacityEstimate_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->currentPhysicalChannelConfigs_1_6(V1_0::RadioIndicationType::UNSOLICITED, {});
    test->simPhonebookChanged(V1_0::RadioIndicationType::UNSOLICITED);
    test->simPhonebookRecordsReceived(V1_0::RadioIndicationType::UNSOLICITED, V1_6::PbReceivedStatus(0), {});
    checker.checked();
}